### ISSUE TITLE
Concurrent commit issue for HadoopTable

### ISSUE THREAD

**Issue by vanliu-tx** [apache/iceberg#1014]
I found that there are still some problem when commit data files to HadoopTable concurrently with the latest main branch which contains this PR (https://github.com/apache/incubator-iceberg/pull/990). @rdblue, could you help to take a look? 

Here is my test code, there are 50 threads, each commit 1,000,000 records (in 10 loops) to a HadoopTable, but the final records in this table is less than expected 50,000,000.

Test code
[TestConcurrentWrite.java.txt](https://github.com/apache/incubator-iceberg/files/4597801/TestConcurrentWrite.java.txt)

Run log 
[run.log](https://github.com/apache/incubator-iceberg/files/4597813/run.log)

Here are the root exception logs:
[2020-05-08 15:43:29,145] pool-1-thread-32 INFO  Committed snapshot 3396938876017046381 (MergeAppend) (org.apache.iceberg.SnapshotProducer:274)
[2020-05-08 15:43:29,147] pool-1-thread-32 WARN  Failed to load committed snapshot, skipping manifest clean-up (org.apache.iceberg.SnapshotProducer:291)
[2020-05-08 15:43:29,147] pool-1-thread-32 WARN  Failed to notify listeners (org.apache.iceberg.SnapshotProducer:308)
java.lang.NullPointerException
	at org.apache.iceberg.MergingSnapshotProducer.updateEvent(MergingSnapshotProducer.java:325)
	at org.apache.iceberg.SnapshotProducer.notifyListeners(SnapshotProducer.java:303)
	at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:298)
	at TestConcurrentWrite$1.run(TestConcurrentWrite.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rdblue** [comment]
The exception you posted is a warning. Are you sure that all of the commits were successful?

**Comment by vanliu-tx** [comment]
@rdblue the commit was successful as the log messages said so. 
"Committed snapshot 3954230755295370661 (MergeAppend) (org.apache.iceberg.SnapshotProducer:274)"

However, when I looked into the final metadata file, this snapshot was not there.

![issue01](https://user-images.githubusercontent.com/64360028/81472969-1e234400-922e-11ea-8a2d-c1c8352d3556.png)

![issue02](https://user-images.githubusercontent.com/64360028/81472971-22e7f800-922e-11ea-9884-0951b3950d80.png)

You can find the metadata files here.
[0509_meta.zip](https://github.com/apache/incubator-iceberg/files/4603399/0509_meta.zip)

There were 8 NPE in the log file run.log, and exactly 8 commits were missing because there were only 493 metadata files in the zip file, which should be 501 files (1 commit for table create, 500 commits for adding data files).

[run.log](https://github.com/apache/incubator-iceberg/files/4603411/run.log)

**Comment by rdblue** [comment]
I should be able to take a look at this tomorrow.

**Comment by rdblue** [comment]
@vanliu-tx, the `UpdateEvent` problem is happening because the snapshot is missing. Just after the commit, the snapshot is loaded to clean up uncommitted files and to send the update event. Both of those tasks are failing to load the committed snapshot. Note the log just above the NPE:

```
[2020-05-08 15:44:17,616] pool-1-thread-49 WARN  Failed to load committed snapshot, skipping manifest clean-up (org.apache.iceberg.SnapshotProducer:291)
```

I think the problem is that the local FS doesn't provide an atomic rename. From [`man rename(2)`](https://linux.die.net/man/2/rename) that is used by `File.renameTo`:

> If newpath already exists it will be atomically replaced

So it looks like a rename is "atomic" in that it is replaced "so that there is no point at which another process attempting to access newpath will find it missing". But that's not the atomic rename like HDFS, where rename fails if the destination path exists. A quick test validates this behavior:

```
fs.rename(p1, dest) -> true
fs.rename(p2, dest) -> true
```

Also, looking at the exceptions thrown in your log, I see only 2 lines in the commit method in stack traces:
```
org.apache.iceberg.hadoop.HadoopTableOperations.commit(HadoopTableOperations.java:123)
org.apache.iceberg.hadoop.HadoopTableOperations.commit(HadoopTableOperations.java:151)
```

The first one is after the check whether base is still current, and the second one is the `exists` check before the rename operation. There are no exceptions thrown from the `rename` operation failing.

So it looks like the problem is that a POSIX FS isn't safe to use with `HadoopTableOperations`. Can you try using HDFS instead?

(FYI @aokolnychyi)

**Comment by vanliu-tx** [comment]
@rdblue thank you for looking into this. I ran the test code with HDFS (50 threads in one process), by checking the final metadata file, the records count and committed snapshots count were as expected.

[v501.metadata.json.txt](https://github.com/apache/incubator-iceberg/files/4667881/v501.metadata.json.txt)

Also tested with two processes (each has 50 threads) to commit data concurrently, the final records count and snapshots count were as expected.

[v1001.metadata.json.txt](https://github.com/apache/incubator-iceberg/files/4668029/v1001.metadata.json.txt)

**Comment by rdblue** [comment]
@vanliu-tx, is it okay to close this, then? I think the problem is that a local POSIX FS doesn't satisfy the requirements for Hadoop tables.

**Comment by aokolnychyi** [comment]
The local file system does not have the needed guarantee for `HadoopTableOperations`. That's the reason why we don't have a concurrency test for Hadoop tables in unit tests.

**Comment by vanliu-tx** [comment]
close this issue
