### ISSUE TITLE
Add an action to rewrite equality deletes as position deletes

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1026]
Equality deletes are more expensive because they are not targeted at a specific data file and cannot necessarily be used to filter rows using a merge strategy (if sort order doesn't match). Iceberg should provide an action that can rewrite equality deletes as position deletes.

**Comment by openinx** [comment]
@chenjunjiedada has proposed a PoC patch for this issue.

**Comment by openinx** [comment]
I also prepared an PR to extend the RewriteFiles API to support rewriting both data files and delete files. #2294

**Comment by manuzhang** [comment]
@rdblue @openinx @chenjunjiedada has this been implemented?

**Comment by jordepic** [comment]
After speaking with @rdblue at the iceberg summit I may try and take this one on but with a spark procedure for going from equality deletes to deletion vectors.  Will use spark SQL for the expensive part (actually doing the row joining) in order to let spark do the majority of the join planning.

After thinking about this problem a bit more, it does begin to beg the question how much streaming writes might actually benefit from secondary indices.  We currently flush many equality deletes at a time (in flink for example, one per incoming data row). Performing an asynchronous deletion conversion in spark while using an index really only benefits if we perform a nested loop join, which could get quite expensive with big equality delete files (as opposed to doing a hash join that doesn't require an index). 

It really all depends on the relative size of the incoming deletes to convert versus the data partition size.  Happy to hear any other thoughts here.  I'll follow up if I push a commit.

**Comment by manuzhang** [comment]
@jordepic Have you followed [Flink: Equality delete to DV conversion](https://lists.apache.org/thread/gldqrycmo24r0vo77wzcj9s9b04rtvy7) discussion on the dev list? If not, I suggest you to read the thread and share your thoughts there.

**Comment by jordepic** [comment]
Just replied!
