### ISSUE TITLE
Add an action to compact delete files

### ISSUE THREAD

**Issue by rdblue** [apache/iceberg#1027]
Tables with slowly changing data may have many small delete files, with only a small portion of the data affected. In that case, it may not be worth rewriting data files to remove rows. Iceberg should provide an action to compact delete files to minimize delete files in a task that need to be read and to keep the number of files in memory during job planning lower.

**Comment by rdblue** [comment]
This may not need to run in a processing engine. Since position delete files are already sorted, they can be merged together without using much memory. Using an engine like Spark could make it faster, but it isn't necessarily required.

**Comment by ajantha-bhat** [comment]
Positional deletes compaction is already handled 
https://iceberg.apache.org/docs/1.3.1/spark-procedures/#rewrite_position_delete_files

Do we need to keep this issue open for equality deletes or raise a separate issue?
Can compacting equality deletes also work? we may need some optimization to merge same filters with greater sequence number instead of reading each equality deletes and storing its content in a big file.
