### ISSUE TITLE
For Hive 2.1.1 version support

### ISSUE THREAD

**Issue by liunaijie** [apache/iceberg#10430]
### Question

Hi team, i am try create an partition table through Hive 2.1.1.
But i find the created table doesn't has `partition` column, the partition column change to the normal column.

Is this version not support well and what's the minimum hive version, 2.3.x?

<img width="1181" alt="image" src="https://github.com/apache/iceberg/assets/28497357/a5d6880b-ee7c-4e62-a1be-9d3563ded38f">

**Comment by liunaijie** [comment]
using iceberg 1.5.2

**Comment by Fokko** [comment]
Hey @liunaijie thanks for reaching out here. Iceberg has a different strategy than Hive when it comes to partitioning. Iceberg expects the partitions to be part of the table itself, rather than being part of the directory path. Details can be found [here](https://iceberg.apache.org/docs/nightly/partitioning/) and also highlights the differences with Hive itself.

**Comment by liunaijie** [comment]
@Fokko  thanks for your quick response, just werid the different behavior when i created table with in hive version 4 and 2.1.1.

In hive 4, i use same ddl to create table, it can show partition filed well.
