### ISSUE TITLE
Can't add column with the same name as a deleted and previously partitioned key column

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg#10487]
### Apache Iceberg version

1.4.3

### Query engine

Spark

### Please describe the bug 🐞

1. column d is also a partition field
![image](https://github.com/apache/iceberg/assets/23215922/7e5a40b5-4ade-4abf-b608-01c65e97683c)
2. delete column d
ALTER TABLE test_p DROP partition field d;
ALTER TABLE test_p DROP COLUMN d;
![image](https://github.com/apache/iceberg/assets/23215922/14addf64-1503-48a2-9a50-40e593bd2799)

3. add column d;
![image](https://github.com/apache/iceberg/assets/23215922/9eb83ccb-d748-4260-8316-bcb0aa9808ee)

why i got this exception, and what should i do ??

**Comment by amogh-jahagirdar** [comment]
Thanks for reporting @madeirak . I think this is similar to https://github.com/apache/iceberg/issues/10234 but this particular issue also brings up a nuance in the "unreferenced partition spec" case.

One problem imo is we should not allow dropping columns which are part of historical partition specs.
Now in your case it's actually still not referenced since no data was actually written (just the metadata updates) so this is another case to think about.

Looking at the PartitionSpec/TableMetadata builder code path, what happens is when the schema is updated, all of the historical partition specs and sort orders need to be updated for the new schema. When you attempt to add the column back it'll have a new id and that id won't align with what was on the historical partition spec; this means updating the historical spec which still referenced the old column will fail.

**Comment by amogh-jahagirdar** [comment]
Well probably we want to keep the historical spec around, but at least in validation we may want to skip that if it’s unreferenced

**Comment by madeirak** [comment]
> Well probably we want to keep the historical spec around, but at least in validation we may want to skip that if it’s unreferenced

thx for reply, btw, the situation I mentioned above is going to solved by skipping validation or something, right?    :)
