### ISSUE TITLE
Support vectorized reads with identity transforms

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1257]
Currently, we don't support vectorized reads if there is an identity transform. Since it is a very common scenario, I think we should try to address that.

**Comment by aokolnychyi** [comment]
@samarthjain @rdblue could you provide some insights on the best way to fix this?

cc @RussellSpitzer

**Comment by rdblue** [comment]
We need to return the `ColumnarBatch` with constant columns. There are two options.

First, we could use [`ConstantColumnVector`](https://github.com/apache/iceberg/blob/master/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ConstantColumnVector.java) that was added for ORC. That is an implementation of Spark's columnar vector interface that always returns a constant.

The second option is to create an Arrow `FieldVector` that contains the data. This would be a little slower because we'd need to create a vector and fill it with copies of the same data value, but then we would have support for other paths that want to consume Arrow.

The simpler option is probably the first one.

**Comment by samarthjain** [comment]
To add to Ryan's point, the place where we currently disable vectorized
reads for identity projections is here
<https://github.com/apache/iceberg/blob/master/spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java#L311>
.
<https://github.com/apache/iceberg/blob/master/spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java#L311>

**Comment by RussellSpitzer** [comment]
I'll take a look at this, should be pretty straight forwards 🤞

**Comment by RussellSpitzer** [comment]
I don't believe there are any current tests checking that this path is exercised, I removed the boolean and no tests failed. I'll be sure to add some back in

**Comment by shardulm94** [comment]
@RussellSpitzer I believe `TestIdentityPartitionData` is supposed to exercise it but what is probably happening here is that the identity partitioned data columns are read from the data file itself rather than the metadata. We may need to add a test where we intentionally modify the metadata so that identity values from metadata do not match the ones written in the data file so we know where the values are picked from. Maybe theres a less intrusive way to test this?

**Comment by RussellSpitzer** [comment]
Could you give me an example? I've been staring at this a while trying to figure out what's going wrong. I would have hoped disabling the boolean would have broken that test suite (or others) but it doesn't. I've just been running through it with a debugger and it does correctly build a reader and return rows but you are probably right that it's reading from the data file.

**Comment by rdblue** [comment]
I think @shardulm94 is right. Iceberg will write all data columns into every file, unlike Hive that will leave partition columns out of the data. The reason why we write the columns is that we may want to move the files to a different partition spec later (e.g., drop a categorical column, move the files, then compact).

So this is probably working because the data files in the tests actually do contain the data columns. What you can do to make the tests fail is generate the data files without the identity-partitioned columns, add them to a table, then validate that you still get those columns when you read. That's basically what happens when we import Hive data into Iceberg tables because the columns aren't present in the data files and we use the values from the file's partition tuple.

**Comment by RussellSpitzer** [comment]
This seems like the right analysis to me, I tried just having the current
test code make the tables in Hive and then import them for reading and I
ran into a bunch of other errors (with and without vectorizing) so I'm sure
I didn't do that right ...

**Comment by RussellSpitzer** [comment]
I can get the test to fail if I import from a Hive Table with parquet files and then attempt to use that as the basis for the IdenetityPartition test. So thanks for steering me in the right direction @shardulm94  + @rdblue, I'll try to figure out where to add tests because I can't quite do that same strategy of creating a Spark table and then importing it for Avro (and orc just does something strange)

**Comment by rdblue** [comment]
You should be able to just write a data file directly with a schema that doesn't include those columns, then append it to the table.

Here's an example that does it for Parquet: https://github.com/apache/iceberg/blob/master/spark/src/test/java/org/apache/iceberg/spark/source/TestParquetScan.java

**Comment by RussellSpitzer** [comment]
How do you append the file to the correct partition if it doesn't have those columns? Sorry I have a lot of beginner questions.

**Comment by aokolnychyi** [comment]
This has been resolved.
