### ISSUE TITLE
Spark3: Iceberg catalog lits non-Iceberg tables

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1319]
I find it a bit confusing that Iceberg tables show up in non-Iceberg catalogs and vice versa. For example, if a user does SHOW TABLES in the default session catalog, we will see both Iceberg and non-Iceberg tables. If we decide to query one of the Iceberg tables, we will end up with a runtime exception. The same is true for non-Iceberg tables that show up in the Iceberg catalogs.

I know users can configure `spark_catalog` to load both but is there anything we can do better to support use cases when users configure a separate Iceberg catalog? Can we filter tables based on `provider`?

**Comment by jerryshao** [comment]
From my understanding, the current implementation of `HiveCatalog` will list all tables under specific db, that's why we will see non-iceberg table in iceberg catalog. I think it is doable to filter out non-iceberg table, but it requires to get the properties of each table, which may bring in extra cost for just table listing.

**Comment by aokolnychyi** [comment]
@rdblue @zhangjun0x01 @rdsr is this same as #1830? Can we resolve it? PR #1835 added extra calls like @jerryshao mentioned. I am ok with that.

**Comment by rdblue** [comment]
I think it is the same. I'll close this.

**Comment by zhangjun0x01** [comment]
I think it is same,I closed #1830

**Comment by aokolnychyi** [comment]
Thanks for working on this, @zhangjun0x01!
