### ISSUE TITLE
FlinkCatalog will need to load hive's configuration files.

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#1437]
Currently, we will load the hadoop configuration by using flink's [HadoopUtils.getHadoopConfiguration(..)](https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java#L122),  this method will only load `core-site.xml` and `hdfs-site.xml`,   it won't load the `hive-site.xml` when using hive catalog. 

We'd better to support load hive configurations.

**Comment by JingsongLi** [comment]
Yes, we should consider `hive-site.xml` too. `HadoopUtils` only consider `core-site.xml` and `hdfs-site.xml` for file system accessing.
Spark also respect `hive-site.xml`: https://issues.apache.org/jira/browse/SPARK-31170
Maybe we can expose a `hive-conf-dir` like Flink Hive integration doing: https://ci.apache.org/projects/flink/flink-docs-master/dev/table/hive/hive_catalog.html#step-2-configure-flink-cluster-and-sql-cli

**Comment by zhangjun0x01** [comment]
I have meet the same issue, for the modification of this issue, I have a few thoughts:
 1. Specify the hive conf dir like flink, and then construct HiveConf through the hive-site.xml in this dir, but in this case, if flink is started in application mode, the cluster will can not load the  hive configuration on the jobmanager of flink, There is maybe no hive-site.xml file on yarn cluster
 2. We construct a HiveConf by the user's parameters. What I tested is that at least two parameters are required to construct HiveConf, hive metastore uri and warehouse,
 However, if the user's hive metastore configuration is more complicated, such as authorization verification, etc., then the construction of HiveConf will become very complicated. We need to provide parameters for the user to accept information such as user permissions.

**Comment by openinx** [comment]
> but in this case, if flink is started in application mode, the cluster will can not load the hive configuration on the jobmanager of flink, There is maybe no hive-site.xml file on yarn cluster

This should not be a problem,  because we would load the hive configuration files at the client side and then construct the `IcebergStreamWriter` and `IcebergFilesCommitter`, those classes will serialize the configurations and send them to job manager,  finally the job manager would deserialize to get the `Configuration`. 

Making the property-value pairs as arguments  sounds reasonable for testing or demo purpose, but it not suitable for production jobs I think.

**Comment by zhangjun0x01** [comment]
hi,@openinx 

For example, I have a flink jar program, which consumes data from Kafka and writes it to iecberg table. If the jar package contains the local configuration path of hive, I upload the jar to the hdfs directory, and my startup command is as follows:

`/home/work/software/flink/bin/flink run-application -p 5 -d -t yarn-application  \
-yD yarn.provided.lib.dirs="hdfs://hadoopcluster/data/flink/libs/" \
hdfs://hadoopcluster/data/flink/user-lib/flink-kafka-iceberg.jar  `

In this mode, the user jar is parsed on the jobmanager node of the flink cluster. I think it may not be possible to load the local configuration file.

**Comment by rdblue** [comment]
I think it's a good idea to load `hive-site.xml` and respect its defaults. But for cases like a missing warehouse directory for a catalog, I think we should prefer configuring the warehouse on the catalog itself. It doesn't make sense for multiple catalogs to use the same `hive-site.xml` setting for warehouse directory.

**Comment by zhangjun0x01** [comment]
I tested it and found that there is indeed a problem with configuring the local directory to load hive-site.xml in flink application mode.
So my idea is to configure a hive conf dir to load hive-site.xml. This directory can be a local path or an hdfs path to be compatible with flink application mode. If it is a local directory, load it directly, if it is an hdfs directory , download it to the local tmp directory first, and then load it.

**Comment by zhangjun0x01** [comment]
> I think it's a good idea to load `hive-site.xml` and respect its defaults. But for cases like a missing warehouse directory for a catalog, I think we should prefer configuring the warehouse on the catalog itself. It doesn't make sense for multiple catalogs to use the same `hive-site.xml` setting for warehouse directory.


My idea is that the configuration of hive is obtained by loading hive-site.xml, but we also support users to configure warehouse. 

- If the user configures warehouse, the value in hive-site.xml will be overwritten, just like when we create hive table the location can be specified. 
- the user does not configure a warehouse, the default value in hive-site.xml is used. 
- the user does not specify a warehouse and hive-site.xml is not configured in hive-site.xml, an exception will be thrown.

What do you think for this? @rdblue

**Comment by openinx** [comment]
> In this mode, the user jar is parsed on the jobmanager node of the flink cluster. I think it may not be possible to load the local configuration file.

In this case,  I think we'd better to include hadoop & hive configurations in the `flink-kafka-iceberg.jar`, so that even if loading jar at job manager side,  we could parse the correct expected configurations. right ?

**Comment by zhangjun0x01** [comment]
hi ,@openinx 

No matter which mode is used to submit flink jobs (sql client,standalone,yarn session, flink per job, application mode), flink will use FlinkCatalogFactory#createCatalog to create catalogs, so the difficulty lies in making FlinkCatalogFactory compatible with various submission modes. If hive file is included in the user jar  , Then FlinkCatalogFactory needs to parse the user jar  to obtain the hive configuration, but for other submission modes, it only needs to configure a hive local path. But I think it may be difficult for FlinkCatalogFactor to know which job mode the current user submits  in order to make different loading methods.

In addition, for other submission modes, we provide a hive local configuration path. If the user executes the DDL that creates the catalog in the code, such as the following code example:

`	tenv.executeSql("CREATE CATALOG hive_catalog WITH (\n" +
				"  'type'='iceberg',\n" +
				"  'catalog-type'='hive',\n" +
				"  'uri'='thrift://localhost:9083'" +
				"  'warehouse'='hdfs://localhost/user/hive/warehouse'" +
				")");`

 and the code is typed into a jar  and executed in application mode, then In this case, we are based on the hive path configured by the user ddl or the hive-site.xml contained in the jar ? If the two configurations are different, the user will be confused. The same ddl It can be executed in sql client, why can't it be executed in the program.

So my idea is to provide a hive conf path, which can be a local path or a hdfs path. If the user configures the hdfs path, we first download it to the local, and then load it. If the user submits the flink jar  in application mode, but the configured local path cannot find the path anymore, we will give the user some prompts and tell him that the application mode needs to configure the hdfs path.

I think this is compatible with various user program submission modes. What do you think about this.

**Comment by JingsongLi** [comment]
> I think it's a good idea to load `hive-site.xml` and respect its defaults. But for cases like a missing warehouse directory for a catalog, I think we should prefer configuring the warehouse on the catalog itself. It doesn't make sense for multiple catalogs to use the same `hive-site.xml` setting for warehouse directory.

+1 to try.
Maybe that's enough, because in iceberg, the dependency on hive is very light, just configure warehouse may be works.

**Comment by openinx** [comment]
I think this [comment] is the right direction to resolve this issue, will create a pull request for it.
