### ISSUE TITLE
Reconsider handling of spaces in PartitionSpec$partitionToPath

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1479]
If we migrate existing tables to Iceberg and then continue writing to them, file locations are not consistent because of how we handle spaces in `PartitionSpec$partitionToPath`.

For example, we have the following locations:

```
/partitioned_table/data/dAtA sPaced=some+key+value/filename.parquet // Iceberg
/partitioned_table/data/dAtA sPaced=some key value/filename.parquet // Spark
```

**Comment by RussellSpitzer** [comment]
Should we just be not escaping?
```
      sb.append(field.name()).append("=").append(escape(valueString));
```

**Comment by manishmalhotrawork** [comment]
@RussellSpitzer @aokolnychyi 

yeah, looks like this change can fix the issue.
as `URLEncoder` converts space to `+`

Or it has to do decoding as encoded?

tested column_name field with spaces it works ( in case we create table using Iceberg internal API's) with Spark, it has to use back ticks `

I tested with no `escape` and it seems to be good for this test-case.

**Comment by bharos** [comment]
Revisiting this issue, I notice even in V1.8 with Spark3.5 iceberg partition values are having "+" in the path instead of space.
It can pose some problems, For example, let's say I archive iceberg data for partition `date_key=2023-03-01,name=Entry 1`
in path ```gs://warehouse/retention_service_test_db/iceberg_table/data/date_key=2023-03-01/name=Entry+1/```
Later I want to restore or add back this partition to iceberg using `add_files` API

To restore, I copy this data into `gs://warehouse/retention_service_test_db/iceberg_table/data/add_file/date_key=2023-03-01/name=Entry+1/`


### Problem 1:

and call
```
CALL spark_catalog.system.add_files(
  table => 'retention_service_test_db.iceberg_table',
  source_table => '`parquet`.`gs://warehouse/retention_service_test_db/iceberg_table/data/add_file/`',
  partition_filter => map('date_key','2023-03-01','name', 'Entry 1')
);
```
It doesn't work saying no matching partitions, because of the "+" in path

### Problem 2:
If I just specify ` partition_filter => map('date_key','2023-03-01')` (or even skip the partition_filter), it will succeed, but the partition will have the '+' in the string value ie. ```{"date_key":"2023-03-01","name":"Entry+1"}``` which should actually be `Entry 1`
