### ISSUE TITLE
Custom partition functions

### ISSUE THREAD

**Issue by samidalouche** [apache/iceberg#1482]
The `PartitionSpec` class is protected in a way that prevents the user from creating custom partitioning functions besides the built-in `bucket`, `identity`, `year`, `month`, `day` and `truncate` ones. 

1. Am I right to assume that the code is written this way because it takes much more than the partitioning function to generate the execution plan/optimize the queries, etc?
2. Is there any plan to provide a way for the user to implement his/her own  partitioning functions? 
3. Is it even realistic to assume the user could implement his/her own partitioning functions?

Thanks

**Comment by rdblue** [comment]
@samidalouche, sorry for the late reply. I didn't see this until today.

Right now, we have a fixed set of transforms because we want to have consistent support across engines. To do that, we want a small set of transforms that are well-defined so that there isn't a huge cost to implementing support. Otherwise, we'd end up with inconsistent features across processing engines, which we really want to avoid.

It is possible to add new transforms and possibly even to provide a way to customize transforms, but we would need a way to plug in code that is used by Iceberg. The hardest thing to implement is projection, which takes a predicate for rows in a table and converts it to a predicate that matches partition values. That's difficult to write and can cause problems if you get it wrong, but I think we can generalize it into two cases: monotonic transforms (like year, month, day, hour, truncate) and other transforms (like bucket). Then you'd only have to supply the `apply` implementation and a few booleans and Iceberg could handle the rest.

I think it is reasonable for users to need additional partition functions, but I hope that we can add functions to Iceberg when they are needed so that everyone benefits.

**Comment by wboyer-teg** [comment]
Just to add a use case here, we'd like to be able to partition on IDs that use a urn: scheme like the following:

urn:eiu:monthly:au:realgdp

...and treat everything up to, say, the 4th colon as the partition value.  The length of that value could be different for different URNs, though.
