### ISSUE TITLE
Switch to using table.name() instead of toString() where it makes sense

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1544]
We should consider updating places that use `table.toString()` and migrate them to `table.name()` where it makes sense.

**Comment by kbendick** [comment]
I am opening a PR for a few of these that I found. Most likely there are more of these, but figured I'd grab some where possible.

**Comment by kbendick** [comment]
Ok. I grepped through the code base for `table.toString`, `Table.toString`, `table().to`, `Table().toString`, etc. and replaced the ones that I could find in the above PR. Not sure if it's exhaustive by any means but it's a start.

**Comment by kbendick** [comment]
ok I also tried `tbl.toString` and `tbl().toString`.

finally I said screw it and also tried `t.toString` and `t().toString`. It was a decent amount to read, but I cant think of any other names that people might have named a Table variable. Can anybody think of any other names of variables people might have assigned tables to? I'm tempted just to look at the hundreds of usages of Table and then that way be able to say that I fully believe all instances have been found. How repeatable is that? Not very, but I can't figure out how to exhaustively check otherwise.

**Comment by RussellSpitzer** [comment]
You should in intellij be able to search for method usages I think

**Comment by aokolnychyi** [comment]
I am going to resolve this as it done. Thanks, @kbendick!
