### ISSUE TITLE
remove guava minimize option in iceberg-bundled-guava

### ISSUE THREAD

**Issue by simonsssu** [apache/iceberg#1567]
Currently we have minimize() option in ceberg-bundled-guava, which only include minimal classes in Guava, when we want to use TreeBasedTable, HashBasedTable or some other classes in guava, we should include other guava dependency, which may easily cause class conflict.

**Comment by RussellSpitzer** [comment]
I'm confused why we want to do this? Isn't the point that an end user should include their own un-shaded version of guava if they want to access other classes?

**Comment by rdblue** [comment]
@simonsssu, if we want additional Guava classes, then we add them to [`GuavaClasses`](https://github.com/apache/iceberg/blob/425b10cea34eef11cca9cf0d237e02274f6dc958/bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java) so that they aren't removed when the Jar is minimized.

Also, we are trying to avoid depending more on Guava because it causes so many runtime issues.

I think that the current build is a reasonable way to go, but maybe I've misunderstood your concern?

**Comment by simonsssu** [comment]
@rdblue Hi Ryan, thanks for pointing out to use GuavaClasses, I've misunderstood what bundled-guava does. I will close the related pr.
