### ISSUE TITLE
Add a serializer for FileScanTask 

### ISSUE THREAD

**Issue by stevenzwu** [apache/iceberg#1698]
For batch/bounded mode, Java Serializable works well as there is no concern of schema evolution. If we are going to support the streaming read with long-running jobs, we need to consider schema evolution for checkpoint state. Otherwise, change in the code might break the Java serialization and ability to restore from checkpoint.

Here are some high-level thoughts.

* Move most of the schema defined in `DataFile` to parent interface `ContentFile`. Extend the schema with the additional fields in `DataFile` and `DeleteFile`.
* Add a schema to `FileScanTask` where `ResidualEvaluator` and `PartitionSpec` fields will be defined as string type.
* `CombinedScanTask` schema is straightforward. it should be just a collection of `FileScanTask`
* Add `ScanTasks` util class in iceberg-core that handles the serialization and deserialization of `FileScanTask` and `CombinedScanTask`

One challenge is how to plugin custom field serializers for `ResidualEvaluator` and `PartitionSpec`.

Overall, this seems like a large change. not sure if there is a simpler way.

**Comment by stevenzwu** [comment]
@openinx @JingsongLi @rdblue any comment?

**Comment by openinx** [comment]
Thanks @stevenzwu for bringing this up.   It's indeed an problem for flink streaming reader because it depends on the java serialization in [StreamingReaderOperator](https://github.com/apache/iceberg/pull/1793/files#diff-22513db68a66d835391d1dad5b0b95ed776dbcc3df7c8df7df5450930f367893R67) now,  it's easy to crash when we upgrade iceberg lib version (which changes the CombinedScanTask classes) and restart the flink job. 

I'd prefer to define the avro schema in `BaseCombinedScanTask` which is similar to `BaseDataFile`, then we could maintain the binary bytes which is serialized by avro approach to flink state backend.  Let me evaluate the work.

**Comment by coolderli** [comment]
@stevenzwu @openinx Is there a patch to fix this problem ？

**Comment by stevenzwu** [comment]
@rdblue @pvary I updated the description with some high-level thoughts on how this can potentially achieved. Can you please share your thoughts?

**Comment by rdblue** [comment]
@stevenzwu, I think that we should introduce a JSON format and parser for these tasks. The information in a `FileScanTask` has been stable for a really long time so it wouldn't be a problem to maintain it. And we've had other projects ask for this before as well, since it is more common to use JSON to serialize in some settings. Trino uses JSON for RPC and we've also recently discussed adding job planning to the REST catalog interface.

**Comment by stevenzwu** [comment]
@rdblue JSON would work, although it is less efficient in terms of space and serialization. But I see the benefit that it can be useful in some other scenarios.

**Comment by stevenzwu** [comment]
@aokolnychyi would also like to get your input. With the recent changelog scan, we may also need to document the JSON format for those changelog scan tasks in the future. not needed right now especially as we are still iterating on those interfaces.

**Comment by aokolnychyi** [comment]
I am also +1 on trying to come up with a reasonable JSON representation. Handling job planning via the REST catalog is something I'd be interested to see.

**Comment by stevenzwu** [comment]
Anton, thanks a lot for the input. Looks like we have a direction moving forward.

**Comment by stevenzwu** [comment]
this is completed via the 3 PRs linked
