### ISSUE TITLE
Setting global conf in HiveIcebergStorageHandler breaks queries with multiple tables

### ISSUE THREAD

**Issue by marton-bod** [apache/iceberg#1708]
Setting the table schema in the global job conf in`HiveIcebergStorageHandler#configureJobConf()` - see #1557 - introduced a problem: whichever table calls this function last, ends up having its schema stored in the global conf (overwriting all the previous ones). 

This leads to issues when using multiple tables (joins) in Tez: in `HiveIcebergSerde#initialize()`, the schema is taken from the conf when present, but that leads to failures for multiple tables since all tables are now using the schema of the table that was the "winner" (that one that set its schema last in the above `configureJobConf()` step).

Furthermore, even for Hive1.1, this approach should only partially fix the issues outlined in #1557, since when working with multiple tables, the same problem of overwriting the schema in the global conf can occur when retrieving the schema [here](https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java#L184) . (the only problem scenario laid out in #1557 was a one-table order by query).

As a result, I'm proposing to revert this change. The proper fix should look into why the table schema property in Hive1.1 is missing from the config object [here](https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java#L184) - possibly there is a missing config merger step in Hive1 whereby the props from the jobInputProperties are not overlaid on top of the global job conf.

**Comment by HotSushi** [comment]
+1 

The reason why the error in https://github.com/apache/iceberg/pull/1557 doesn't show up in the integration test [here](https://github.com/ExpediaGroup/iceberg/blob/master/mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java#L145),  is because Hive2 overwrites properties set in `configureInputJobProperties()` on top of `configureJobConf()`.

We found that, Hive2 did not make significant change over Hive1.1 in relevant code, except for a piece where scheme of table location is ignored (see [here](https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java#L400)). Therefore the error in https://github.com/apache/iceberg/pull/1557 can show up if file split's location is incorrectly set up. We made an internal change to get around this issue in https://github.com/linkedin/iceberg/pull/43.

It should be safe to go ahead with the revert. Thanks @marton-bod

**Comment by rdblue** [comment]
@HotSushi, could you open a PR with the fix?
