### ISSUE TITLE
NOT IN with nulls should be treated as false

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#1710]
Right now, we remove nulls from IN predicates while translating Spark filters to Iceberg. Due to that, we don't handle NOT IN with nulls in an optimal way. NOT IN with nulls should match nothing.

**Comment by rdblue** [comment]
I don't think this is going to be easy. You're right about the behavior, but NOT IN is passed as `not(in(...))` and it works because `not(null)` is `null`. We could inspect the child expression in `not` and look for `in` with a null, but replacing with `alwaysFalse` at that point isn't correct because negating further up the expression tree should still result in `null`, but negating `alwaysFalse` is `alwaysTrue`.

In fact, the fix in #1709 also has that problem. `not(x > null)` should be `null`, but would evaluate to `true`. I'm going to revert #1709 until we figure this out.
