### ISSUE TITLE
 iceberg-bundled-guava module shadowJar relocate use questions ask

### ISSUE THREAD

**Issue by zanmeipaul** [apache/iceberg#1750]
The iceberg-bundled-guava module uses shadowJar relocate to change the package name. What plug-ins need to be added for Eclipse and IDEA to prevent the development tool from reporting errors?

![image](https://user-images.githubusercontent.com/20592867/98805886-4137e600-2453-11eb-8fc4-864a9c18a61d.png)

**Comment by RussellSpitzer** [comment]
I find that Intellij correctly locates these if you just run the full build
once, once the shadow jar has been made if you refresh the project it will
find the shaded classes.

**Comment by jackye1995** [comment]
I usually run `./gradlew :iceberg-bundled-guava:build`, and it will automatically refresh the dependency.
If not, there is a button to force refresh:

![Snip20201112_3](https://user-images.githubusercontent.com/29823233/98913354-1dd56100-247c-11eb-988e-756cba9e2d54.png)

**Comment by zanmeipaul** [comment]
hi @RussellSpitzer  @jackye1995 , Thank you for your answer. I guess it's my question about using eclipse

**Comment by ahmedriza** [comment]
The suggested fixes do not seem to work with recent versions of Intellij.  Tried the approaches suggested, but Intellij just refuses to locate the dependency

<img width="1628" alt="image" src="https://github.com/apache/iceberg/assets/2463311/ca20f6ab-5230-4025-b28a-783b262ca053">

Really odd, since the Intellij Gradle settings do show up the `iceberg-bundled-guava` as a dependency, but I guess it is failing to actually locate where the built jar is or maybe something else entirely is now broken in Intellij and its Gradle integration.

**Comment by jzhuge** [comment]
Noticed the same issue

**Comment by jzhuge** [comment]
Anybody got it working in latest IntelliJ?

**Comment by cxzl25** [comment]
1. `./gradlew :iceberg-bundled-guava:build`
2. `bundled-guava/build/libs`  Add as Library
<img width="565" alt="image" src="https://github.com/apache/iceberg/assets/3898450/a740cae2-7f3f-45e6-a001-8ca66da64727">

3.  Project Library
<img width="606" alt="image" src="https://github.com/apache/iceberg/assets/3898450/e12ed2de-1e68-4586-b996-7968a7b26010">

4.  Project Structure -> Libraries -> libs

<img width="403" alt="image" src="https://github.com/apache/iceberg/assets/3898450/ae0e0a36-0974-4a03-a085-bc23d7339a42">


<img width="1001" alt="image" src="https://github.com/apache/iceberg/assets/3898450/bffd9fd0-9f71-4aee-9eca-87ca131b4a2f">
