### ISSUE TITLE
Manifest List is a LinkedList Indexed during Write

### ISSUE THREAD

**Issue by johnclara** [apache/iceberg#1812]
ManifestLists are stored as linked lists:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/ManifestLists.java#L46

But with Manifest V1/V2 split, they're getting wrapped and indexed by individual tasks:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotProducer.java#L180

Any reason why the manifest list should stay as a linked list?

@rdblue

**Comment by rdblue** [comment]
Those two code sections aren't very related. The write is using an array because the manifests are processed in parallel. That happens to ensure that each manifest has metadata. If the `ManifestFile` that will be written doesn't already have metadata about its contents, then it will be scanned to generate that metadata.

On the read side, all of the `ManifestFile` instances in the manifest list are read into memory for later use in scan planning and other operations. I don't see a strong need for those to be in a linked list, but I don't think it would be a problem either.

**Comment by johnclara** [comment]
Not worth changing

**Comment by johnclara** [comment]
`manifests.get(index)` this section of line 180 in the snapshot producer was the indexing part in the linked list, not the filling of the array.

**Comment by rdblue** [comment]
Oh, I see. We could change that to an `ArrayList`. Maybe that would be faster?
