### ISSUE TITLE
Add support for building runtime jars containing the sources

### ISSUE THREAD

**Issue by jshmchenxi** [apache/iceberg#1865]
It will be easier to debug locally if the runtime jars (eg. iceberg-flink-runtime/iceberg-spark-runtime) contain sources.
Just like the [flink-shaded](https://github.com/apache/flink-shaded) project, it supports command `mvn package -Dshade-sources` to build source jar for shaded resources.
I'm new to gradle and currently have no idea how to achieve this.
It will be appreciated if anyone could help.

**Comment by openinx** [comment]
The published `iceberg-flink-runtime` should not contains sources code, because it's for production purpose.  If you really want to debug the runtime code, you might need to rebuild the project to get a new runtime jar with sources attached.  For most cases, I don't use the IDE debug directly,  I will read the stactrace and read the code base to see what's wong, if it indeed a potential bug, I will write an unit test to reproduce.

**Comment by pan3793** [comment]
Also +1 for attaching `shade-sources`.
We use `iceberg-*-runtime` directly in `pom.xml` to avoid conflicting with exist cdh6 dependencies. For example, cdh6 use `hive-2.1.1` which bundled `hive-orc` instead of `apache-orc`, but with same package path, the new `apache-orc` will break the build.

**Comment by rehevkor5** [comment]
> The published iceberg-flink-runtime should not contains sources code, because it's for production purpose.

It's not necessary for the compiled JARs to contain the source code. Maven's standard approach to source JARs is that you publish an artifact with a classifier of `sources`. Refer to https://maven.apache.org/pom.html#dependencies

Gradle is capable of doing the same via `withSourcesJar()`, see https://docs.gradle.org/current/userguide/publishing_maven.html
