### ISSUE TITLE
Support Page Skipping in Iceberg Parquet Reader

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#193]
I think we should evaluate the feasibility of page skipping in Iceberg Parquet reader.

See [here](https://github.com/apache/parquet-format/blob/master/PageIndex.md) for more details.

**Comment by manishmalhotrawork** [comment]
@aokolnychyi this is interesting. is this still valid ?

**Comment by chenjunjiedada** [comment]
I 'm also interested in this. Currently, the page indexes feature has not released yet. See [PARQUET-1434](https://issues.apache.org/jira/browse/PARQUET-1434).

**Comment by chenjunjiedada** [comment]
@aokolnychyi @rdblue IIUC, we don't need to do extra work to support this as long as the predicate pushdown works well. The read property `parquet.filter.columnindex.enabled` defaults set to true and column indexes are built by default as well.  Please correct me if I 'm wrong.

**Comment by rdblue** [comment]
We would need to implement something to take advantage of the column indexes in some engines. Any client using an Iceberg table uses its own readers for Parquet data. Spark readers are in the iceberg-spark module and use a different read path to construct records than the one built into Parquet, so we would need to add support for page indexes there.

In the long term, we want this optimization to be part of the vectorized reads because we think that reading first into Arrow (vectorized) and then converting to an in-memory row format is going to be faster than deserializing directly to the row format. That means we should invest in adding page skipping to the Parquet to Arrow conversion.

**Comment by chenjunjiedada** [comment]
The column index feature provides a help function`ParquetFileReader.readNextFilteredRowGroup` which should contain column index filtering logic. Does that mean we can just replace the `readNextRowGroup` In  ParquetReader to utilize the column index filtering?

**Comment by rdblue** [comment]
@chenjunjiedada, probably not. That may read just the required pages, but Iceberg doesn't use Parquet filtering, so it wouldn't be correct without converting and pushing those filters. Record construction also needs to change to reconstruct rows correctly because the filtered pages start at different row offsets.

**Comment by shangxinli** [comment]
I don't see any progress on this feature for a year! Anybody is still actively working on it? If not, I am interested in working on it. 

I look at the Icerberg code briefly. Yes, although the flag parquet.filter.columnindex.enabled is enabled by default, but Iceberg is not using that reading path. It seems we can borrow something in org.apache.parquet.internal.filter2.columnindex.ColumnIndexFilter and implement the filtering in Vectorized Parquet reader.

**Comment by aokolnychyi** [comment]
I think this work was blocked by the vectorization work. Since we merged it into master, I think we should be good to go.

**Comment by aokolnychyi** [comment]
I don't know anyone working on this.

**Comment by shangxinli** [comment]
Thanks Anton! I will have a look when I get time.

**Comment by rdblue** [comment]
@shangxinli, it would be great to have your help implementing this!

You're right that Iceberg doesn't use the read path from Parquet. Iceberg has its own set of readers to reconstruct Parquet rows, and it also has its own set of expressions that are used directly in row group and record filters.

We're here to help out with questions if you have them.

**Comment by rdblue** [comment]
@shangxinli, `idToAlias` is correct. That accesses the full Parquet name for the field in the a schema converted from a Parquet file. There is no guarantee that Iceberg field names correspond to the names used by Parquet when the file was written, which is why we maintain the alias map when converting from Parquet.

**Comment by shangxinli** [comment]
@rdblue, idToAlias could be null. In that case, how do we find the field name which is required by the following Parquet API(FilterApi)? 

BTW, how do you resolve the imports of 'relocated' in Intellij? I am able to Gradle build in the terminal but Intellij keeps complaining those relocated imports like below. This blocks me to run unit test in Intellij. 

import org.apache.iceberg.relocated.com.google.common.collect.ImmutableList;
import org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap;

**Comment by rdblue** [comment]
`idToAlias` is not null when the schema was converted from a Parquet schema. So you just have to ensure that the schema you're using was converted from the schema of the file you're working with.

Try building the gradle bundle through IntelliJ's gradle plugin. That usually fixes it for me.

**Comment by shangxinli** [comment]
It shows null to me when I do a simple writing/reading as below. 
Dataset<Row> df = ....
df.write().format("iceberg").mode("overwrite").save(path_name);
spark.read().format("iceberg").load(path_name);

It is null because the 2nd constructor public Schema(List<NestedField> columns) () is called from https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SchemaParser.java#L240

**Comment by rdblue** [comment]
@shangxinli, I wouldn't expect an alias map when getting a schema from that path. If you're parsing the schema from Iceberg metadata, then there are no aliases. We only set them when the schema is created by converting a Parquet MessageType to Iceberg Schema.

When converting to the Parquet FilterApi, the aliases must come from a Schema instance that was created from the MessageType of the file you're pushing filters to. Otherwise, the aliases might not match the file because the file may have been written with different column names.

**Comment by lgo** [comment]
Hey folks, I saw this was still open and @shangxinli's PR unmerged. I was recently exploring options to optimize point lookup reader performance for a sorted column on parquet Iceberg tables.

Is this a task that should still be done to add support for it?

**Comment by shangxinli** [comment]
This PR is blocked because we need [ID-based resolution](https://issues.apache.org/jira/browse/PARQUET-2006) support in Parquet.

**Comment by 7mming7** [comment]
@shangxinli ,Doesn't it seem like there's no progress here?

**Comment by zhongyujiang** [comment]
Hi guys, I have implemented a ID-based `ParquetColumnIndexFilter` on the Iceberg side, equivalent to the ColumnIndexFilter in Parquet-MR. I have also updated the `ParquetReader` to support data page skipping: #6967 (though the vectorized read path has not been updated yet)
Are you interested in reviewing it?  Will appreciate your comments.
