### ISSUE TITLE
remove a list .metadata.json in HadoopCatalog

### ISSUE THREAD

**Issue by txdong-sz** [apache/iceberg#1934]
![image](https://user-images.githubusercontent.com/5066512/102161744-d4d15c00-3ec2-11eb-9be1-bf04edce51e7.png)

in hadoop cos scene  this list status may cost a lot of time  if there are many files in cos metadata.  
and we spend about 10s  to list tables .

if we remove (fs.listStatus(metadataPath, TABLE_FILTER).length >= 1) or  find a better way to list file like 
![image](https://user-images.githubusercontent.com/5066512/102161998-5aeda280-3ec3-11eb-8506-8c76d15c8cdb.png)

![image](https://user-images.githubusercontent.com/5066512/102161957-43161e80-3ec3-11eb-8d7e-59f22cff56c9.png)

**Comment by jacques-n** [comment]
I'm guessing that FileSystem.listStatusIterator() could be faster since you only need to check if it is greater than 1 and it doesn't require a full traversal. @txdong-sz do you want to propose a patch? You'd need to implement the filter outside the call since I believe that call doesn't support filters.

**Comment by txdong-sz** [comment]
@jacques-n 
i also think that it is not need to check metadata.json   
if namespace with metadata folder in   so we can just consider that is a table
or eles 
check if that metadata folder have a version-hint.text   file in it
