### ISSUE TITLE
Avro: Schema conversions should preserve docs

### ISSUE THREAD

**Issue by shardulm94** [apache/iceberg#1954]
In Avro schema conversions referenced below, we should copy field level documentation between Iceberg and Avro schemas. https://github.com/apache/iceberg/blob/9f727cb366103ea8fed10c1d578a88aa7fbd704f/core/src/main/java/org/apache/iceberg/avro/SchemaToType.java#L31 and https://github.com/apache/iceberg/blob/9f727cb366103ea8fed10c1d578a88aa7fbd704f/core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java#L34

**Comment by kbendick** [comment]
@shardulm94 @RussellSpitzer I can take this one.

**Comment by kbendick** [comment]
It seems my patch has inadvertently broken a different test (more info in the PR summary).

AFAIK I am unable to revert my PR to a draft as I don't have commit rights in this repo.

I've updated the PR to have [WIP] instead while I investigate.

**Comment by kbendick** [comment]
I figured out why the test needed to be updated (slight increase in manifest file size due to the field docs appearing in their header). Given the increase is many orders of magnitude less than the default target manifest file size (698 bytes increase per GenericManifestFile according to my debugger from this patch), I personally don't think it's an issue.

This PR is no longer considered WIP.

**Comment by shardulm94** [comment]
@kbendick Saw that your PR was merged. Thanks for working on this!
