### ISSUE TITLE
What's the purpose of Position2Accessor and Position3Accesor? 

### ISSUE THREAD

**Issue by simonsssu** [apache/iceberg#2049]
Currently I'm doing some type convert by using Iceberg Accessor. I found some tricky codes in Accessor like this:
![image](https://user-images.githubusercontent.com/12323514/103965699-48e8e200-5199-11eb-8e22-b1c9e8e5f3cd.png)
In my understanding, we only need a WrappedPositionAccessor and a PositionAccessor, It makes me quite confused why we need a position2accessor and position3accessor here . Also if we have more than 3 layers nested types, why we can use WrappedPositionAccessor rather than position4accessor ? In my understanding, the logic to get value in Position2Accessor and Position3Accessor is the same as what it was in WrappedPositionAccessor.

I'm trying to remove position2accessor and position3accessor, just return WrappedPositionAccessor for new accessor, and All UTs have passed. I'm not understanding the purpose here, if it's a tricky part and we don't have any optimization here, I prefer to remove them.

**Comment by openinx** [comment]
@simonsssu  It's an optimization for accessing nested field.   For example,  we have the schema: 

```
root
 |-- a: struct (nullable = false)
 |    |-- b: struct (nullable = false)
 |        | -- c: string (containsNull = false)
```

We could just use the `Position3Accessor` to access the nested field `c` (Because it just access the nested field straightforward :  `row.get(p0, StructLike.class).get(p1, StructLike.class).get(p2, javaClass);`  ). 

Of course,  it won't break the correctness if we remove that optimization, then we will use the `WrappedPositionAccessor` to access field `c` recursively,  that's a more complex stack trace which may consume more resources. 

But I think it's good to keep the optimization because the nested fields with depth=1 or 2 or 3 are the fields that will be accessed with the highest frequency.

**Comment by simonsssu** [comment]
@openinx I think what we need is to add some comments here.

**Comment by openinx** [comment]
@simonsssu  It's indeed a bit hard to understand,  would you like to add comments for that ?

**Comment by simonsssu** [comment]
OK, I will add comments and make a pr
