### ISSUE TITLE
Spark can't read Iceberg table created from Presto

### ISSUE THREAD

**Issue by sshkvar** [apache/iceberg#2122]
Spark can't read table which was created in Presto 

```java
create table iceberg.examples.test_table 
with (format = 'parquet')
as select timestamp '2021-01-19 23:59:59.999999' as ts;
```
In Spark 
```scala    
spark.read
      .format("iceberg")
      .load("examples.test_table")
      .show(10, false)
```

Fails with exception `java.lang.UnsupportedOperationException: Spark does not support timestamp without time zone fields`

Please add support of `Timestamp without timezone` type into Iceberg Spark runtime, because Iceberg supports this type

**Comment by HeartSaVioR** [comment]
That's a fundamental issue on "Spark" side, not "Iceberg" side. Spark only has the type "timestamp" which is used as "timestamp with timezone". Iceberg can't add the support of "timestamp without timezone" arbitrarily on Spark. Spark's "user defined type" is not a public API so Iceberg can't even expose the column of the type as UDT as well.

There still has a possibility to expose it under "long" type, but you'll lose the characteristic of "timestamp" there. If we think it's still better than "don't support", probably a way to move forward.

**Comment by davseitsev** [comment]
According to Spark docs `TimestampType` represents values comprising values of fields year, month, day, hour, minute, and second, with the session local time-zone. The timestamp value represents an absolute point in time.  So it's more like `LocalDateTime`. Why can't  Iceberg expose `timestamp without timezone` as Spark `timestamp`?

As far as I understand the problem is that Spark has only one timestamp type but Iceberg has two types which causes some inconsistency in type mapping between Spark and Iceberg.

In my opinion it could be solved in a following way:
1. For read access there is no problem, both Iceberg types (`timestamp`, `timestamptz`) could be exposed as Spark `timestamp`.
2. For insert there is no problem because we know target type defined in the table metadata and can choose correct one
3. For table creation we have inconsistency which could be solved by configuration property. Spark has such kind of property to choose how to store timestamp fields in parquet (`spark.sql.parquet.outputTimestampType=(INT96 | TIMESTAMP_MICROS | TIMESTAMP_MILLIS)`). Why can't we have such logic for Iceberg?

**Comment by HeartSaVioR** [comment]
(DISCLAIMER: I'm just a contributor of the project, but familiar with ASF projects.)

Why not initiating discussion thread in dev@ mailing list? Basically ASF project is community driven and making consensus is the core culture. Discussion thread in dev@ mailing list would provide better traction and also would help making progress.

**Comment by javsanbel2** [comment]
Did the discussion thread started in the dev mailing list? How it went? I am interested in this issue too, as am having the same problem.

**Comment by davseitsev** [comment]
Related issues: https://github.com/apache/iceberg/issues/2388 and https://github.com/apache/iceberg/issues/2244
