### ISSUE TITLE
Flink schema validation always has checkNullability and checkOrdering set true. Any particular reason ?

### ISSUE THREAD

**Issue by elkhand** [apache/iceberg#2235]
Hi,

Flink schema validation (`TypeUtil.validateWriteSchema(schema, writeSchema, true, true);`) always has `checkNullability` and `checkOrdering` set true. 

Any particular reason for this, @openinx ?

In `org.apache.iceberg.flink.sink.FlinkSink` class:

```
static RowType toFlinkRowType(Schema schema, TableSchema requestedSchema) {
    if (requestedSchema != null) {
      // Convert the flink schema to iceberg schema firstly, then reassign ids to match the existing iceberg schema.
      Schema writeSchema = TypeUtil.reassignIds(FlinkSchemaUtil.convert(requestedSchema), schema);
      TypeUtil.validateWriteSchema(schema, writeSchema, true, true);
...
```

In Spark, both are read from specified options `checkNullability` and `checkOrdering`:

In `org.apache.iceberg.spark.source.SparkWriteBuilder` class:

for batch: 
```
 @Override
  public BatchWrite buildForBatch() {
    // Validate
    Schema writeSchema = SparkSchemaUtil.convert(table.schema(), dsSchema);
    TypeUtil.validateWriteSchema(table.schema(), writeSchema,
        checkNullability(spark, options), checkOrdering(spark, options));
...
```

for Streaming:
```
@Override
  public StreamingWrite buildForStreaming() {
    // Validate
    Schema writeSchema = SparkSchemaUtil.convert(table.schema(), dsSchema);
    TypeUtil.validateWriteSchema(table.schema(), writeSchema,
        checkNullability(spark, options), checkOrdering(spark, options));
```

**Comment by openinx** [comment]
@elkhand , Sorry for the delay,  there's no other reason that we did not provide the `checkNullability` and `checkOrdering` option.  We flink could provide that options if we really need.  I think that could be a TODO issue for iceberg flink connector.

**Comment by rdblue** [comment]
I disagree that there isn't a reason other than they aren't exposed. Originally, these weren't even options because the validation checks that the write is correct. Disabling the nullability check was added for cases where users wanted runtime failures because it was too hard to fix the schema that was being written. Disabling the order check was added because the Spark 2.4 planner wouldn't reorder columns automatically and users wanted to guarantee that the columns were correct without reordering.

In both cases, users wanted to disable checks because they had more information than Iceberg did. For example, that a table contained no null values even though a field was optional.

If someone wants to expose these, we should carefully consider the use case around it because not exposing these as options is the sensible default.
