### ISSUE TITLE
Investigate new DS V2 interfaces in Spark 3.1

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#2311]
We need to take a look at new interfaces in DS V2 in Spark 3.1 and see if we can support them.

**Comment by aokolnychyi** [comment]
@flyrain, could you take a look at this one?

**Comment by flyrain** [comment]
Currently, partition related ops like `Alter table add partition` and `Show partitions` fail due to Hive doesn't think an Iceberg table is partitioned even though it is. This probably can be resolved in Spark 3.1.
Spark 3.1 introduces interface SupportsPartitionManagement. We can let SparkTable extends it so that partition related ops can be supported for Iceberg table.

**Comment by flyrain** [comment]
According to the way Iceberg handles the partition, we probably never support a command to add/remove/rename a partition. We can still support the `Show partitions`, that's basically a call to metadata table https://iceberg.apache.org/docs/latest/spark-queries/#partitions.
```
SELECT * FROM prod.db.table.partitions
```

**Comment by aokolnychyi** [comment]
This has been resolved.
