### ISSUE TITLE
Internal Tests Cannot us ORC or Avro Datasource Writers

### ISSUE THREAD

**Issue by RussellSpitzer** [apache/iceberg#2360]
While working on the addFiles procedure I found that it is currently impossible to use Spark's Avro or ORC writers in our test code because of classpath issues.

See

https://github.com/apache/iceberg/blob/f0a6b717dbf662caa9c762e72c47715a12625647/spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java#L90-L128

which are created and written using the Spark Sources

https://github.com/apache/iceberg/blob/f0a6b717dbf662caa9c762e72c47715a12625647/spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java#L458-L465

We Should probably fix this so that the Spark sources's for these modules work. Alternative we can change the code in these tests to manually generate ORC and Avro files but that seems like a workaround for a classpath issue we should probably clean up.

For ORC there is a conflict right out of the box complaining about invalid libraries at runtime
For Avro, Spark3 has a warning that in Spark3 the spark-avro package is also required, I attempted adding this to testRuntime but didn't have any luck

**Comment by pvary** [comment]
We have faced the same issue when moved the mr module to the Hive repo. CC: @marton-bod
First random idea: create a bundled-orc / bundled-avro / bundled-parquet(?) modules like we did with guava?

**Comment by marton-bod** [comment]
Yes, we faced the same issue that Hive exec uses a different `orc-core` version than `iceberg-core`, therefore we were not able to pull both of them in and run unit tests that can write to Hive ORC tables and Iceberg ORC tables at the same time. In a real cluster, this problem goes away, because we shade the `orc-core` dep used by iceberg-orc and include that into the runtime jar. As @pvary mentioned our initial idea to resolve this was to create a new `bundled-orc` module in Iceberg to avoid any classpath conflicts with Hive. A similar approach could resolve the problems for Spark too.

**Comment by pan3793** [comment]
Suppose we do not intend to access iceberg internal API in `iceberg-spark`, `iceberg-spark-extension` modules (correct me if I'm wrong), move all test classes to `iceberg-spark-runtime` module should solve this problem.
