### ISSUE TITLE
Integrate Parquet bloomfilter feature 

### ISSUE THREAD

**Issue by shangxinli** [apache/iceberg#2391]
Parquet bloom filter(https://github.com/apache/parquet-format/blob/master/BloomFilter.md) will be available once parquet 1.12.0 is released. 

This issue is created to integrate parquet bloom filter after Iceberg upgrades the parquet version to 1.12.0 (https://github.com/apache/iceberg/issues/2390), and Parquet has the "column resolution by ID" feature https://issues.apache.org/jira/browse/PARQUET-2006

**Comment by shangxinli** [comment]
cc @chenjunjiedada

**Comment by chenjunjiedada** [comment]
Thanks for ping me, @shangxinli ! Let me try locally first, will post PR once it works well.

**Comment by kbendick** [comment]
This has been completed thanks to @\huaxingao and others.

See some related PRs:
- https://github.com/apache/iceberg/pull/4938
- https://github.com/apache/iceberg/pull/5035
- https://github.com/apache/iceberg/pull/5172

If there's anything else you'd like to follow up on, please create a new issue (as this one is somewhat old). There are a few open issues for example Flink support etc.

I'm going to close this, but feel free to open a new issue or reopen this one if you feel it's necessary (I suggest opening a new one as this issue is pretty old).

Thanks @shangxinli!
