### ISSUE TITLE
TableProperties 'write.format.default' not correct.

### ISSUE THREAD

**Issue by duydb81** [apache/iceberg#2440]
Hi,

I'm new to Iceberg and when I'm testing it I got this error when inserting into Iceberg table from Hue/Hive:

![image](https://user-images.githubusercontent.com/82132798/113965481-a6073900-9857-11eb-892f-7a2d92fb64ac.png)

I think there is a mistake here, because if I do not specify 'write.format.default' then it cannot get the default format, should it be 'PARQUET' (in capital letters) instead of 'parquet'?

![image](https://user-images.githubusercontent.com/82132798/113965773-2fb70680-9858-11eb-95fb-34b18be9220a.png)

Thanks and have a good day.

**Comment by pvary** [comment]
Hmm.. we might only need to capitalize the config values.
We should check how it is done in other places...

**Comment by marton-bod** [comment]
Thanks @duybd81 for flagging this! I think capitalization of the default value should solve this. I also think it would be logical to capitalize it given that it's transformed into a `FileFormat` in almost all cases and therefore has to be capitalized throughout most of the codebase anyway prior to passing it in.

I've run the whole test suite with the change and the only test that failed was `org.apache.iceberg.actions.TestCreateActions#testSparkTableReservedProperties`, due to the `format` table prop changing from `iceberg/parquet` to `iceberg/PARQUET`. @aokolnychyi @RussellSpitzer Do you see any potential problems with changing the `format` spark table prop as above?
