### ISSUE TITLE
Flink CDC | OOM during initial snapshot

### ISSUE THREAD

**Issue by ayush-san** [apache/iceberg#2504]
I am using flink CDC to stream CDC changes in an iceberg table. When I first run the flink job for a topic with all the data for a table, it gets out of heap memory as flink tries to load all the data during my 15mins checkpointing interval. Right now, the only solution I have is to pass `-ytm 8192 -yjm 2048m -p 2` for a table with 10M rows and then reduce it after the flink has consumed all the data. 
I am attaching a sample job DAG, for my prod job kafka topic has 2 partitions
![image](https://user-images.githubusercontent.com/57655135/115663412-13d65900-a35e-11eb-9218-9f2f9af2a5c4.png)
Shouldn't my iceberg sink have propagated the back-pressure up the source since it has not written that data yet and it will only do that after the checkpointing interval?
```
FlinkSink.forRowData(rowDataDataStream)
                .table(icebergTable)
                .tableSchema(FlinkSchemaUtil.toSchema(FlinkSchemaUtil.convert(icebergTable.schema())))
                .tableLoader(tableLoader)
                .equalityFieldColumns(tableConfig.getEqualityColumns())
                .build();
```

**Comment by openinx** [comment]
@ayush-san ,  I think that's because we've maintained all the keys that come from the same checkpoint in a __in-memory__  HashMap, it mainly used to locate the `<file_id, pos>` for the rows that was written in the current checkpoint before.  In the long run, we need to change this HashMap to a Map that can spill to disk or replace it with an embedded KV lib, so that we can take on a larger number of rows in a single checkpoint.  [This](https://docs.google.com/presentation/d/18xL5hhGfJKEVJyv-fbfoLYWgioRMqoEutpKFDjXhyKA/edit#slide=id.gb479a3dd40_0_948) would be a good document to describe the current design.

FYI @rdblue .

**Comment by ayush-san** [comment]
@openinx What should be the immediate solution for now? I can think of two ways
* Increase the job and task manager memory and keep the checkpoint the same
* During the initial few hours, reduce the checkpoint to 1/2 mins

**Comment by openinx** [comment]
@ayush-san  I think you may want to try this PR so that we could get ride of OOM when ingest the whole snapshots from the upstream mysql databases: https://github.com/apache/iceberg/pull/2680
