### ISSUE TITLE
Add metadata tables tests to make sure they don't break when reading different versions of tables

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#2532]
based on discussion in #2521

**Comment by taherk77** [comment]
I would like to work on this issue. Can someone please guide a little and give more context?

**Comment by RussellSpitzer** [comment]
@taherk77 That would be awesome!

https://github.com/apache/iceberg/issues/2542#issue-870411640 Here are @yyanyy 's notes on the problem. Basically we want to make sure that whether you have a v1 table or a v2 table, the metadata table code reads correctly. Our previous tests cover converting manifests but don't make sure that manifests from both versions can be accessed by the same metadata table code.

**Comment by itachi-sharingan** [comment]
Is it ok to assume that this issue and #2542 are duplicate? I am asking this to completely understand the ask here.

**Comment by itachi-sharingan** [comment]
@RussellSpitzer @yyanyy 
I am a newbie to this project so following question might be very trivial or wrong altogether, so I am ready to read through code and documentation to develop correct understanding of the project, but need some guidance to look at the correct place. 

Question:-
Here https://github.com/apache/iceberg/pull/2521#issuecomment-828793923, what I understand is that to ensure backward compatibility for reading manifest files we should create couple of data files and manifest files explicitly in resources folder and create iceberg table from them, and let then run couple of test on the table created. Now can you point me to some code or test where manifest files are used to create an iceberg table, because I see that tables are getting created by catalog.buildTable which only takes table identifier and schema as input but not using data files and manifest files. 

Also after figuring the above part, how can I find the fields that were introduced in different versions and remove them from manifest file in resources.

**Comment by yyanyy** [comment]
@itachi-sharingan welcome to the community! Your understanding is correct. For creating iceberg table, the manifest/data files are not needed as the input since they should be eventually linked from the table metadata file, so such relationship should be preserved from the table metadata object and the manifest files in the resources folder. 

For finding the files introduced, I think https://iceberg.apache.org/spec/#version-2 this could be a good place to check what's strictly required for v1 vs. v2; you can also create a v1 table (follow code path as in https://github.com/apache/iceberg/pull/2887 to find out the setting) and use the created files as starting point. I think we can have such setup for both v1 and v2 tables, so that in future when v3 is introduced we can continue to have this safety guard.

**Comment by ZhangchengHu0923** [comment]
I found this question was shelved for a long time,As it happens，I am a newbie to this projec,I'll pick up this work if u don't mind @itachi-sharingan  @yyanyy @RussellSpitzer ,I am going to do the test by following the steps below, @yyanyy  @RussellSpitzer  could u please take a look to see weather my undertanding about the issue is correct,thx a lot.

step 1:create v1 v2 tables by TestTables 
step 2:generate some data files and append to the tables
step 3:read diffrent kinds of meta info of both v1 and v2 table by subclasses of BaseMetadataTable，such as AllDataFilesTable/AllEntriesTable/HistoryTable, to see weather all theses subclasses work well

more questions:
> If my understanding is correct, what do u think is the good idea to divide the test work, divede according to v1/v2 version with 2 test class, or create one test class per kind of MetaDataTable?

> I plan to put the test class in iceberg-core/test,is that ok?

**Comment by kyle-cx** [comment]
hey guys:
       I spent some time on this issue, I need some help in order to move forward, could u please give me some guidance, thx. 
@RussellSpitzer @yyanyy 

here is my questions

> I was planning to do the test work in iceberg-core, but I think didn't find a complete impl of metadata tables of which I can read out metadata record, but I can only get some FileScanTask, just like TestIcebergSourceTablesBase.java shows.
  Should I do this testing at a higher abstraction, or am I misunderstanding these metadata tables and iceberg-core provides an implementation that can read metadata records, how do I call it?

> in #2521#issue comment-827897536 , @yyanyy  said "we create v1 and v2 normal table, write data to them, and then query the manifest table and ensure output meets expected", what does the expectation mean, the number of records or fields ? 

> in #2521#issue-comment-828793923, @yyanyy said "I think a way of achieving it could be to add resource files ...",My understanding of this is that we need to put the historical version, include 0.9.X/0.10.X/0.11.X/0.12.X/0.13.X, of the tables' file into the resources directory, when doing the test ,we load these files as tables and read the metadata of them. is my understanding correct?

**Comment by kyle-cx** [comment]
finally, I found a way to read records from a table, and I'll move forward follow the code below and do the test in iceberg-core, I hope this could reflect the behavior of reading metadata tables in higher abstractions like spark/flink
```
CloseableIterable<Record> result = IcebergGenerics.read(table)
        .where(Expressions.lessThan("id", 5))
        .build();
```

**Comment by sfc-gh-aixu** [comment]
@RussellSpitzer and @yyanyy Seems we haven't made progress with this one.  I would like to start with some simple tasks in Iceberg.  Can you assign to me?
