### ISSUE TITLE
Does the Spark 2.4 support catalog?

### ISSUE THREAD

**Issue by zorrofox** [apache/iceberg#2700]
Hi,

I want to confirm that is the meaning for the `Icberg Catalog` from [the Doc](https://iceberg.apache.org/spark-configuration/#catalogs-in-spark-24), because I just want to confirm that if Spark 2.4 support using catalog. 
![image](https://user-images.githubusercontent.com/1528417/122150951-4188db80-ce91-11eb-91aa-aaaee7961841.png)

Another [Doc piece](https://iceberg.apache.org/spark/#spark-24) said Spark 2.4 is not support catalog. It confuse me that the `Iceber Catalog` is not refer to Spark Catalog?
![image](https://user-images.githubusercontent.com/1528417/122151024-5d8c7d00-ce91-11eb-8516-14db12d57fc1.png)

**Comment by flyrain** [comment]
I believe the second page needs to be updated. cc @rdblue @RussellSpitzer

**Comment by zorrofox** [comment]
@flyrain You are right, I have successfully run the Catalog in Spark 2.4.

**Comment by rdblue** [comment]
I think the second page is the old `spark.md` that was refactored into several pages in the current layout. I thought that references to that page were mostly gone, but I left it so that we didn't have broken links (at least until we could provide JS-based redirects). Since it is causing confusion, I think we should just remove the page.

**Comment by flyrain** [comment]
Removed the file spark.md in PR #2727.
