### ISSUE TITLE
Can Spark iceberg connector read from specific file?

### ISSUE THREAD

**Issue by GrigorievNick** [apache/iceberg#2917]
I wanna read few files from the previous version of the table.
I can find files and their metadata using `.files`. prefix in the datable name.
```
val files = sparkSession
      .read
      .option("snapshot-id", previousVersion)
      .format("iceberg")
      .load(s"$testTable.files")
      .filter(my filters to find file)
```
I also see that in Spark3RewriteActions I can specify a list of files to read from the table using `FILE_SCAN_TASK_SET_ID`
```
   val manager = FileScanTaskSetManager.get 
    manager.stageTasks(table, "fileGroupId", fileScanTasksList)
    sparkSession
      .read
      .format("iceberg")
      .option("snapshot-id", previous)
      .option(SparkReadOptions.FILE_SCAN_TASK_SET_ID, "groufileGroupIdpID")
      .load(testTable)
```
What I can find is how to create `FileScanTask` from `$testTable.files` or from any output.
In code, I see that `DataTableScan` use `ManifestReadtask`, but I don't see any code to read from one or a few predefine iceberg files.
Do I need to write my own FileScanTask implementation, or there is a code that already does it?

**Comment by RussellSpitzer** [comment]
Reading specific files isn't really supported at the moment although you may be able to repurpose the Rewrite code to handle it... To do so you would have to make BaseFileScanTasks which you could do by converting the File metadata rows into DataFiles (See SparkDataFile) and then putting those into the manager ....

I think one of the key issues is that the way we read the files is also state dependent on the table at that time so we have to know what spec we are using, for the residual evaluator you can just put in an always true evaluator.

---

If you just want to read  files it may make sense to just pass the file paths to the normal spark reading code rather than doing it through the Iceberg Datasource. Something like 

https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L595
spark.read.parquet(files:_*)

**Comment by GrigorievNick** [comment]
@RussellSpitzer Thx, the first approach is exactly what I am looking for, and because I know manifests and snapshots I will be able to reproduce the exact state.
The goal of this task is to implement file coupling based on a specific column in the table and flatMap iceberg files to rows.

>If you just want to read files it may make sense to just pass the file paths to the normal spark reading code rather than doing it through the Iceberg Datasource. Something like

 I was not able to use it with ORC files.
 ```
Type 3 has an unknown kind.
java.io.IOException: Type 3 has an unknown kind.
```
 I will try

**Comment by kbendick** [comment]
Could the unknown kind come from using capital `String` for your type for `idRange`?

**Comment by GrigorievNick** [comment]
@kbendick Thank you, it's definitely an issue. 
So thx you guys for the help, both your answers id definitely what I am looking for.
