### ISSUE TITLE
Is Iceberg support ranger partition?

### ISSUE THREAD

**Issue by EricJoy2048** [apache/iceberg#3026]
In my case, I have a column named `id` and data type is `long` in my table.  I want create ranger partition from `id` column.
I think the truncate's width (W)  can do this. But the `W` only can be `Integer` now. Why not supported long type?

**Comment by openinx** [comment]
Could you please give more information about how would you like to use the truncate#width to create a ranger partition ? I did not quite understand your case actually. Thanks.

**Comment by gaojun2048** [comment]
> Could you please give more information about how would you like to use the truncate#width to create a ranger partition ? I did not quite understand your case actually. Thanks.

From the iceberg document I found W is the width of each partition, not the number of partitions.
If I want to divide the numbers from 1 to 100 into 3 ranger partitions, W should be 100/3 + 1 = 34 (because 100% 3 != 0).
Do i have a misunderstanding?

And then if I want to divide the numbers from Long.MIN_VALUE to Long.MAX_VALUE into 10 ranger partitions, W should be (Long.MAX_VALUE - Long.MIN_VALUE ) / 10 + 1 .

**Comment by kamiltalipov** [comment]
I would like to add an example where I had to add a fake column in order to mitigate the problem. There is a long type column which contains time with milliseconds precision. I want to have a partition for every 1000 seconds. Unfortunately, `1000 * 10 ** 9` is greater than `Integer.MAX_VALUE`. Trying to use this value would lead to error `Unsupported width for transform: truncate(1000000000000, message_ts)`. So, to deal with it I added a fake column which contains time in seconds, not in milliseconds.
