### ISSUE TITLE
[Python] support iceberg hadoop catalog in python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3220]

**Comment by srilman** [comment]
Is anyone planning to work on this? Would be happy to pick this up!

**Comment by Fokko** [comment]
I'm seeing more and more people asking for this. The Hadoop catalog is a tricky implementation since it isn't supported my many object stores. Should we provide a `from_uri` method, to load a table without a catalog? Not having a catalog means that it isn't able to do any alterations to the table, but should be able to load it and have read-only support.

**Comment by ajantha-bhat** [comment]
IMO, Hadoop catalog is not a production recommended catalog (https://iceberg.apache.org/docs/latest/java-api-quickstart/#using-hadoop-tables)

> Hadoop tables shouldn’t be used with file systems that do not support atomic rename. Iceberg relies on rename to synchronize concurrent commits for directory tables.

I am not sure we should support it from python and let more users use it!

**Comment by Fokko** [comment]
@ajantha-bhat that's exactly my consideration as well. However, there are users that use for example ADLS, which has [support for atomic renames](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace#the-benefits-of-a-hierarchical-namespace), [PR opened here](https://github.com/apache/iceberg/pull/6392). On top of that, this is only relevant when writing to tables.

**Comment by rdblue** [comment]
For what it's worth, I think that **the biggest mistake I made with Iceberg was introducing the "Hadoop" tables** that rely on atomic rename.

These tables have a lot of problems and limitations in HDFS, but the bigger problem is that people choose to use them on unsafe object stores to avoid having a catalog/metastore. I think that introducing these in the Python implementation will only cause people to think that this is a reasonable choice and cause a lot of problems.

I'm a firm -1 on adding this to the Python implementation. If anyone wants to move forward with this, then I suggest we debate it on the mailing list and vote on it. If I'm out voted and the community clearly wants to do this I won't oppose it.

**Comment by ajantha-bhat** [comment]
+1, I strongly agree with Ryan. 

I do believe Hadoop catalog has greatly helped in Iceberg adoption (to try it out quickly). 
But we don't highlight its problem strongly enough. Even the [getting started page](https://iceberg.apache.org/docs/latest/getting-started/) uses only Hadoop catalog and no warnings are mentioned on that page. I have seen many users using the same catalog in concurrent scenarios and asking for help.  

But I do worry that if we deprecate it or remove it, It may hamper the adoption rate. So we are leaving it as it is. 
Maybe we can improve the warnings in the document section and introduce a page for catalogs in detail.

**Comment by srilman** [comment]
FYI, I did start working on an initial implementation but ran into issues with trying to use just FileIO to perform special operations needed for Hadoop tables (I believe hadoop FS libraries are used instead in the Java implementation).

As a developer for a Python-based compute engine, we would like to start using PyIceberg. However, we use Hadoop tables extensively for 
(1) Local testing since it is easy to view and modify metadata 
(2) Public read-only examples on remote FS like S3

I think we should be able to replace usages of (1) by using a SQLLite DB + JDBCCatalog locally, or some equivalent SQLCatalog for Python. However, as long as there exists catalogs unsupported in Python, I think there should be some way for users to access their tables  in some limited fashion (like read-only as Fokko suggested). Thoughts?

**Comment by Fokko** [comment]
Hey everyone, I think we should split out the idea of implementing the full hadoop catalog, and just being able to read a table from a metadata URL. For the latter, I've created a new issue: https://github.com/apache/iceberg/issues/6430

My apologies for invoking the negative feelings around the HadoopCatalog, and I fully agree that this is something we should avoid in PyIceberg. However, I do see a lot of value in just reading (not writing!) and just using a path to the metadata.

@srilman I've recently started working on [integration tests](https://github.com/apache/iceberg/pull/6398) that write tables using Spark (since PyIceberg doesn't have any read support), and these are shared using the RestCatalog. Would love to get your thoughts on that!

**Comment by djouallah** [comment]
for people that uses only Python ( no spark, nor glue and all this big engine stuff), is there any simple to use catalog, I read about this REST thing, but it seems it is only a spec, not an actual piece of software ?

**Comment by srilman** [comment]
@Fokko Didn't realize that there was a Docker image for REST catalog! We use a very similar Docker Compose setup to test for Hive catalog support, which is great for testing catalog integration. Will definitely look into using this once we add REST catalog support.

However, I think Docker Compose might be a bit too _much_ for our Iceberg unit tests due to start-up times and difficulty to read and modify metadata on the fly. Those were two big benefits of Hadoop tables. If there is a simpler REST catalog server implementation, like as a Python or Node script, that'd be great. Otherwise, I think JDBCCatalog is better for unit testing. Are there plans to add that catalog to PyIceberg?

**Comment by Fokko** [comment]
Migrated to the new repository: https://github.com/apache/iceberg-python/issues/17
