### ISSUE TITLE
[Python] support partition spec in iceberg python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3228]

**Comment by samredai** [comment]
Now that schema has been merged I think we need a couple more PRs in order to close this:
1. PartitionField
2. PartitionSpec
3. PartitionSpecBuilder

For 3. I know we discussed whether we should go with the builder pattern or just lean into python's ability for named optional arguments. There might be a middle ground in there where we use the builder pattern (to maintain consistency with the java codebase) and simply use that builder in the `PartitionSpec` dunder init.

**Comment by dramaticlly** [comment]
I can help by starting with PartitionSpec!

**Comment by rdblue** [comment]
This was added in the PRs above, so I'll close this.
