### ISSUE TITLE
[Python] support table scan in iceberg python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3229]
This task is to implement table scan function in iceberg/python library. There is an implementation in iceberg/python_legacy library. Please review it and then either update it or rewrite it.

**Comment by askalik** [comment]
would this issue be updating the python legacy table scan code in the iceberg/python directory?

**Comment by askalik** [comment]
@jun-he could I try and complete this? 

Assuming goes well, would likely try taking in some of the others.

Wanting to complete as part of hacktoberfest

**Comment by jun-he** [comment]
Hi @askalik, thanks for the help. I assign this task to you.

**Comment by Fokko** [comment]
I'll bump this to the next release 👍🏻

**Comment by simjay** [comment]
Hi @jun-he, I was on the monthly sync today and heard you might want to revisit this task and I am interested. I want to take a stab at it but if you could give any pointer for me to understand the how you want the refactor to be done, it would be amazing. 

For now, I read the legacy_python's DataTableScan implementation and currently trying to understand more on how this repo is structured. Any guidance or more details would be much appreciated, so that potentially i can contribute to this ticket!

**Comment by Fokko** [comment]
This is in: https://github.com/apache/iceberg/pull/6233
