### ISSUE TITLE
[Python] support iceberg base catalog in python library

### ISSUE THREAD

**Issue by jun-he** [apache/iceberg#3245]
Seems we can use ABC for this.

**Comment by samredai** [comment]
Here are some additional notes/details/questions to guide this issue. I've also included a diagram of the java implementation.

- Catalog abstraction
  - Operations
    - List tables
    - Create a table
    - Drop a table
    - Replace table
    - Load table (returns an instance of the main table class that users will interact with)
    - Rename a table
    - Check that a table exists (or maybe this is done in load table. Python users will be familiar with `try catalog.load_table() except MissingTableException`)
- Table identifier (maybe not needed?)
  - In python, a table identifier could just be a string and the main Table class itself could also serve as the table identifier. `Table(“foo.bar.baz”, catalog=Catalog(...))` or `Table(namespace=”foo”, database=”bar”, table=”baz”, catalog=Catalog(...))`. Loading the table from the catalog would then be `Table.load()`.
  - “Loading a table” from the catalog could easily be confused with loading the actual data. Since we’ll have both of these functionalities in a single library, should we have a more explicit class name here so it’s not confused with whatever the particular in-memory table format is that’s being used, i.e. pyarrow.Table, pandas.DataFrame, numpy.ndarray, etc.? Some options:
    - IcebergTable
    - TableMetadata
    - TableInfo
- Namespace: Does this need to be a class? Can the `catalog.listNamespaces` method just take a string as an argument?
- Should the JDBC catalog implementation be ranked higher in priority than the hive catalog?

Java implementation:

![catalog](https://user-images.githubusercontent.com/43911210/152832960-77afbccd-02f3-456e-8863-bd8988d02afe.png)

**Comment by cccs-eric** [comment]
@samredai Is there a plan to support a filesystem-based catalog?  Local filesystem, AWS S3 buckets or Azure datalake?  Or that use case would be cover by `Table.load(locationUri)` assuming you know the location URI?

**Comment by dhruv-pratap** [comment]
@jun-he Can you please assign this task to me?

I had a discussion with @samredai and @cabhishek on this task today, and we feel it is a nice candidate work-stream to kick-start  in parallel to all the others as catalog would be a nice convergence point for all the other work-streams to integrate into and test. 

To summarize our discussion, we would be breaking this larger effort into smaller chunks as listed below:

- [ ] Base Catalog with just table interfaces
- [ ] In-memory catalog implementation (Dictionary based)
- [ ] Add Transaction interfaces to Base Catalog
- [ ] In-memory catalog transaction interfaces implementation
- [ ] REST Catalog Implementation (This might be a separate tracker)

Initial structure of the implementation we discussed:

- We already have a `catalog` package, 
- We will be adding a `base.py` module in it to contain the `Catalog` base class.
- Extend it as `InMemoryCatalog` in a 'in_memory.py' module under the same 'catalog' package.

Happy to answer any other questions.

**Comment by Fokko** [comment]
You've [completed this task a while](https://github.com/apache/iceberg/blob/master/python/pyiceberg/catalog/__init__.py#L115) ago @dhruv-pratap Thanks for working on this! 👍🏻
