### ISSUE TITLE
Hive: Bug when runing SQL with multiple table join

### ISSUE THREAD

**Issue by openinx** [apache/iceberg#3393]
I encountered an iceberg bug when executing Hive query to iceberg table. I can reproduce this by writing an unit test: https://github.com/apache/iceberg/pull/3392/files#diff-514a9a4a1b39ecf3ed48a4099e0d9335f7eede202cf72adc889f9f75cb810cfdR227

![image](https://user-images.githubusercontent.com/5028729/139045256-b433142e-b68e-413f-a749-0052196778de.png)

I think this bug is related this PR (https://github.com/apache/iceberg/pull/2052), but I'm not quite familiar with hive internal.  @pvary , @qphien, @marton-bod  Could you help to check this ?

**Comment by kbendick** [comment]
As we've cherry-picked all of the completed PRs for 0.12.1, I'm going to remove this from the 0.12.1 milestone @openinx.

As I mentioned before, if / when we find a fix, we can cut a release if we feel it's urgent. Or if we're close enough to the next major release we can let it go out there.

Maybe add this to the 0.13.0 project so it's still tracked somewhere that's likely to be seen? https://github.com/apache/iceberg/projects/24

**Comment by kbendick** [comment]
@openinx I am following up on this, but wondering if you have any new information on this to add?

**Comment by kbendick** [comment]
I'm marking this as important for 0.13.0.

It seems that this bug only occurs when CBO is on, but I really don't know enough about Hive to be able to say much beyond that.

**Comment by pvary** [comment]
I have found this to be a Hive issue, and fixed it in Hive code: apache/hive#2765

**Comment by kbendick** [comment]
Thank you @pvary! I tried checking out the PR with the bug report and rebasing off of the latest master, and it still happens when using MR, which I suppose isn't unexpected given that the fix was only recently added upstream.

Is there anything that we need to update within Iceberg's repo? I bumped the `org.apache.hive` version to 2.3.9 (from 2.3.8), but that was still released well before your fix in Hive.

Will there be a 2.3.10 release or do we have to do anything from within Iceberg eventually to pick up the changes?

**Comment by pvary** [comment]
TBH, this fix is a really interesting story:
- No Iceberg change is needed - this is clearly a Hive issue.
- In Hive master we are phasing out MR, and only Tez is supported (the issue does not happen with Tez)
- Even the tests are lame for the fix as we need to insert the data with Tez (MR is not supported with Iceberg), but the query should be run with MR to find the issue.
- To be correctly backported the change should be rebased to Hive branch-2.3, branch-2, branch-3 and branch 3.1. The issue is that the tests will not work for these branches as Iceberg is not supported there.

I have serious number of other tasks. I have found the issue and put the solution upstream, so if someone faces this they can fix it, but sadly I did not have time to follow up with a solution which could be released. I hope the affected ones will find it here, and if someone has time to backport the fixes, I am happy to review and push.

Thanks,
Peter

**Comment by jackye1995** [comment]
Given this is a Hive issue, I am removing this out of the 0.13 milestone. Please let me know if anyone concerns.

**Comment by kbendick** [comment]
> TBH, this fix is a really interesting story:
> 
> * No Iceberg change is needed - this is clearly a Hive issue.
> * In Hive master we are phasing out MR, and only Tez is supported (the issue does not happen with Tez)
> * Even the tests are lame for the fix as we need to insert the data with Tez (MR is not supported with Iceberg), but the query should be run with MR to find the issue.
> * To be correctly backported the change should be rebased to Hive branch-2.3, branch-2, branch-3 and branch 3.1. The issue is that the tests will not work for these branches as Iceberg is not supported there.
> 
> I have serious number of other tasks. I have found the issue and put the solution upstream, so if someone faces this they can fix it, but sadly I did not have time to follow up with a solution which could be released. I hope the affected ones will find it here, and if someone has time to backport the fixes, I am happy to review and push.
> 
> Thanks, Peter

Thanks for the deep dive @pvary! I think it’s fair to leave as is, and if somebody is really affected they can pick up the issue or apply the necessary patch in their fork.

This also begs the question: should we be running MR in the unit tests in this repo? How many users are using MR vs Tez for the limited amount of functionality that is supported?

It’s also good to remove from the 0.13.0 milestone, as there’s nothing we can do about it here.

**Comment by pvary** [comment]
To be honest I would like to keep the tests here even if the functionality is not widely used. At least the MR version is somewhat working.
Tez functionality not works out of the box with the current Hive versions :( :( :(. We identified several Tez and Hive changes which are needed.

Still we would like to use this as guinea pig for making sure that the basic Hive functionalities are intact. If there is some Iceberg change affecting the Hive integration the tests should show them immediately, rather than facing them only when we upgrade the Iceberg version after a release.

+1 on removing this from the 0.13.0 milesonte
