### ISSUE TITLE
Help, Build iceberg project successfully with master or 0.12.x branch, but no flink-runtime directory exists in iceberg-root-directory, why?

### ISSUE THREAD

**Issue by wxy7** [apache/iceberg#3518]
![image](https://user-images.githubusercontent.com/40302376/141062252-e921304c-8124-450b-bd8a-799785626960.png)

Help, Build iceberg project successfully with master or 0.12.x branch, but no flink-runtime directory exists in iceberg-root-directory, why?

**Comment by openinx** [comment]
If you build the master branch, then the iceberg-flink-runtime has been moved into its own specific versioned modules, such as https://github.com/apache/iceberg/tree/master/flink/v1.12 and https://github.com/apache/iceberg/tree/master/flink/v1.13.

If you build the 0.12.x branch, then the iceberg-flink-runtime should be existed in the root iceberg project directory.

**Comment by wxy7** [comment]
![image](https://user-images.githubusercontent.com/40302376/141079448-37306ec9-3044-4000-9633-e2494e1fa09a.png)

Well, thx for answer!  I've tried to build master branch, like the above pic. The iceberg-flink-runtime has been moved into v1.13/flink-runtime, but not in v1.12/flink-runtime.

And then tried to build 0.12.x branch, it's OK now!

**Comment by openinx** [comment]
> The iceberg-flink-runtime has been moved into v1.13/flink-runtime, but not in v1.12/flink-runtime.

No we don't just move the iceberg-flink-runtime to v1.13/flink-runtime, instead we create a separate iceberg-flink-runtime for different specified flink version.   When build the iceberg project, we don't get the `iceberg-flink-1.12-runtime-0.13.0-SNAPSHOT.jar` because we don't enable the flink1.12 build by default ( the default flink version is 1.13, you can see https://github.com/apache/iceberg/blob/master/gradle.properties#L18). And if you want to enable the flink1.12 build, you can choose one of the approaches:

1.  Add `1.12` in the gradle.properties;
2. Execute the command: 

```
./gradlew -DflinkVersions=1.12 iceberg-flink:iceberg-flink-1.12:build -x test
```

**Comment by openinx** [comment]
Close this issue now,  feel free to reopen it if have more questions.

**Comment by wxy7** [comment]
Well Done!!  thx so much! @openinx
