### ISSUE TITLE
Iceberg does not support drop namespace cascade

### ISSUE THREAD

**Issue by pan3793** [apache/iceberg#3541]
The semantic of drop namespace cascade is different between Iceberg and Spark, then run Spark SQL `DROP DATABASE xxx CASCADE` cause failure if the database is not empty.

Iceberg `interface SupportsNamespaces`
```
  /**
   * Drop a namespace. If the namespace exists and was dropped, this will return true.
   *
   * @param namespace a namespace. {@link Namespace}
   * @return true if the namespace was dropped, false otherwise.
   * @throws NamespaceNotEmptyException If the namespace does not empty
   */
  boolean dropNamespace(Namespace namespace) throws NamespaceNotEmptyException;
```

Spark `interface SupportsNamespaces extends CatalogPlugin`
```
  /**
   * Drop a namespace from the catalog, recursively dropping all objects within the namespace.
   * <p>
   * If the catalog implementation does not support this operation, it may throw
   * {@link UnsupportedOperationException}.
   *
   * @param namespace a multi-part namespace
   * @return true if the namespace was dropped
   * @throws NoSuchNamespaceException If the namespace does not exist (optional)
   * @throws UnsupportedOperationException If drop is not a supported operation
   */
  boolean dropNamespace(String[] namespace) throws NoSuchNamespaceException;
```

The `CASCADE` logic is handled by `DropNamespaceExec`
```
    if (nsCatalog.namespaceExists(ns)) {
      // The default behavior of `SupportsNamespace.dropNamespace()` is cascading,
      // so make sure the namespace to drop is empty.
      if (!cascade) {
        if (catalog.asTableCatalog.listTables(ns).nonEmpty
          || nsCatalog.listNamespaces(ns).nonEmpty) {
          throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)
        }
      }

      if (!nsCatalog.dropNamespace(ns)) {
        throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)
      }
```

**Comment by rdblue** [comment]
From the code, it looks like returning false is allowed and will result in an error that the namespace can't be dropped because it is not empty.

**Comment by kbendick** [comment]
Hi @pan3793 - Thanks for reporting this!

I spent some time looking into this, and it doesn't seem as though Spark exposes `CASCADE` to the interfaces that external catalogs are supposed to implement.

In fact, their javadocs _do_ say that the default behavior is to `CASCADE`, but `SupportsNamespace` doesn't capture any of the information related to cascading from `DropNamespaceExec`.

Even in their tests for external catalogs, they only have a test that throws if the namespace isn't empty: https://github.com/apache/spark/blob/5c0762b5d2004464c36df353a4d483f8f57eebeb/sql/[…]/spark/sql/execution/datasources/v2/V2SessionCatalogSuite.scala

That's sort of what they're implying in the comment:

```
// The default behavior of `SupportsNamespace.dropNamespace()` is cascading,
// so make sure the namespace to drop is empty.
```

Even their implementation `DropNamespaceExec` (which you posted here) doesn't seem to handle `CASCADE` behavior at all which is why they actually check and throw vs list and drop.

And poking around the query planner, it doesn't seem to be the case that any instantiated `DropNamespace` node actually causes cascading either, at least for V2Catalog interfaces.

I'm going to poke around a bit more to see if there is an easy way to get at the `CASCADE` information - but I think that their documentation is a little off, specifically for external catalogs.

I will get back and confirm that. Since it's not exposed in Spark's `SupportsNamespace` interface presently, it will probably a little more difficult to get this behavior until it can be fixed upstream.

But hopefully I'm wrong and it's a simple change!

**Comment by kbendick** [comment]
Ok. On further inspection, it seems that the V2SessionCatalog falls back to the V1 definition `DropDatabaseExec`:

https://github.com/apache/spark/blob/8ab9d6327d7db20a4257f9fe6d0b17919576be5e/sql/core/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveSessionCatalog.scala#L254-L255

So we'd likely have to inject our own analyzer rule, or get that information exposed upstream in Spark (having Spark expose it being the better choice but longer task): https://github.com/apache/spark/blob/4df40ead99f07b87e3207c9d18c1b4f1f92a3b86/sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala#L182-L190

**Comment by pan3793** [comment]
Thanks for your reply, the cascade logic is handled by `DropNamespaceExec`, I updated issue description.

**Comment by kbendick** [comment]
> Thanks for your reply, the cascade logic is handled by `DropNamespaceExec`, I updated issue description.

Appreciate the update.

Unfortunately, there's not really presently a way to access whether or not the user has set CASCADE in the query based on the interfaces that Spark provides.

Spark gives us essentially the same `SupportsNamespaces` interfaces, and `dropNamespace` only provides access to the `Namespace` that the user passed.

Our code (at least in the HiveCatalog) simply implements the interface Spark provides, which doesn't provide access to whether or not the `CASCADE` flag is set.

**Comment by pan3793** [comment]
Spark already told us the dropNamespace should be act as `CASCADE`

Spark `interface SupportsNamespaces extends CatalogPlugin`
```
  /**
   * Drop a namespace from the catalog, **recursively dropping all objects within the namespace.**
   * .....
   */
  boolean dropNamespace(String[] namespace) throws NoSuchNamespaceException;
```

And in `DropNamespaceExec`, Spark know the `CASCADE` flag, and handled by 

```
      if (!cascade) {
        if (catalog.asTableCatalog.listTables(ns).nonEmpty
          || nsCatalog.listNamespaces(ns).nonEmpty) {
          throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)
        }
      }

      if (!nsCatalog.dropNamespace(ns)) {
        throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)
      }
```

**Comment by pan3793** [comment]
Seems the second `throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)` doesn't make sense

**Comment by pan3793** [comment]
What if the following change in Iceberg `interface SupportsNamespaces`

```
default boolean dropNamespace(Namespace namespace) throws NamespaceNotEmptyException {
    dropNamespace(namespace, false);
}

boolean dropNamespace(Namespace namespace, boolean cascade) throws NamespaceNotEmptyException;
```

And expose `dropNamespace(namespace, cascade=true)` to SparkCatalog

**Comment by kbendick** [comment]
Yeah. That's what I mean.

I know the Spark docs mention it, but they're actually the ones that even throw the exception. I did a pretty deep dive and I can see how Hive tables are able to handle it. They follow an older pathway `DropDatabaseCommand`, which relies on HMS to handle the Cascade.

The problem with the approach that you mentioned is that we still wouldn't have the ability to get the `CASCADE` information from the query. Just setting it to `true` by default is most likely not going to work for most cases.

We'd have to implement our own antlr grammar to catch `drop table ... cascade`. That's something that could be done, but it's not a trivial amount of work necessarily.

**Comment by kbendick** [comment]
I can sync up with some people in the Spark community that I know and see if there is a way to get access to whether or not that flag is set.

If I don't get back to you in a few days, feel free to message me on the Iceberg slack 🙂

**Comment by kbendick** [comment]
May I ask too, how big of an issue is this for you in practice? What's the workflow that you use that requires Cascade support?

I 100% agree it would be great to support, but it would be helpful to know your specific pain point and how you're using CASCADE in your workflows if you don't mind sharing. Is it in Dev environments to easily stand up and tear things down? Or do you use a namespace perhaps as a staging environment during your jobs?

**Comment by pan3793** [comment]
> The problem with the approach that you mentioned is that we still wouldn't have the ability to get the CASCADE information from the query.

I can't agree. Spark already handled the nonempty detection, an exception will throw if drop a nonempty database without CASCADE. Why Iceberg need to know the CASCADE flag?
```
      if (!cascade) {
        if (catalog.asTableCatalog.listTables(ns).nonEmpty
          || nsCatalog.listNamespaces(ns).nonEmpty) {
          throw QueryExecutionErrors.cannotDropNonemptyNamespaceError(namespace)
        }
      }
```

**Comment by pan3793** [comment]
> May I ask too, how big of an issue is this for you in practice? What's the workflow that you use that requires Cascade support?

I encounter this issue when change the TPCDS test suite from Delta table format to Iceberg. The drop database cascade sql work with delta but failed in iceberg.

https://github.com/apache/incubator-kyuubi/blob/2baabf46cacf745e5ceaf78192f9f2359dc9e477/kyuubi-server/src/test/scala/org/apache/kyuubi/operation/tpcds/OutputSchemaTPCDSSuite.scala#L70

**Comment by kbendick** [comment]
Spark has access to that information, but presently it just throws an exception after doing the lists.

So if it was changed on the spark side to list the tables and drop them if `cascade` is used, Iceberg wouldn't need to know at all.

But unfortunately that's not what Spark does. I'll try syncing up with some folks that are more deeply integrated with the core Spark community to see if something can be done, but I'm not super confident much will come from it. At least not very quickly.

**Comment by kbendick** [comment]
If you have further ideas, I'm definitely open to hearing them. As I said, I'll try to reach out to some contacts who might be able to shed more insight.

If Spark even threw a different exception based on Cascade, we could catch it and then delete everything. But the exception is the same whether cascade flag is used or not.

**Comment by pan3793** [comment]
The original PR https://github.com/apache/spark/pull/26476 description shows the design is for performance purpose.

**Comment by kbendick** [comment]
Oh cool. This is a bit more promising. I'll try to take a look and see how these tests are working.

I didn't come across these tests surprisingly, even when I opened it up in intellij and did code search etc.

I'd also gladly review a PR if you happen to have time. I'll try to sort through how their `foo` data source is using Cascade, but I won't necessarily have time to implement it if it's complicated.

**Comment by kbendick** [comment]
One last question @pan3793.

Which catalog are you using? It might eventually make a difference so if I can be testing it from that point of view that would be preferable.

**Comment by pan3793** [comment]
`HadoopCatalog`

**Comment by kbendick** [comment]
Ok. Well, I think I've mostly figured it out.

So the contract says that things should `CASCADE` by default. Which is why it's not exposed to Iceberg or other connectors.

All of the tests that I've found which use `CASCADE` use the `InMemoryTableCatalog`. The `InMemoryTableCatalog` does in fact list all namespaces and things and drops them by default.
https://github.com/apache/spark/blob/e99fdf9654481dd9b691a3c10e52f3f3db6ed2ba/sql/catalyst/src/test/scala/org/apache/spark/sql/connector/catalog/InMemoryTableCatalog.scala#L216-L224

It seems to be that the contract is supposed to be that people who implement `dropNamespace` are supposed to eagerly cascade. I will look into this more (as its getting late for me and its been a long day), but if there is danger of corrupting people's data or accidentally allowing people to drop large things they didn't intend to, then that's probably something that's going to need to be discussed.

I've talked to a decent number of people at several different large organizations that use Spark, and it's pretty rare for very large organizations to even let their users actually purge data. As often times, users want that data back within a few days or so or they didn't intend to delete it at all.

So that at least accounts for how the existing tests which have `cascade` in them work. Because of that `InMemoryTableCatalog`, which does list and drop everything. It seems that for performance reasons, they've offloaded the work of listing and dropping from spark to the individual catalog implementations.

So we'll see. If it's possible to have `cascade` and still be safe for the underlying data - meaning that the `RESTRICT` keyword isn't required, then I'm definitely very much in favor of it.

It's too bad they don't allow for seeing if the flag is set or not, as listing is also expensive for us if each individual call is going to wind up getting ultimately rejected.

But that `InMemoryTableCatalog` should provide some hints on how they have cascade working.

The reason that I worry it might not be safe for us, is that for our implementation of `HiveCatalog`, we have to pass `cascade` directly to the Hive Metastore Client: https://github.com/apache/iceberg/blob/f68d8d426661efc0d7e5686fe833b573b74eadab/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L271-L284

So I don't think that would go through Spark, which assumes it has control over it.

Again, I'd love to be wrong. So if you can come up with a PR that works and doesn't require people to use `RESTRICT` and doesn't simply always cascade, regardless of what the user puts, I'd 100% sign off on that.

I'll also try to find time to play around and see if I can get it to work that way. Hopefully it's something that we can make work, but Spark does seem to assume that all of the interactions with Hive go through it and that's not necessarily true for us as far as I can tell because of our implementation of `HiveCatalog` (as we interact with a large number of systems, not just Spark).

This would all be a lot easier if Spark exposed whether or not the user had entered `cascade` into the query for us. But if we can make this work, then I'd love to get this fixed. 🙂

**Comment by kbendick** [comment]
Actually, I started playing around with it and we might get lucky and it might not be as bad as I thought.

If you don't hear from me in the next few days, feel free to reach out on the Iceberg Slack. 🙂

**Comment by kbendick** [comment]
Ok, actually I spoke too soon.

I've gotten at least one test to work now. I will follow up with some kind of draft PR in the next few days.

Thanks for your patience and report @pan3793!

**Comment by kbendick** [comment]
Appears we might have things working after all, for all catalogs!

Thanks for your continued patience.

I'll push a PR shortly.

**Comment by kbendick** [comment]
> I encounter this issue when change the TPCDS test suite from Delta table format to Iceberg. The drop database cascade sql works with delta but failed in iceberg.
> 
> https://github.com/apache/incubator-kyuubi/blob/2baabf46cacf745e5ceaf78192f9f2359dc9e477/kyuubi-server/src/test/scala/org/apache/kyuubi/operation/tpcds/OutputSchemaTPCDSSuite.scala#L70

@pan3793 - Please let me know when you have a completed version of the TPC-DS suite in Kyuubi that works with Iceberg.

I'd love to be able to possibly run that sometimes. I have a version that I can run myself, but it's not very well developed. Your delta one looks decent, so I'd love to see it as an Iceberg implementation if that's what you're working on!

**Comment by pan3793** [comment]
> So the contract says that things should CASCADE by default. Which is why it's not exposed to Iceberg or other connectors.

Yea, that's my point.

> Appears we might have things working after all, for all catalogs!

I realized it when I looked through the codebase. 

> Please let me know when you have a completed version of the TPC-DS suite in Kyuubi that works with Iceberg.

The suite I show you only do a verification of TPC-DS query result schema. 

The most important role of Kyuubi is a gateway of Spark SQL, just like Spark Thrift Server, exposing Spark SQL as a HiveServer2 compatible Service. 

Basically, the suite creates all empty tables, then run all TPCDS query on the empty tables and verify the output schemas match the golden file, this process works well with iceberg. The error only occurs in the last step, clean up tables, when I switch the table format from delta to iceberg.
