### ISSUE TITLE
Should we support sort order during table creation SQL ?

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#3547]
In SQL create table syntax, when we create a table, should we support `sort order` in table properties?

I can see that only `ALTER TABLE ... WRITE ORDERED BY` is present and also we can sort files during `RewriteDataFiles`   

will it be good to have it in create table as well to avoid calling alter table ?

If yes, please assign this issue to me. I can work on it.

**Comment by hililiwei** [comment]
I have a question. If sort is supportted with  creation SQL, will it ensure the order of the whole table or only the current batch data? thank you.

**Comment by ajantha-bhat** [comment]
> I have a question. If sort is supportted with creation SQL, will it ensure the order of the whole table or only the current batch data? thank you.

It will act as a default sort order for the table. The insert's will use this sort order. However Iceberg also supports sort order evolution. So, when `ALTER TABLE ... WRITE ORDERED BY` it has to change table property also.  When sort oder is changed, it won't impact previous written data. Only new data will follow new sort order.

**Comment by ajantha-bhat** [comment]
@RussellSpitzer . @jackye1995 , @rdblue : Is it better to support sort order in the table properties (reserved property) and deprecate `ALTER TABLE ... WRITE ORDERED BY`?

So, that user can have sort order in the create table and one less custom SQL in Iceberg?

P.s: I am planning to parse the sort order using spark default parser like I did for rewrite_data_files procedure.

**Comment by rdblue** [comment]
No, I don't think so. These aren't table properties and we don't want to rely on hacks like in `rewrite_data_files`. If we want this in DDL, then Spark should support it.

**Comment by jackye1995** [comment]
> then Spark should support it

+1

It's definitely achieveable in CREATE TABLE DDL, but I don't think using TBLPROPERTIES is a good idea. The table version upgrade makes sense to use a special property because we want all users in all engines to easily upgrade their tables to a newer version, and table properties is the best way as it exists in all versions of the CREATE TABLE DDL.

For sort order, different engines have different ways to define that. For example, in Hive DDL, there is a clause `CLUSTERED BY (col_name, col_name, ...) [SORTED BY (col_name [ASC|DESC], ...)] INTO num_buckets BUCKETS` , so if we really want to define sort order in create table, we should implement clauses like this on the engine side. (I am not saying to use the Hive DDL syntax in Spark, we should propose a syntax that could fully support Iceberg sort order features when we do it)

**Comment by ajantha-bhat** [comment]
ok. Thanks for the clarifications. I will close this issue.

**Comment by maytasm** [comment]
A little late to the conversation but another case to think about is CREATE TABLE ... LIKE ...
i.e. 
`create table foo like bar`
where the table bar has both write.distribution-mode and sort-order set. This would create a table foo with only write.distribution-mode but no sort-order. This seems surprising / unexpected given that there is no error / warning message. I am also not sure sure how would be modify the CREATE TABLE ... LIKE ...DDL to make sure that sort-order from the source table is copied over. (Btw this is from Spark)

@ajantha-bhat @rdblue @jackye1995
