### ISSUE TITLE
Parquet: ParquetValueReaders#BytesReader processing bytebuffer will cause the data to be null

### ISSUE THREAD

**Issue by wulei0302** [apache/iceberg#3575]
Please help me look at this problem. When I use [ParquetValueReaders](https://github.com/apache/iceberg/blob/d6cbca0c2fb3d10083b304bcbdf16bf51e3b586b/parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java#L333****) to read binary and blob data that can be converted to betybuffer, I found that the first record can read the value normally, but from the second record, betybuffer field`s value is equal to null .
It looks like "reuse.limit(data.remaining());" should be changed to "reuse.limit(binary.length());"
The reason is that remaining is 0 after data.get()

![image](https://user-images.githubusercontent.com/52473940/142389859-3adfb744-b6de-4b56-987b-6df5d2d92a44.png)

Thanks Reply

**Comment by wulei0302** [comment]
Of course I can solve the problem without setting _reuseContainers_ ~~

**Comment by wulei0302** [comment]
@rdblue This seems to have a small bug, please assign me, thank you~

**Comment by wulei0302** [comment]
@RussellSpitzer  Hi, After my test, this seems to have a small bug, please assign me, thank you~

**Comment by rdblue** [comment]
@wulei0302, you don't need to be assigned to work on an issue. Feel free to open a pull request for it.

We avoid assigning issues because it prevents things from getting fixed more often than it helps people coordinate. It's not uncommon for someone to think they'll have time and never get to an issue and having it assigned deters other people from working on it (which is the point). And we almost never see people working on the same thing at the same time.

**Comment by wulei0302** [comment]
> 

Okay, thank you for your reply, I understand, I will open a PR directly

**Comment by rdblue** [comment]
Fixed in #3646.
