### ISSUE TITLE
Cannot use RewriteDataFiles on Hadoop Tables

### ISSUE THREAD

**Issue by shay1bz** [apache/iceberg#3731]
I'm trying to compact Hadoop-based table with Spark, but it fails internally while trying to load HiveCatalog instance.
This is easy to reproduce locally:
```
    val spark = SparkSession.builder().master("local")
      .config("spark.sql.autoBroadcastJoinThreshold", -1)
      .config("spark.sql.catalog.ice", "org.apache.iceberg.spark.SparkCatalog")
      .config("spark.sql.catalog.ice.type", "hadoop")
      .config("spark.sql.catalog.ice.warehouse", "/tmp/iceberg")
      .config("spark.sql.catalog.ice.default-catalog", "testDB")
      .getOrCreate()
    spark.range(10000).repartition(100).writeTo("ice.testDB.t1").using("iceberg").createOrReplace()
    spark.table("ice.testDB.t1").show()

+----+
|  id|
+----+
|6118|
  ...   
+----+


    val tables = new HadoopTables(spark.sparkContext.hadoopConfiguration)
    SparkActions.get(spark)
      .rewriteDataFiles(tables.load("/tmp/iceberg/testDB/t1"))
      .execute()

WARN BaseRewriteDataFilesSparkAction: 
Failure during rewrite process for group BaseRewriteDataFilesFileGroupInfo{globalIndex=1, partitionIndex=1, partition=PartitionData{}}
java.lang.IllegalArgumentException: 
Cannot initialize Catalog implementation org.apache.iceberg.hive.HiveCatalog: 
Cannot find constructor for interface org.apache.iceberg.catalog.Catalog
	Missing org.apache.iceberg.hive.HiveCatalog [java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/NoSuchObjectException]
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:176)
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:225)
```

It seems that `rewriteDataFiles` invokes a `spark.read` which in turn initializes the `default_iceberg` catalog:
https://github.com/apache/iceberg/blob/ded95a5435f18db9b6367e7aa4d1c666c77cfaed/spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java#L106-L110

Settings `spark.sql.catalog.default_iceberg.type=hadoop`, and basically all other `spark.sql.catalog.default_iceberg` parameters fix the problem.

Is that the right way to go? I'm asking because it wasn't documented and I'm concerned it might backfire.

**Comment by RussellSpitzer** [comment]
There are a few approaches here. The key code is that the Spark implementation of the rewrite strategy uses 

https://github.com/apache/iceberg/blob/551bda56db428037373efaae2bf8fc6e7b0be95a/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/Spark3BinPackStrategy.java#L64-L68

To read and write to the table, which assumes that the correct catalog identifier is included in the `name` of the table which has been passed to the action. We do this because we are using a Spark Reader and Writer to do the work here, so we need to know how to load the Table in a Spark context. When you pass in a table identifier that is loaded by an anonymous Iceberg catalog like ``` val tables = new HadoopTables(spark.sparkContext.hadoopConfiguration)``` it has to guess what the catalog name should be, and uses "default_catalog"

To fix this we have a few options:

1. Load the table via our helper method, here you can pass in the "catalog.database.name" of the Hadoop catalog https://github.com/apache/iceberg/blob/827b6c86108eec7b6de25f61022c7f8b5dda481c/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java#L628-L635
2.  As you showed above, setting the default-iceberg catalog up, this way any identifiers that don't have a catalog will be checked there. There is no problem with this
3. Load the table manually via Spark, basically doing *1.* on your own
    ```scala
     spark.sessionState.catalogManager.catalog("YourCatalogName").asInstanceOf[TableCatalog]
      .loadTable(tableName).asInstanceOf[org.apache.iceberg.spark.source.SparkTable]
      .table()
    ```

**Comment by shay1bz** [comment]
Thank you very much Russel, this explains a lot. 
As for option 1, this code does not seem to be released yet so I think I'll go manually like in option 3.
