### ISSUE TITLE
Class conflict in ORC benchmark

### ISSUE THREAD

**Issue by zhongyujiang** [apache/iceberg#4065]
I  ran [ORC data benchmark](https://github.com/zhongyujiang/iceberg/actions/runs/1812237626) (master & spark3.2) and got this error:

> Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (localhost executor driver): java.lang.NoSuchMethodError: 'org.apache.orc.storage.ql.exec.vector.VectorizedRowBatch org.apache.orc.TypeDescription.createRowBatch(int)'

Seems like class conflict, cause iceberg-orc uses orc-core-nohive and Spark uses orc-core.

**Comment by V-yg** [comment]
@zhongyujiang Did you solve that problem? I had the same problem

**Comment by zhongyujiang** [comment]
@V-yg No, I haven't.

**Comment by netanelm-upstream** [comment]
I have the same issue trying to write Iceberg ORC files using the JAVA API with hive metastore as a catalog.
Somehow, it uploads this class: org.apache.orc.storage.ql.exec.vector.VectorizedRowBatch (from hive-metastore-api)
Instead of this class: org.apache.orc.storage.ql.exec.vector.VectorizedRowBatch
Any suggestion how to solve it, will be very appreciated :)
