### ISSUE TITLE
Proposal: Support partition with transform for Flink SQL

### ISSUE THREAD

**Issue by yittg** [apache/iceberg#4251]
For now, only the `identity` partition transform is supported with flink SQL. To support other generic transforms, it is expected that Flink SQL supports defining partitions with transform. It depends on the support of Flink engine and the corresponding transformers. Here proposes another way to support partition with transform by composing the computed columns and partition list in flink.

The basic idea is that defining the partition field as a computed column in flink, with the mapping from the expression in Flink to the transform Iceberg (or vice versa), then use the column in partition list.

The only concern is how to map the expression from Flink to Iceberg. We can use user defined function (UDF) to resolve it.

> The built in functions in Flink may not be enough to cover all partition transform in Iceberg.

Iceberg can provide all corresponding UDFs for all partition transforms from catalog.

For creating table, if a computed column is used in partition list and can be mapped as a partition transform, then Iceberg will save it as a partition field with the following rule:

- the column name will be used as the partition field name;
  
- the parameter column name will be used as the source field name;
  

> other kinds of computed columns are still not supported.

For loading table, a partition field will be mapped as a computed column and one element in partition list with the following rule:

- the partition field name will be used as the column name;
  
- the transform will be mapped as a UDF function invoking expression for the column expression;
  
- the type of partition field will be mapped as the type of the column.

**Comment by kbendick** [comment]
Question wrt reading data:

Normal partition resolution rules will still apply, so nothing special wiill need to happen there from the users perspective?

If so, then something like https://github.com/apache/iceberg/issues/5000 is something I've been interested in for a long time.

Having to name the partition fields is possibly somewhat a pain though, as ideally users use the standard naming. However, there's no oblligation to use the standard naming (as partition fields can be renamed from their normal source + _ transform naming.

But because parttition fields can already be renamed, I think we can map them via the `PartitionSchema` and `PartitionField` itself (and not need the UDF). Maybe I'm mistaken though.

But is there a way we can do this without having to supply the given name? Is there a function catalog or something that can be applied in Flink SQL?

**Comment by kbendick** [comment]
I do overall think this feature is important.

Can you provide a user side example of your idea @yittg?  I want to make sure I understand it fully.

**Comment by yittg** [comment]
> Can you provide a user side example of your idea @yittg? I want to make sure I understand it fully.
This feature is not required for my personal scenario. In our platform, the metadata is not managed by Flink SQL, so I have no example about this though. 

This issue was primarily intended to initiate a discussion with some preliminary idea.

**Comment by hililiwei** [comment]
I think we've been stuck on FLink integrations such as compute columns for too long.
In Flink's flow calculation, the computed columns and so on is a rigid requirement.
I agree with @kbendick  that we should mention it at the next community meeting and form a design team to finish it as soon as possible.
Any progress is better than standing still.
So far, I've seen three or four different proposals. We should focus on them and then design a workable proposal and get it done.
Without this support, Flink streaming tasks simply don't work.
