### ISSUE TITLE
iceberg-flink-runtime 0.13.1 is not available 

### ISSUE THREAD

**Issue by sap1ens** [apache/iceberg#4299]
It appears that iceberg-flink-runtime 0.13.1 is not available in the [Apache repository](https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink-runtime/) even a few weeks after the release.

**Comment by openinx** [comment]
@sap1ens The correct link is here: https://repo.maven.apache.org/maven2/org/apache/iceberg/iceberg-flink-1.14/

Since iceberg 0.13.0,  we supported multiple flink versions in one iceberg branches. So we add the flink version suffix for the deployed artifacts.

I will close this issue,  feel free to reopen it if any further question.

**Comment by sap1ens** [comment]
Ah, got it! Thanks for explaining. I guess [this page](https://iceberg.apache.org/docs/latest/flink/) needs to be updated (it still uses the URL I shared).
