### ISSUE TITLE
Flink - Investigate migrating deprecated usage of `TableSchema` to new `Schema` and `ResolvedSchema` classes

### ISSUE THREAD

**Issue by kbendick** [apache/iceberg#4317]
Flink has deprecated the `TableSchema` class, which we still use in parts of the code base.

There are two classes which replace it, `Schema` and `ResolvedSchema`.

As I understand, `Schema` is used for declaring types etc and `ResolvedSchema` is what is used during program execution after passing through analysis etc. It has the watermark in it, so this would potentially make providing better support for watermarks easier.

Java Doc for deprecated `TableSchema`: https://nightlies.apache.org/flink/flink-docs-release-1.14/api/java/org/apache/flink/table/api/TableSchema.html

FLIP-164, which brought the new classes: https://cwiki.apache.org/confluence/display/FLINK/FLIP-164%3A+Improve+Schema+Handling+in+Catalogs

As the new classes were released in Flink 1.13, I'm not sure how much longer we'll be able to use the older classes.

There is a `toSchema` function which helps aide the transition. This also seems to give access to metadata columns etc that might be highly beneficial to us. It seems possible that we could even _possibly_ support partition transforms via the usage of `ComputedColumn`.

I'm still researching this as I've been looking into Flink 1.15 (which isn't out just yet)

cc @hililiwei if you have existing knowledge of this or are interested.

**Comment by hililiwei** [comment]
Hi,@kbendick, thank you so much for bringing it up and explaining it in detail.  

I do have a pr https://github.com/apache/iceberg/pull/4246 related to this. It is precisely our team that has started to deprecate the old API and gradually revamped the old tasks.

In that pr, an attempt has been made to use `ResolvedSchema` instead of `TableSchema`in internal framework processes, and added `ResolveSchema` APIs.

But for now, it seems we need more support for `Schema`, which is the recommended declaration in APIs, but in that pr, only exposes `resolveSchema` , not `Schema`. 

Hopefully this issuse will further clarify the requirements for our follow-up work. 

Thx.

**Comment by kbendick** [comment]
Cool. Thank you @hililiwei. I will take a look at this PR.

**Comment by yittg** [comment]
I'm also investigating migrating the deprecated usage to move more relative new features forward, and drafting some step changes for Catalog, Source, and Sink before knowing @hililiwei is working on this, :). I am happy to help review #4246 and the following change if needed.

And for partition transforms, i think computed column is the correct way. Actually i issued a proposal #4251 before, though it didn't get much response, haha.

**Comment by hililiwei** [comment]
@yittg Thank you for your feedback. Could you elaborate on what new features you would like to add? Maybe we can discuss it.

**Comment by yittg** [comment]
@hililiwei That would be great. For example, supporting of partition transforms.

Is this migrating on the way?

**Comment by HongHuangNeu** [comment]
How to convert ResolvedSchema to org.apache.flink.table.api.Schema? I am a bit confused.
