### ISSUE TITLE
Expose human-readable metrics in metadata tables

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#4362]
To improve Iceberg UX, we could expose iceberg Metrics as human-readable fields in metadata tables.

**Problem**

Currently there are the following fields in files_table:
```
  Types.NestedField COLUMN_SIZES = optional(108, "column_sizes", MapType.ofRequired(117, 118,
      IntegerType.get(), LongType.get()), "Map of column id to total size on disk");
  Types.NestedField VALUE_COUNTS = optional(109, "value_counts", MapType.ofRequired(119, 120,
      IntegerType.get(), LongType.get()), "Map of column id to total count, including null and NaN");
  Types.NestedField NULL_VALUE_COUNTS = optional(110, "null_value_counts", MapType.ofRequired(121, 122,
      IntegerType.get(), LongType.get()), "Map of column id to null value count");
  Types.NestedField NAN_VALUE_COUNTS = optional(137, "nan_value_counts", MapType.ofRequired(138, 139,
      IntegerType.get(), LongType.get()), "Map of column id to number of NaN values in the column");
  Types.NestedField LOWER_BOUNDS = optional(125, "lower_bounds", MapType.ofRequired(126, 127,
      IntegerType.get(), BinaryType.get()), "Map of column id to lower bound");
  Types.NestedField UPPER_BOUNDS = optional(128, "upper_bounds", MapType.ofRequired(129, 130,
      IntegerType.get(), BinaryType.get()), "Map of column id to upper bound");
```

but is hard to use:

- these are all maps requiring knowledge of the field-id.
- the value of bounds are not readable except if converted by ```Conversions.fromByteBuffer(type, value)```

**Options for Metadata Tables**

1. Change existing fields on "Files" table (is it possible to break backward-compatibility?)
If not:
2. New fields on "Files" table under a new struct:    ie files.resolved_metrics.upper_bounds

**Options for Field Types**

- A struct mirroring original table schema.  The leaf type on the metrics-struct would be either optional(long) for counts, or optional(column type) for bounds.  

eg, for a table with (col1 string, col2 struct<col3 string>), we could do:
```
select * from file.resolved_metrics.column_sizes.col1  //long type
select * from file.resolved_metrics.null_value_counts.col2.col3 //long type
select * from file.resolved_metrics.upper_bounds.col1 // string type
select * from file.resolved_metrics.lower_bounds.col2.col3 //string type
```

**Schema Resolution**

Choosing which schema used for resolving this information, given tables can change schema.  I think the easiest is just to use the current table schema.  If a column in current schema does not have any metric in that data file, can return null.

If user want to resolve file metrics for fields written with older schema, we can implement time-travel for the chosen metadata table, which would use the schema at that point to resolve the file written then.

**Comment by hililiwei** [comment]
This is a real problem in use, so we've even built a gadget that reads these values and converts them into a human-readable format. +1 for this issuse

**Comment by RussellSpitzer** [comment]
@szehon-ho as another option would it be to just change the output to JSON objects? So instead of map int -> buffer we do int-fieldid -> json representation?

**Comment by szehon-ho** [comment]
@RussellSpitzer do you mean like upper_bounds = Map (1 -> { "field-name": "id // or null if not in current schema", "value": "..." } ) ?  It's possible but why not just model as struct in this case for ease of sql?

**Comment by szehon-ho** [comment]
Synced with @RussellSpitzer , the proposal was  similar.

Question remains whether we want to change the existing field or not.  I'd prefer to keep existing as the map of field id -> binary may contain some information that the new field would not have (in case the field is removed in current schema), but i'm open. 

@rdblue @jackye1995 @aokolnychyi  fyi if you guys have any thoughts

**Comment by kbendick** [comment]
I support converting the values when retrieving them for display purposes. This is an issue that I think many people encounter and would be beneficial to support.

I would prefer to do it as a generated column from the metadata that users can select if they so choose. Something that is resolved at runtime. Or as an option to pass to the metadata table when querying it.

As for the stated options:

> New fields on "Files" table under a new struct: ie files.resolved_metrics.upper_bound.

My concern with actually storing an additional separate field is that the metrics themselves on very large tables can become quite a lot of data. I'm thinking of tables with possibly hundreds of columns, or tables with a very large number of files / partitions that require a lot of metadata to track.

Duplicating that on disk seems like it would cause headaches.

> Change existing fields on "Files" table (is it possible to break backward-compatibility?)

I don't like the idea of changing the spec to update the type of these values as stored.

There are now a lot of engines that support Iceberg, and growing all the time (see the recent Snowflake announcement, etc).

Some of these implementations are outside of our immediate awareness,  or are possibly closed source / inner sourced implementations as well. These people rely on Iceberg's specification to ensure compatibility. This would be a breaking change, mostly for display purposes / human interaction as far as I can tell. Though the primary value of the metrics is for engines to use for decision purposes at runtime.

If we change the actual data on disk, I have a feeling we'll likely have to consider both for a long time which would make the code substantially harder to reason about.

--------------
So **overall** +1 to doing something about displaying the metrics data properly for users to inspect, -0 to adding a new struct mirroring the original map in the table's metadata due to size concerns and the added difficulty this will bring for us, and -1 to the idea of changing the spec entirely.

**Comment by RussellSpitzer** [comment]
> > Change existing fields on "Files" table (is it possible to break backward-compatibility?)
> 
> I don't like the idea of changing the spec to update the type of these values as stored.
> 
> There are now a lot of engines that support Iceberg, and growing all the time (see the recent Snowflake announcement, etc).

My suggestion here was to change the metadata table view, not the underlying spec. Ie although the value in binary, it probably has little value to the SparkSQL user to read them in binary so we may want to change them to either strings or the actual types of those columns when we return the values

**Comment by rdblue** [comment]
What we did for the metadata tables in Trino was to produce structs, like @szehon-ho suggested. The idea is that you'd get a struct for each column name that contains value_count, null_count, upper_bound, lower_bound, etc. And each of those would have the correct data type.

I think that's generally the right direction. The main challenge is that in Spark we originally didn't have a good way to transform the maps into rows. But now we can do it using [`DataTask`](https://iceberg.apache.org/javadoc/latest/org/apache/iceberg/DataTask.html), which we use for similar transforms elsewhere.

**Comment by szehon-ho** [comment]
I'm still working on this (pr still under review)
