### ISSUE TITLE
[Feature Request] Iceberg integrates with Pulsar, supports java to read iceberg tables sequentially

### ISSUE THREAD

**Issue by hangc0276** [apache/iceberg#4621]
### Motivation
[Apache Pulsar](https://github.com/apache/pulsar) is doing integration with Iceberg, and take Iceberg as tiered storage to offload topic cold data into Iceberg. When consumers fetch cold data from topic, Pulsar broker will locate the target data is stored in Pulsar or not. If the target data stored in tiered storage (Iceberg), Pulsar broker will fetch data from Iceberg by Java API, and package them into Pulsar format and dispatch to consumer side.

For Pulsar Iceberg integration, we first use iceberg writer to streaming write topics messages into iceberg table in one thread.  And then we use iceberg reader to read records from iceberg table by streaming. In pulsar's read case, we should ensure the records read by the same order with the write. However, we found current Iceberg Java reader implementation doesn't support read records by order or doesn't support `order by ` operation on reading.

### What we need
- We need Iceberg to support read records out which keep the writer order, or support order by specific fields.
- We need to read the change log of the iceberg table by streaming.
- Does the Iceberg community has plan to support this feature?

**Comment by Reo-LEI** [comment]
I worked with Hang(@hangc0276 ) before to help Pulsar store cold data using Iceberg. As Hang mentioned above, Pulsar needs to read the data which are stored in Iceberg in the order of writting.

But because the Iceberg writer will split the data file according to the number of records and file size, and Iceberg reads the data concurrently according to the file granularity. This results in that even if the upstream distributes the records with the same key to the same writer and writes them in the order of events, the data cannot be guaranteed to be read in the order of writing when reading (for example, in a snapshot, writer-1 write the data to dataFile-1 and dataFile-2 in the order of events, and the events in dataFile-2 all occur later than those in dataFile-1. However, due to concurrent reading of records, the records in dataFile-2 may be read first than the records in dataFile-1).

Not only in this case of Pulsar, but also in Flink to implement stream reading of complete changlog(+I/-U/+U/-D), records need to be read in the order of writing. So I think it is necessary for Iceberg to support the ability to read records in the order they were written.

@rdblue @aokolnychyi @RussellSpitzer @kbendick @flyrain @jackye1995 @stevenzwu @openinx

**Comment by openinx** [comment]
> However, we found current Iceberg Java reader implementation doesn't support read records by order or doesn't support order by operation on reading.

It sounds like the pulsar reader hope the apache iceberg reader guarantee the record-level writing order semantic.  As far as I know,  the table format based on DFS files is hard to maintain the record-level  order semantic. Currently, the iceberg table format was optimized for batch analysis readers,  not for a message queue consumer.

I think @rdblue and @RussellSpitzer had discussed the approach about dual writing the iceberg table format and message queue, for downstream reader to consume the records with the writing order,  but I don't see a public discussion or design document to describe the details. Maybe they can provide more input about this issue.

**Comment by hangc0276** [comment]
> > However, we found current Iceberg Java reader implementation doesn't support read records by order or doesn't support order by operation on reading.
> 
> It sounds like the pulsar reader hope the apache iceberg reader guarantee the record-level writing order semantic. As far as I know, the table format based on DFS files is hard to maintain the record-level order semantic. Currently, the iceberg table format was optimized for batch analysis readers, not for a message queue consumer.
> 
> I think @rdblue and @RussellSpitzer had discussed the approach about dual writing the iceberg table format and message queue, for downstream reader to consume the records with the writing order, but I don't see a public discussion or design document to describe the details. Maybe they can provide more input about this issue.

@openinx  Thanks for your quick reply. Looking forward Iceberg community to discuss and support this feature.

**Comment by flyrain** [comment]
In terms of order granularity, here are 3 of them
1. snapshot level, it is there already.
2. file level, not in the current table spec. I assume it is what you want for this feature request, please confirm.
3. row level, not in the current table spec, I'm not even sure it is something worth to pursue.

We can discuss it in the community sync. Feel free to add it to the agenda. I’d suggest a proposal for this before that. It may present a rough idea, or multiple ideas. It may address some concerns like how it work with the current data file compaction. A data file compaction may break the order between multiple data files.

**Comment by RussellSpitzer** [comment]
As @openinx says, Iceberg doesn't inherently have an ordering in its generic readers since these are not meant to be a full featured reader. In general, most engines like Spark or Trino are implementing that sort of sorting and ordering because in a generic case such ordering requires a full shuffling of the records as written. While you could write a table with a column that specified the insert ordering, reading with that ordering would be the responsibility of the reading implementation. 

For a specific table only written and read by pulsar you could probably guarantee a certain ordering for all reading but this wouldn't be possible for a generic table. A generic Iceberg table only sees ordering at a snapshot level as @flyrain stated and within that snapshot all rows are considered to have come into existence at the same point in time.

**Comment by rdblue** [comment]
You should be able to reconstruct an order, but I'm not sure whether you'd consider it the _same_ order or even if there is an _original_ record/row order.

Most systems that work with Iceberg don't have an order because they process data in parallel tasks. Each task has a record order, but there's no order between tasks. For example, when Flink processes data from a Kafka topic, there is order within each Kafka partition, but no order across partitions or really across Flink tasks. Does Pulsar have a concept of total order over rows?

I said above that you can reconstruct an order. That's because Iceberg keeps writes in order. For a given append operation, Iceberg writes the data file metadata into a manifest file in the original order. So all you need to do is read snapshots sequentially, order data files sequentially, and then read records from data files sequentially. We could formalize that a bit so that we can keep track of file order within a commit, but I'm skeptical that it is valuable given that most systems rely on partial ordering and not total ordering.

**Comment by hangc0276** [comment]
> You should be able to reconstruct an order, but I'm not sure whether you'd consider it the _same_ order or even if there is an _original_ record/row order.
> 
> Most systems that work with Iceberg don't have an order because they process data in parallel tasks. Each task has a record order, but there's no order between tasks. For example, when Flink processes data from a Kafka topic, there is order within each Kafka partition, but no order across partitions or really across Flink tasks. Does Pulsar have a concept of total order over rows?
> 
> I said above that you can reconstruct an order. That's because Iceberg keeps writes in order. For a given append operation, Iceberg writes the data file metadata into a manifest file in the original order. So all you need to do is read snapshots sequentially, order data files sequentially, and then read records from data files sequentially. We could formalize that a bit so that we can keep track of file order within a commit, but I'm skeptical that it is valuable given that most systems rely on partial ordering and not total ordering.

@rdblue @RussellSpitzer @flyrain Thank you for your patient reply.

For Pulsar, we only need partial ordering instead of total ordering. Let me explain how we integrate Pulsar topic with Iceberg.

We will write one topic's messages into one iceberg table. For a Pulsar topic, it has many partitions, and for each partition, we will create an iceberg writer to deal with message writing. For one message, it will be fetched from one topic partition and then written into iceberg table with additional metadata fields, such as <partitionId, ledgerId, entryId> (<ledgerId, entryId> used to specify one message named `MessageId`). For messages from different topic partition, the additional metadata fields `partitionId` will be different, and we won't care about the message order between different topic partitions. 

For messages from the same topic partition, they will be written into iceberg table as the same order they stored in topic partition. The metadata fields <ledgerId, entryId> for messages will be strictly increasing. Such as [<1, 0>, <1, 1>, <1, 2>, <2, 0>, <2, 1>, <3, 0>, <3, 1>]. 

We will read records from iceberg table by specify `partitionId` and `MessageId` range. For example, we specify partitionId 0 and messageId range [<1, 0>, <10, 20>].  The iceberg reader need to return the records with MessageId strictly increasing order.

The reader need to support partial key pair order for the returned records, otherwise, it's hard for Pulsar to reorder the records returned from Iceberg reader. Pulsar can keep writes order in partition.

For Iceberg writer, it will write records sequentially into multiple parquet files. For Iceberg reader, we will specify partitionId and MessageId range to read, it can keep the record order in one parquet file, but it's hard to keep order between multiple parquet files.

**Comment by rdblue** [comment]
@hangc0276 if you're guaranteeing that each partition is written by only one writer (which I think is given) then you should be able to accomplish this already because you process records in order within a partition to the file, then when you read they have the same order.

The challenge is what to do when a partition is split across multiple files within a snapshot, right? The easy solution is not to split partitions across files, but you could also look at file metadata to see which one has the lowest `ledgerId, entryId` pair.

I think you should be able to do this without much trouble.

**Comment by hangc0276** [comment]
@rdblue  Great! Thank you very much for your great idea. I will try it as your suggestion.
My only one concern is whether the single writer can cover the performance requirements.  Anyway, I will use the current single writer to implement it in the first step. If it has performance trouble, I will try to improve it in the next step.

Thank you very much again.
