### ISSUE TITLE
Migrate back to use ReusableArrayData in Flink

### ISSUE THREAD

**Issue by yittg** [apache/iceberg#4624]
In #4432 (1.14), #4521 (1.13), we add fixes to walk around the Flink issue [FLINK-25238](https://issues.apache.org/jira/browse/FLINK-25238).

Now it has been fixed in Flink, and we can migrate back to use ReusableArrayData after the fixes being released (1.14.5+, 1.15.0+).
It will not be fixed in 1.13.

Create this issue to track it.

* [ ] Flink 1.14
* [x] #4712

**Comment by kbendick** [comment]
Note that we should strongly consider whether or not to backport this to Flink 1.14.

If the fix was applied in Flink 1.14.5, and users use Flink 1.14.2 at runtime, they’ll likely encounter an issue.

If this is super performance critical, we can consider adding a flag or something to opt-in for Flink 1.14, but it seems the patch fix has somewhat broken API comparability for Flink 1.14.x.

shameless plug for my PR that would add binary / semantic / API compatibility checks, at least to the API module: https://github.com/apache/iceberg/pull/4638

also, if you’re ever curious, you can apply that plug-in to `allsubprojects` to see if that catches the issue after changing it. I suspect it would (though generally speaking we only intend on defining binary / source / semantic compatibility guarantees for the api module).

**Comment by yittg** [comment]
Thanks @kbendick . Totally agree with you about whether and how to backport it to Flink 1.14. We can provide a property for user to choose the prefer action if it is strongly required.

**Comment by kbendick** [comment]
Hi @yittg! Are you still planning on trying to get this into 1.14?

I personally think it's dangerous to do, and that we should avoid it. It would only work for the newest versions(s) of Flink 1.14, and we don't have control over which version is in use. We also don't run tests across different patch releases of any framework.

If you're not, please close this issue. If you would like to patch this into 1.14 conditionally, we'll have to see what other people think as this change could only be applied to Flink versions 1.14.5+ and I don't believe there is any existing precedence for code being changed at the patch level (just the minor version level).

Let us know what you think!

**Comment by yittg** [comment]
@kbendick Thanks for reminding, i'll close this issue directly.
