### ISSUE TITLE
spark api can not read iceberg data which using hive_catalog

### ISSUE THREAD

**Issue by lichaohao** [apache/iceberg#4659]
flink (use hive_catalog) write data into iceberg table, spark api(scala) can not read iceberg data
flink: 1.13
iceberg:0.13.2
spark:3.2
hive:3.1.2
such as: spark.read.format("iceberg").load("/warehouse/tablespace/external/hive/iceberg.db/my_iceberg_test").show()

spark api can not read iceberg data which using hive_catalog

exception message:
caused by: File does not exist: /warehouse/tablespace/external/hive/iceberg.db/my_iceberg_test/metadata/version-hint.text

i check the hdfs path ,hdfs actually does not exist version-hint.text if write data by hive_catalog  ,but it exists if using hadoop_catalog.
i think spark api wants to get the latest schema,datalist by version-hint.text .
maybe spark api should support this situation if using hive_catalog write data into iceberg table ,spark api can get  the latest schema,datalist by hive TBLProperties

this bug can be fixed in next version (iceberg-spark-runtime ) ?

**Comment by lichaohao** [comment]
flink (use hive_catalog) write data into iceberg table, spark api(scala) can not read iceberg data
flink: 1.13
iceberg:0.13.2
spark:3.2
hive:3.1.2
such as: spark.read.format("iceberg").load("/warehouse/tablespace/external/hive/iceberg.db/my_iceberg_test").show()

spark api can not read iceberg data which using hive_catalog

exception message:
caused by: File does not exist: /warehouse/tablespace/external/hive/iceberg.db/my_iceberg_test/metadata/version-hint.text

i check the hdfs path ,hdfs actually does not exist version-hint.text if write data by hive_catalog  ,but it exists if using hadoop_catalog.
i think spark api wants to get the latest schema,datalist by version-hint.text .
maybe spark api should support this situation if using hive_catalog write data into iceberg table ,spark api can get  the latest schema,datalist by hive TBLProperties

this bug can be fixed in next version (iceberg-spark-runtime ) ?

**Comment by RussellSpitzer** [comment]
This is not quite correct. The issue here is that you are specifying a file path instead of a table identifier. When you use a file path to load a table in Spark, Iceberg assumes that the data is using a `Hadoop Catalog` because a Hive Catalog Table cannot be read from path alone. A Hive Catalog Table needs to know the specific metadata.json file to load.

To load the table correctly, if your Metastore is correctly configured. You setup the Catalog API as specified in the docs https://iceberg.apache.org/docs/latest/getting-started/#adding-catalogs and then you can access your table with
`spark.table("catalog.namespace.table")` or `spark.read.format("iceberg").load("catalog.namespace.table")`

**Comment by lichaohao** [comment]
thanks a lot. i should add the hive_catolog name before the db
