### ISSUE TITLE
spark action expireSnapshots and removeOrphanFiles block in spark local mode

### ISSUE THREAD

**Issue by flashJd** [apache/iceberg#4900]
Issue #4471 has  reported this. I will add extra detail info.
precondition:
1 ./bin/spark-submit  --class jobs.DeleteOrphanFilesJob  --master spark://ubuntu:7077 
spark standalone mode works successfully
 ./bin/spark-submit  --class jobs.DeleteOrphanFilesJob  --master local[*]
spark local mode block at last task of collectAsList operator
2. use custom hiveConfig will also cause it when run TestRemoveOrphanFilesAction3
![image](https://user-images.githubusercontent.com/23452216/170955399-60237424-548c-4ae0-b6d9-d408b50c5340.png)

phenomenon:
the action blocked in collectAsList and deeper stack: events.take() in spark-sql which call Condition.await()，so it is blocked here
![image](https://user-images.githubusercontent.com/23452216/170958006-8365f713-7f6f-46a5-9ae0-a5200a9e7c53.png)

So any suggestion why spark is blocked here and how we can solve it.

**Comment by amogh-jahagirdar** [comment]
I think is expected as @RussellSpitzer mentioned in https://github.com/apache/iceberg/issues/4471#issuecomment-1086660475. The spark procedure has to wait until the computation of the files to actually be deleted. Currently, the results of that computation is collected to the spark driver, and deletion of the files occurs on the driver. Even if the procedure did a distributed deletion of files (not currently done due to concerns of more easily hitting rate limiting from the underlying FS), the procedure needs to first compute the files to be deleted. So if that's the bottleneck in the collectAsList, then that's expected.

**Comment by flashJd** [comment]
It seems not like a performance bottleneck but a completely stuck

**Comment by RussellSpitzer** [comment]
Did you check a thread dump? What makes you think it is stuck?

**Comment by melin** [comment]
[jstack.log](https://github.com/apache/iceberg/files/8820521/jstack.log)
![image](https://user-images.githubusercontent.com/1145830/171548014-c88008c6-7904-449f-ba06-a031d6f6e103.png)
@RussellSpitzer

**Comment by RussellSpitzer** [comment]
Inside the broadcast exchange thread also seems to be waiting, I'd check out the stage view, is that a single final task we are waiting for? Or another stage. In the dump I didn't see any executor threads running anything but I didn't look that close. 

I would also just try disabling 
1. Adaptive query planning
2. Broadcast joins

Could be that to broadcast is just not completing due to memory pressure, but nothing in that dump looks iceberg specific to me. Just lots of Spark internals waiting on other spark internals

**Comment by eric666666** [comment]
I fixed this problem. You can see issue #4471
