### ISSUE TITLE
Proposal: Rename Python library to `pyiceberg` and remove `src` level in directory

### ISSUE THREAD

**Issue by samredai** [apache/iceberg#4933]
Since `iceberg` is reserved on PyPi, we need to decide on a different name to publish under. The open PR #[4844](https://github.com/apache/iceberg/pull/4844/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R19) currently uses `apache-iceberg`.

I'd like to propose that we use `pyiceberg` and also rename the library to match that name. I think it's important that the import matches the namespace on pypi. I think it's safe to say that many people will reflexively `pip install iceberg` if they see code snippets using `import iceberg`. Among other things, this is a security risk since they'll be accidentally (and somewhat reasonably) installing a different library.

Additionally, I feel that the `src/iceberg` directory is not very pythonic. It seems much more common that python libraries have a root directory named after the library, without a encapsulating `src` directory. I propose we replace `python/src/iceberg` with a single directory `python/pyiceberg` that contains the source code.

**Comment by dramaticlly** [comment]
I agree with proposed above, especially around how we organize the project directory structure. I think `src/iceberg` should go away, and it would be awesome if we can import the same namespace as module name. However I do observe some other apache project such as airflow have module named to `apache-airflow` and import namespace to `airflow`. But we have the potential complication of legacy-iceberg project as well as already reserved iceberg middleware project on pypi already https://pypi.org/search/?q=iceberg, so +1 on `pyiceberg`

**Comment by jun-he** [comment]
@samredai  there was a discussion at the beginning of python refactoring related to the names: https://docs.google.com/document/d/1oMKodaZJrOJjPfc8PDVAoTdl02eGQKHlhwuggiw7s9U/edit#bookmark=id.halmhixpma4k. `py-iceberg` was voted to be the name to be used for pypi.

**Comment by Fokko** [comment]
Hey @samredai Thank you for bringing this up.

I fully agree. I went for `apache-iceberg` in the PR #[4844](https://github.com/apache/iceberg/pull/4844/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R19), but that wasn't intentional. I got that from `apache-airflow` on which I also did a lot of work. @jun-he thanks for pointing out the vote, I was unaware of it. Since there weren't any releases (yet), I figured it was TBD.

I also think that `pyiceberg` is a great pypi package name as it matches the internal name. This will prevent a lot of confusion, and frustration in the end. It also nicely aligns with `pyarrow` and `pyspark`.

With respect to dropping the `src`; a big `+1` from my side. It doesn't add any value in my opinion. It will simplify some things such as being able to import the source without having to install it. Also, I had to explicitly tell this to poetry, since it defaults to non-src projects: https://github.com/apache/iceberg/pull/4844/files#diff-1a45bd938160f7761769e7b6fbc819d1cc7f84ce37f1a6a23ef83cc4e214abc8R36-R38

**Comment by samredai** [comment]
@dramaticlly , @jun-he , @Fokko , thanks for the input! I've added this as a topic to the [python community sync doc](https://docs.google.com/document/d/1oMKodaZJrOJjPfc8PDVAoTdl02eGQKHlhwuggiw7s9U/edit). If nobody raises any issues there, I'll go ahead and open a PR for this.

**Comment by samredai** [comment]
Closing now that PR #5169 was merged.
