### ISSUE TITLE
Failed to delete data from iceberg data table

### ISSUE THREAD

**Issue by jiaowolaowang** [apache/iceberg#5023]
I use sparksql to delete data in iceberg. Data can be queried through the following conditions, but cannot be deleted using the same conditions.
![1655120730546](https://user-images.githubusercontent.com/49644985/173346724-111ce0a8-a658-41f7-8034-0d1e0dc375e2.jpg)
The jar packages I refer to are as follows
![1655121417173](https://user-images.githubusercontent.com/49644985/173348506-07105cbf-9882-4ca6-b68b-ede7e3543177.jpg)

The log information is as follows
![1655120836314](https://user-images.githubusercontent.com/49644985/173347002-ee140467-704e-4d75-ba1f-253511ddac90.jpg)

It seems that the data to be deleted is not queried. But some data can be deleted correctly.

**Comment by kbendick** [comment]
First, you don’t need to include both `iceberg-core` and `iceberg-spark-runtime-3.2_2.12`. For Iceberg, the “Spark runtime” jar is the only dependency required (though you nigh need some non-Iceberg dependencies, such as AWS s3 Java SDK v2 to use S3FileIO). But `iceberg-core` is already included in the Spark runtime jar.

Second, can you please provide the full output of `desc extended <tbl>`? I’m wondering if one of the columns has maybe been dropped, and so the query filter is being simplified to false because a non-null value is being provided.

In any case, the `desc extended <tbl>` output, as well as the full logs from the deletion, would be beneficial.

It’s also possible that one of the columns you marked is a partition column or something and that value isn’t present. Just a couple guesses, but the full logs as well as the `desc extended <tbl>` output would help a lot in debugging.

Additionally, querying the current snapshot with that same filter to see if any data is returned (eg `select count(*) from tbl where <that deletion where clause>`) would also be beneficial in debugging.
