### ISSUE TITLE
Support catalog method to set table metadata

### ISSUE THREAD

**Issue by szehon-ho** [apache/iceberg#5163]
**Background**: 

#3851 and further prs added support to register a new table in catalog pointing to existing metadata.json.  It may be good to support setting an existing table in catalog to another metadata.json.

**Justification**:  

There have been instances in the past where such a method would have been welcome, the workaround unfortunately is to manually update the catalog (ie, update Hive Metastore directly), or even drop and recreate.

1. Disaster recovery from outdated catalog backup with a table pointing to an older metadata.json
2. Bugs where table becomes in a bad state due to bad metadata modification (in particular, partition field dropping bugs that made the table impossible to query):
a.  https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1654877950329549 (just one instance of trying to help user)
b.  https://github.com/trinodb/trino/issues/8284
c.  https://github.com/apache/iceberg/pull/3411
d.  https://github.com/apache/iceberg/pull/4560
4. Catalog consistency problems where metadata.jsons get overriden from each other:
a.  #5036
b.  some problems in custom catalog impelementations

**Ideas:**

1. Add a force option to catalog::registerTable 
2. Add a different method to catalog (reset table?)

**Concerns:**

This could of course be dangerous, but metadata.json does seem a user-exposed concept already in catalog API and in some utils.  User can achieve this today by dropping table with purge=false, and registering the metadata.json to new table with same name.

We could potentially run some kind of table consistency check (explore all the reachable graph and even historic metadata graph to validate that the new table metadata is consistent).  This could be another utility that could be just generally useful.

**Comment by RussellSpitzer** [comment]
Here is the other register PR, I forget where we were discussing the "force" issue https://github.com/apache/iceberg/pull/4810

**Comment by flyrain** [comment]
@RussellSpitzer and me had a discussion around #4810 if we want to "update" a table with a metadata.json. 

+1 for this idea. I happened to resolve a table corruption case caused by catalog inconsistency. I had to update the table's metadata.json location manually at that time. A force register or update/reset tool will be pretty helpful in that case.

**Comment by yabola** [comment]
@szehon-ho @RussellSpitzer 
I also have a strong need to call register table on the same table to update meta location.
My background:
We write using hadoop catalog, but need to read from hive catalog for special reasons (for example, we need to create a hive view to read table, hadoop catalog can't create hive view). Hive is read only here.
But in order to update the metadata, we need to update the meta location information regularly.

I took a rough look at the current implementation. I think if the register table is to implement the update mechanism, it is better not to call the `BaseMetastoreTableOperations#commit` method here. Because register table is similar to the mirror reading of the table, there should be no modification operation, but there is modification in the commit method.

I would like to complete this update function if possible. Thanks!

**Comment by flyrain** [comment]
@yabola, we can still reuse the method `registerTable`.  For your concern about `doCommit` changing the metadata, it won't happen in the method `registerTable` since we explicitly set the base to null, so that `doCommit` won't write a new metadata, check the details here.
https://github.com/apache/iceberg/blob/08c8764b40fac06836d32d4d886b9f43962c8ee6/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L218

**Comment by yabola** [comment]
@flyrain Yes, the existing `registerTable` logic does not modify. The check for METADATA_LOCATION in the `doCommit` method needs to be modified. For example：
https://github.com/apache/iceberg/blob/master/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L239

**Comment by szehon-ho** [comment]
@yabola yep that would be great if you want to take a stab!  I haven't looked at the details yet, so @flyrain may help on that.  I was initially thinking it may be cleaner to use a new function, but if it's easier to re-use registerTable than that may be ok too. 

On the user-facing side, I was just thinking to add an error check (that may be overriden), that either the new metadata passed in is in the previousFiles() of the old one, or vice-versa.

**Comment by RussellSpitzer** [comment]
I am kind of in favor of it just being a "force" option on registerTable, since we are in the realm of dangerous operations anyway may as well?

**Comment by pvary** [comment]
> We write using hadoop catalog, but need to read from hive catalog for special reasons (for example, we need to create a hive view to read table, hadoop catalog can't create hive view).

@yabola: It is possible to create Hive external tables where the Catalog is HadoopCatalog. So you can store your Iceberg tables in your desired Iceberg Catalog, and you still can query them from Hive, in the same way as any other table.
See: https://iceberg.apache.org/docs/latest/hive/#catalog-management

Would this help in your use case?

That said, I still agree with the goal for this issue, but I think we should try to avoid cases where an Iceberg table is registered to multiple Iceberg catalogs.

**Comment by yabola** [comment]
@pvary Thanks for your advice. Yes, I can manually create the hive external table, and set the inputFormat to `HiveIcebergInputFormat` and other table properties, hive can access the data.
But it seems the `registerTable` command (by seting `iceberg.engine.hive.enabled`)seems to be more convenient and stable (it is same as manual creation essentially). 
I will create a PR recently for a "force" option on `registerTable`.

**Comment by pvary** [comment]
Happy to help @yabola! Hive 1.1.0 is really old. 2.3.x, and 3.1.x is supported in some configurations, but if you are able to upgrade Hive 4.0.0-alpha-1 would be your best bet to query Iceberg tables
