### ISSUE TITLE
Rewritedatafiles is not work with total-delete-files on Spark 3.2.1, Scala 2.12, Iceberg 0.14.0

### ISSUE THREAD

**Issue by cbwn123** [apache/iceberg#5216]
This is snapshot in metadata file which is create by rewrite data files action and rewrite manifests action. 
 {
    "sequence-number" : 479,
    "snapshot-id" : 7678743334037913715,
    "parent-snapshot-id" : 704591498781525614,
    "timestamp-ms" : 1657152639626,
    "summary" : {
      "operation" : "replace",
      "manifests-created" : "1",
      "manifests-kept" : "0",
      "manifests-replaced" : "3",
      "entries-processed" : "0",
      "changed-partition-count" : "0",
      "total-records" : "190361791",
      "total-files-size" : "11035003231",
      "total-data-files" : "56",
      "total-delete-files" : "24356",
      "total-position-deletes" : "226070",
      "total-equality-deletes" : "0"
}

The total-data-files number fell sharply，but total-delete-files not.

Why not the rewritedatafiles action merge data file and delete file?

**Comment by RussellSpitzer** [comment]
It does merge data and delete files. Unfortunately the logic for cleaning up delete files is more complicated and we haven't set that up quite yet. The main issue being that just because a delete file is applied to 1 data file doesn't mean it was applied to all relevant data files. Currently the way we do the processing doesn't let us know if a delete file has been completely or only partially merged. There are various efforts going forward to clean this up at the moment.

**Comment by Initial-neko** [comment]
@RussellSpitzer mean that this statistical total-delete-files item is not accurate yet, but the query efficiency will not be affected after action done
