### ISSUE TITLE
The metadata file is too large

### ISSUE THREAD

**Issue by lintingbin2009** [apache/iceberg#5219]
We have a table with thousands of columns. Every time a column is added, all the old columns will be retained in the schemas field of the metadata, and will not be deleted again. In this way, after hundreds of column addition operations, the metadata will have a size of several hundred MB.
Is there any way to clean up the schemas field. Does the metadata need to save all the historical schemas if it is just adding columns?

**Comment by RussellSpitzer** [comment]
I actually wrote something for cleaning up Partition Specs because of a slightly related issue.

https://github.com/apache/iceberg/pull/3462

But we could always extend this to schema's as well. Basically just a "cleanMetadata" function.

**Comment by lintingbin2009** [comment]
@RussellSpitzer This sounds like a good idea. However, the iceberg community staff did not express any of their opinions, so your code has not been merged into master.

**Comment by RussellSpitzer** [comment]
Yes as I noted, this was something we used internally and I didn't push for it to be merged here because I wasn't sure there was any utility. This also would not cover your specific issue but provides a template for what could be a solution. As for community interest, I'm sure we could get something like this in if it is not solely for fixing our internal issues.
