### ISSUE TITLE
Iceberg tables should optionally allow for automatic schema evolution

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#540]
Related to #244 .  We should allow for automatic schema evolution when writing to an Iceberg table. This feature should be controlled by a flag, since it may not always be desirable to automatically evolve a table's schema .

Today I don't think we throw a good error message when the schema being written to a table is evolved. If we decide to control the schema evolution as an optional feature, we should also provide a good error message when the table has disabled automatic schema evolution.

@rdblue, @fbocse  thoughts?

**Comment by rdblue** [comment]
What do you mean by automatic schema evolution? When you write to a table, any new columns are automatically added?

**Comment by rdsr** [comment]
Yes, if the columns are valid as per the schema evolution rules
We've seen use-cases of it where users want their jobs to automatically evolve their private tables when the upstream datasets evolve.

**Comment by rdblue** [comment]
Yeah, I think that could be a good idea. We'd want to document some of the risks, though. It's easy to add columns with the wrong type when you're doing that.

**Comment by rdsr** [comment]
> It's easy to add columns with the wrong type when you're doing that.

Wouldn't `UpdateSchema` catch invalid schema evolutions?

**Comment by rdblue** [comment]
Yes, it will. But we would want to fail earlier than that. The case I'm thinking about is when you're developing a change that adds a column and everything looks fine in the data, so you deploy it. But what if you accidentally used a string instead of an int? You'll quickly catch that when people start using the new column, but you won't be able to simply update the type and write because string to int is an incompatible change.

**Comment by geota** [comment]
Databricks recently released support for automatic schema evolution in merge operations:
https://databricks.com/blog/2020/05/19/schema-evolution-in-merge-operations-and-operational-metrics-in-delta-lake.html

**Comment by rdblue** [comment]
@geota, in Spark, "automatic schema evolution" usually means not validating the schema on write and merging schemas together on read to find what the table schema actually is. This is how the v1 DataFrame APIs work. Calling it "automatic" makes it sound more like a feature and less like a bug.

That said, I think it's fine to add this to Iceberg as a real feature -- where we detect the changes and apply them to the table schema. It just shouldn't be the default behavior because it can easily cause problems. Most of the use cases are covered by replace-table-as-select anyway.

**Comment by tabdulradi** [comment]
@rdblue This issue can now be closed as it's implemented via https://github.com/apache/iceberg/pull/4154, right?

**Comment by rdblue** [comment]
Fixed by #4154.
