### ISSUE TITLE
Iceberg Table properties not replaced when DataFrameWriterV2 replace() is used

### ISSUE THREAD

**Issue by swapna267** [apache/iceberg#5832]
Based on Replace() documentation , Table properties should be replaced with the one's associated with the data frame. 

"The existing table's schema, partition layout, properties, and other configuration will be replaced with the contents of the data frame and the configuration set on this writer."
https://spark.apache.org/docs/3.2.0/api/java/org/apache/spark/sql/DataFrameWriterV2.html#replace--

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableMetadata.java#L655
For iceberg tables, the current behavior is that table properties are getting updated , but not replaced. Is this the expected behavior ?

**Comment by karuppayya** [comment]
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableMetadata.java#L655
Is there any specific reason for updating it than replacing it?
@rdblue @aokolnychyi @RussellSpitzer @flyrain @szehon-ho

**Comment by flyrain** [comment]
Not aware of the reason of the original decision, but replacing makes more sense to me.

**Comment by rdblue** [comment]
The new properties should be merged, not replaced. There are many properties that should live with the table across versions. For instance, the compression codec is based on the data in the table and should not be dropped because the operation replacing the table's data doesn't specify one. Instead, properties should be respected by always merged with the existing ones.
