### ISSUE TITLE
What is the expected behavior of expireOlderThan for a table with a tag that has not reached max age?

### ISSUE THREAD

**Issue by barronw** [apache/iceberg#6018]
### Question

Is `expireOlderThan` expected to fail when there is at least 1 tag that has not reached max age? 

I get "cannot incrementally clean files for table with more than 1 ref" when I try to run `expireOlderThan` on a table with a tag that has not reached max age.

**Comment by amogh-jahagirdar** [comment]
> Is expireOlderThan expected to fail when there is at least 1 tag that has not reached max age?

This was the case previously, but this will be fixed in the 1.1 release. The [procedure needed to be updated](https://github.com/apache/iceberg/pull/5669) to do a full file reachability analysis in the presence of multiple branches and tags to determine which files are safely removed. The change for the updated procedure is merged in master if you needed it to get unblocked.
