### ISSUE TITLE
[Python] The structure of a partition definition and partition instance should be consistent

### ISSUE THREAD

**Issue by ddrinka** [apache/iceberg#6120]
### Feature Request / Improvement

Consider the `PartitionSummary` in a `ManifestFile`.  The lower and upper bounds can be resolved with `conversions.from_bytes`, resulting in types according to the definitions in `conversions.py`.  For instance, a date of 2022-04-01 results in a `long(19083)`.

Now consider `ManifestEntry.data_file.partition`.  The instance of a partition definition should resolve into the same datatypes as the `PartitionSummary`.  But here, since the Avro reader is used, the date above is resolved to `date(2022, 04, 01)`.

I like the work being done in `expressions/literals.py`.  For matching up partitions of different datatypes, I'm testing out converting the partition values to literals.  A workaround to the disconnect above would be to allow `DateLiteral`s to be created directly from `date`s.

#### literals.py
```python
@literal.register(date)
def _(value: date) -> Literal[int]:
    # We should not convert to and from a string here but I'm trying to reduce the surface area of this example code
    return DateLiteral(date_to_days(value.isoformat()))
```

With this change in place I can create a `Literal` from both resulting representations of a date above and check equality and gt/lt.

**Comment by Fokko** [comment]
Hey @ddrinka Thanks for opening the PR. The date is a so-called logical type that most storage formats store internally as the days since 1970-01-01. After reading, this should be converted into a date again. For the PartitionSummary, we convert it into the physical type (int) and compare it with the partition.

It seems that the `DateLiteral` is missing here: https://github.com/apache/iceberg/blob/master/python/pyiceberg/expressions/literals.py#L108-L164 It would be great if you can open up a PR to fix this 👍🏻

**Comment by ddrinka** [comment]
Ok @Fokko, check out the PR and let me know what you think.

I think there's still room for improvement on aligning the handling of partitions between `PartitionSummary` and `DataFile.partition` so I propose leaving this feature request open, but having the ability to use Literals to convert between will let me keep toying with this.
