### ISSUE TITLE
Add ignoreDuplicates option for add_files procedure

### ISSUE THREAD

**Issue by reh183** [apache/iceberg#6306]
### Feature Request / Improvement

When we use the add_files procedure we would like to pass in a directory which contains some files which have already been added and some new files. We would like the procedure to add the new files to the table and ignore the ones that have already been added.

I believe this was mentioned here on this issue https://github.com/apache/iceberg/issues/2735#issuecomment-867840947. What got implemented in https://github.com/apache/iceberg/pull/2779 was a checkDuplicateFiles flag which controls whether or not to error out if any duplicate files are present.

cc @szehon-ho @RussellSpitzer 

### Query engine

Spark

**Comment by bohdan-pd** [comment]
Also would like use procedure like that cc @RussellSpitzer

**Comment by sweetpythoncode** [comment]
Also would like to use procedure like this @RussellSpitzer

**Comment by szehon-ho** [comment]
Yea at the time, I didn't see a huge use case where a folder has some files already added but not all.  Curious, if you can share the use case.

Yea the problem with things like this is once its implemented, its a bit hard to change.  

I guess if we start over, we could have an argument like 'duplicate_file_mode' which would take option 'allow', 'error', 'skip'.  and we would probably deprecate 'check_duplicate'.  Not sure what @RussellSpitzer thinks.

**Comment by sweetpythoncode** [comment]
@szehon-ho(cc @RussellSpitzer )
Thanks for checking this, here is the case which I faced:
1. We have a hive structure with partitions:
```
s3://bucket/data/id=1/name=test/timestamp=20231101191213/result.orc
s3://bucket/data/id=2/name=test-2/timestamp=20231101191213/result.orc
```
2. We have partitioning by `id, name, timestamp` in the table.
3. We run the procedure to `add_files` from hive into iceberg:
```
CALL iceberg_catalog.system.add_files(
table => 'test.test_name',
source_table => '`orc`.`s3://bucket/data/`'
)
```
4. After some time **uncontrolled** hive system adds a new partition and removes the old one(for `timestamp`, it needed to control process version in other systems like Trino to avoid duplicates), now we have:
```
s3://bucket/data/id=1/name=test/timestamp=20231101191213/result.orc
s3://bucket/data/id=2/name=test-2/timestamp=20231101191217/result.orc <- old timestamp removed, new one added
```
5. I want to sync the iceberg table to watch the new partition and remove removed from the bucket.
6. We run these steps to register that one changed partition, otherwise iceberg will fail with the file does not exist:
```
delete from test.test_name where 1=1;
CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	check_duplicate_files => false
)
CALL iceberg_catalog.system.expire_snapshots('test.test_name', TIMESTAMP '{now}', 1)
```
_use case can be changed with a new features at least to that:_
6.
```
delete from test.test_name where timestamp = 20231101191213; <- removed partitions from bucket
CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	duplicate_file_mode => 'skip'
) <- here we register only the new partition, instead of scanning the whole data again.
CALL iceberg_catalog.system.expire_snapshots('test.test_name', TIMESTAMP '{now}', 1) <- to expire old removed partition from snapshots
```
------------------
Also here is another workaround to add the full path to the new partition but I cannot just use the full path to the new partition because Iceberg will ignore partitions in the path and set them as null in a table, [here is link to issue](https://github.com/apache/iceberg/issues/7027)
```
CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/id=2/name=test-2/timestamp=20231101191217/`'
)

```

**Comment by szehon-ho** [comment]
```
delete from test.test_name where 1=1;
CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	check_duplicate_files => false
)
CALL iceberg_catalog.system.expire_snapshots('test.test_name', TIMESTAMP '{now}', 1)
```

I believe that this should work now, if you clear the entire table.  There was an issue before, but fixed by @dramaticlly , in #6889 , can you check if it fixes your issue?

**Comment by dramaticlly** [comment]
also what spark and iceberg version are you using at the moment? the #6889 was only introduced in latest spark 3.3, happy to backport if there's a need.

**Comment by sweetpythoncode** [comment]
@szehon-ho @dramaticlly Thanks for your reply! I run full data clear due to another issue, if you run `add_files` with `check_duplicate_files` two or more times it generates incorrect meta information for `record_count` and `file_size` for e.x.:
`CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	check_duplicate_files => false
)

returns in metadata for specific file(i check metadata through Trino)
record_count -> 1, file_size -> 500

i run once again due to new partitions added in the path
CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	check_duplicate_files => false
)

and now its returns in metadata for specific file(which is already registered in first step)
record_count -> 2, file_size -> 1000

so it will sum metadata information same files each time when i run **add_files** with **check_duplicate_files**, except if they are new in the path. If i run:
delete from test.test_name where 1=1;
Old files will be matched as new and that issue is fixed by this workaround
`

**Comment by dramaticlly** [comment]
@sweetpythoncode yeah I believe if we disable the flag to `check_duplicate_files` , then it's really rely on caller to cherry-pick the right data using partition filter. So if same add-files procedure is called repeatedly, this will cause same files being added more than once. 

I feel having a check duplicate option with 
- error (exit on first duplicate found)
- skip_import_if_same_name_found (skip if existing data file with same name found, import otherwise)
- off (import every data files regardless)

seem to be handy for problem described above. On the other hand, if we can have a dedicated deduplicated action/procedure, it also helps here (not just for import but also for other data quality protection)

**Comment by szehon-ho** [comment]
@sweetpythoncode Im not sure I get the issue you refer to, your code shows you add the file twice with check_duplicate = false, and metadata is duplicated?   

> CALL iceberg_catalog.system.add_files(
	table => 'test.test_name',
	source_table => '`orc`.`s3://bucket/data/`',
	check_duplicate_files => false
)

Did i get that right?

> (i check metadata through Trino)

Can you elaborate what you mean?  

I feel its the right behavior, if the file is duplicated, the metadata should be duplicated, not sure if I missed something.

Anyway, I'm not opposed to adding a mode and then allowing skip option if you guys think its useful, but I'm initially thinking a bit cautiously.  I initially see add_files as for a case where the source directory is no longer changing.  I think 'check_duplicates' is good, for job retries, when you dont know if the original add_file succeeded.

On the other hand, If the source directory always changing, and you want to use 'skip' to sync the new files, the problem is, it only handles append on source side.  There is no mechanism to remove data, in case where data is removed from source directory, so it doesn't feel very complete to me, and delete + re+add feels safer.
