### ISSUE TITLE
Publish to Maven Central (or Equivalent)

### ISSUE THREAD

**Issue by omervk** [apache/iceberg#65]
Now that the project is an Apache project, I'd love to see its artifacts published to a central repository, rather than relying on jitpack.io.

Whether the `iceberg-runtime` and `iceberg-presto-runtime` artifacts should be published too is debatable (as they're uber/fat-jars).

**Comment by vrozov** [comment]
For apache projects, artifacts should be published to the apache maven repository (they will be automatically available on the central repository as well).

**Comment by SurenNihalani** [comment]
+1 for this. 

I would be down to do the steps for this (https://github.com/osmlab/atlas/wiki/Gradle,-Travis-CI-and-Maven-Central) but there are two blockers here:
1. proving authorization to sonatype for this project (since I am not a member and they have a human approval process)
2. How would I give back the credentials to project for future amendments? (I am down to maintain them personally too if that helps us get this done)

**Comment by SurenNihalani** [comment]
could utilize https://github.com/1Password/1password-teams-open-source for storing the credentials here. (h/t: @shardulm94 )

**Comment by aokolnychyi** [comment]
I think we can close this one as we had the first Apache release and our publishing is configured.
