### ISSUE TITLE
BasicStats: TOTAL_RECORDS_PROP does not update after deletes

### ISSUE THREAD

**Issue by simhadri-g** [apache/iceberg#6709]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Hive

### Please describe the bug 🐞

**Issue:**

- Hive planner uses basic stats for query planning. 
- It obtains the total ROW_COUNT  during a tableScan  from SnapshotSummary.TOTAL_RECORDS_PROP .
-  https://github.com/apache/hive/blob/master/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java#L323
- But we noticed that **after deleting records**,  the SnapshotSummary.TOTAL_RECORDS_PROP  does not change. Only inserting new records updates this value.
- This has quite a bit impact on the Hive planner. 
- If a table had 1 million rows and 900k rows were deleted, hive planner still sees that the total number of records is 1 million. This is problematic during a Join query because hive depends on the total row count to determine the join strategy(map join vs merge join and map join being significantly faster for smaller tables).  The incorrect row count throws off the hive planner and forces it to use the slower merge join.

- I also noticed that **Apache spark** uses the same SnapshotSummary.TOTAL_RECORDS_PROP to obtain the total record count.
` long totalRecords =
          PropertyUtil.propertyAsLong(
              snapshot.summary(), SnapshotSummary.TOTAL_RECORDS_PROP, Long.MAX_VALUE);`
- I may be incorrect,  but I think spark is also affected by the same issue.
https://github.com/apache/iceberg/blob/a301a1f098b56babf5d2329b2d1f7bb9af9eb832/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java#L149 

**My doubts are**

-  Should we be taking the difference between  TOTAL_RECORDS_PROP and TOTAL_POS_DELETES_PROP as below to get the total row count (assuming there are no equality deletes )?:
`long totalRecords = Long.parseLong(summary.get(SnapshotSummary.TOTAL_RECORDS_PROP)) -
              Long.parseLong(summary.get(SnapshotSummary.TOTAL_POS_DELETES_PROP));`

- Is there a way to know the total number of rows deleted during equality deletes and obtain the correct row count?

I would be most grateful if someone could answer my questions. 

I apologize in advance if my understanding is lacking.

Thanks!

**Comment by boroknagyz** [comment]
I think we cannot assume that numRows(table) is equal to numRows(data files) - numRows(position delete files).

Because

- Concurent deletes might create delete files that reference the same rows:
https://github.com/apache/iceberg/blob/cecb10bb8ab0458fb3f6a650692a8e432f08cbd2/api/src/main/java/org/apache/iceberg/RowDelta.java#L131-L133

- Partial compactions, e.g.:

1. Table has data files: A, B, X and delete file: D
2. D references A and B
3. Now we rewrite the small files which are A and X
4. So now the table has data files AX', B, and delete file D
    (AX' doesn't have any deleted rows)
5. In this case numRows(table) is not equal to numRows(dataFiles) - numRows(deleteFiles)

(Though the above could be fixed by rewriting the delete file to D' to only reference rows in B. But I'm unsure if Iceberg does such a thing)
