### ISSUE TITLE
REST-Catalog: missing conflict-checks for `dropTable` and `updateTable`

### ISSUE THREAD

**Issue by snazy** [apache/iceberg#6710]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

Concurrent operations against the same table (like updating the same table from different clients) are not completely safe via the Iceberg REST API.

`deleteTable` offers no `UpdateRequirement` checks at all.
`updateTable` has `UpdateRequirement`s, but there is none that checks for example the latest metadata-location, which should change for every update.

**Comment by agnes-xinyi-lu** [comment]
for updateTable, there is UUID check for every commit, that should guarantee the uniqueness of the metadata. Isn't metadata location decided on the server side for each new commit (probably includes UUID in the path)?

**Comment by jhump** [comment]
It is unfortunate that this issue was auto-closed just because the right person didn't happen to see it. This is a legitimate issue, and there's another issue: there's not a safe way to delete a snapshot. While we can verify that none of the existing references have been concurrently modified when deleting a snapshot, we cannot verify that no **new* references were added. So the following sequence is possible:
1. Updater 1 loads the table and computes old snapshots to remove based on the set of snapshots and all refs.
2. Concurrently, updater 2 adds a new reference to one of those older snapshots.
3. Updater 1 now issues the call to remove snapshots and incorrectly drops the snapshot for the ref that was just added.

> for updateTable, there is UUID check for every commit, that should guarantee the uniqueness of the metadata. Isn't metadata location decided on the server side for each new commit (probably includes UUID in the path)?

@agnes-xinyi-lu, the UUID is a unique ID assigned to the _table_, not for each commit. It is the same for lifetime of the table and is not sufficient to determine if any of the table's metadata has changed (other than its UUID; and many catalogs forbid changing the UUID and only allow that update action at table creation).
