### ISSUE TITLE
Do you need to save all historical json files after cleaning up expired snapshots?

### ISSUE THREAD

**Issue by xuzhiwen1255** [apache/iceberg#6800]
### Question
This is the corresponding json file after I cleaned it up.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/105710753/217992943-217a18fc-708d-42a6-bb2b-8dd2ac355d64.png">

After cleaning and cleaning out expired snapshots and orphan files, the metadata-log still records all the metadata.json information.I don't think it makes sense since we've cleaned out expired snapshots and orphan files, and the file pointed to by metadatalog in the old metadatajson doesn't exist anymore,so I suggest that you can clean up the contents of the metadata-log after cleaning up expired snapshots and orphan files, and only keep the snapshot information that still exists.

If I understand wrong, please correct me, thank you.

**Comment by RussellSpitzer** [comment]
I think this is worth thinking about but I'm not sure it is as simple as this. Currently we don't really consider the json files to really have the same lifecycle as other metadata files. They aren't really expired since they aren't actually part of the history ...

**Comment by xuzhiwen1255** [comment]
> I think this is worth thinking about but I'm not sure it is as simple as this. Currently we don't really consider the json files to really have the same lifecycle as other metadata files. They aren't really expired since they aren't actually part of the history ...

However, if you write to iceberg through flink and have high real-time requirements, then the ck interval will be very short. If it runs for a long time, I think the metadata-log may be relatively large, although recording this It doesn't take up too much space, but it's redundant. After all, the manifest-list file has been deleted, which makes it meaningless. But I don't know if there are other considerations in the design here.

**Comment by amogh-jahagirdar** [comment]
Right I remember seeing this during testing when working on some changes to the expire snapshots behavior. Ultimately though as a default behavior I think this is expected, because the metadata file is the root of the metadata tree and is the source of truth for snapshots, and the associated manifest list/manifest metadata files which get cleaned up during expire snapshots. So from this angle, the `ExpireSnapshot`s API should just focus on cleaning up snapshots + manifest list/manifest files based on a single metadata file. `RemoveOrphanFiles` should also be focused on just removing the invalid files themselves and should not get in the business of rewriting metadata.

**For streaming use-cases would it make more sense to have some kind of "retain last n" metadata log entries table property?** 

That way the number of metadata log entries is always bounded and you can configure according to your desires. cc @stevenzwu who's more familiar on the flink side.

**Comment by amogh-jahagirdar** [comment]
Actually we already have this table property: `write.metadata.previous-versions-max` https://iceberg.apache.org/docs/latest/configuration/#write-properties
and looking at the code it enforces the metadata log size as well. @xuzhiwen1255 could you check if this works well for your streaming use case?

**Comment by xuzhiwen1255** [comment]
> Actually we already have this table property: `write.metadata.previous-versions-max` https://iceberg.apache.org/docs/latest/configuration/#write-properties and looking at the code it enforces the metadata log size as well. @xuzhiwen1255 could you check if this works well for your streaming use case?

Thank you for your reply.

I don't quite understand it.I guess if the manifest that this metadata.json file points to no longer exists, I guess it's an orphan file in a sense.

**Comment by amogh-jahagirdar** [comment]
@xuzhiwen1255 I was replying to 

> However, if you write to iceberg through flink and have high real-time requirements, then the ck interval will be very short. If it runs for a long time, I think the metadata-log may be relatively large, although recording this It doesn't take up too much space, but it's redundant.

The table property `write.metadata.previous-versions-max` can be configured so that you can control the metadata-log size. Please checkout https://iceberg.apache.org/docs/latest/maintenance/#remove-old-metadata-files. This has what you're looking for. Based on this you can configure what are considered the valid metadata files , and if there are any older metadata files they will get cleaned up during orphan file removal.

**Comment by xuzhiwen1255** [comment]
> The table property write.metadata.previous-versions-max can be configured so that you can control what is the amount of metadata files to retain (and thus the metadata-log size). Please checkout https://iceberg.apache.org/docs/latest/maintenance/#remove-old-metadata-files. This has what you're looking for.

Thank you for your reply. I know this parameter is used to delete metadata.

I have a question, that is, when a file is not referenced, it is an orphan file. If the metadata file does not reference the manifest file, should it be considered an orphan file?

**Comment by amogh-jahagirdar** [comment]
Sorry for the late reply @xuzhiwen1255 but yes if any file is no longer tracked by the current Iceberg metadata tree it will be considered as an orphan file.

**Comment by xuzhiwen1255** [comment]
@amogh-jahagirdar  thanks, got it.
