### ISSUE TITLE
Core: `currentAncestors` also returns the current snapshot

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#6930]
### Feature Request / Improvement

I noticed that the `currentAncestors` also returns the current snapshot. For me, an ancestor implies, only the parents and their parents of the current snapshot of a table.

https://github.com/apache/iceberg/blob/62eb74c5571c856bae5b32cacb6fb1ec4f380da9/core/src/test/java/org/apache/iceberg/util/TestSnapshotUtil.java#L117-L125

I noticed this when porting this logic to Python. I'm opening this ticket to see if we're okay with that, we want to change this?

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
I think it's expected, although do agree the name is a bit confusing. In most cases (I think) we want to just iterate over the current and the ancestor lineage, having the API return an Iterable which is inclusive makes it easier to iterate over (rather than have a variable for the current, and then loop over the parent).

 If there's a valid use case for excluding the current, perhaps another API which accepts a `boolean includeCurrent` could be offered. Then for compatibility purpose the original API calls the new API with `includeCurrent = true`

**Comment by rdblue** [comment]
Yeah, I agree it's not the best name. The reason to include current was that you normally want to include it in whatever you're doing, and having it in the loop is the easiest way. I also considered calling the method "history" or something, but history already has a special meaning in table metadata, which is not just ancestry but a log of how and when the current pointer has changed.
