### ISSUE TITLE
[Spark-3] Add missing abortStagedChanges support for StagedSparkTable

### ISSUE THREAD

**Issue by jerryshao** [apache/iceberg#698]

**Comment by jerryshao** [comment]
By revisiting the code, I found that most of the operations has cleanup methods `cleanUncommitted`, `cleanAll`, so seems there's no need to implement `abortStagedChanges`, what's your opinion @rdblue?

**Comment by rdblue** [comment]
@jerryshao, I think that we do need to implement the abort method. The abort is called if there is any failure with the final commit (see https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/WriteToDataSourceV2Exec.scala#L494).

That commit happens after the write operation has committed to the transaction, so Spark is no longer responsible for calling the writer's abort methods with each task's commit data. If the transaction has a successful write committed, then Spark won't clean up the data files that were created and Iceberg should. It's a narrow case, where the write succeeds and Iceberg's commit fails, but we should plan on handling it. Because it is such a narrow case, I didn't think it was very urgent.
