### ISSUE TITLE
How do I know which partition has delete files and the count?

### ISSUE THREAD

**Issue by kingwind94** [apache/iceberg#6995]
### Query engine

Spark

### Question

Using "select * from hive_catalog.iceberg_db.iceberg_table.partitions", we can query the data file count and record count of all the partitions. However, how do I know the delete file count of partitions? I need to rewrite data files and remove delete files.

**Comment by szehon-ho** [comment]
There is a pr for this https://github.com/apache/iceberg/pull/6661.

But for now, you can check out data_files and delete_files table.  Just group both by partition, do count(*).

The problem is now, RewriteDataFiles applies but doesn't remove delete files.  I'm planning to work on that now, via implementing RewritePositionDeleteFiles (minor compaction of delete files), which will during the rewrite, drop obsolete  position deletes.  It's in progress.

**Comment by kingwind94** [comment]
> There is a pr for this #6661.
> 
> But for now, you can check out data_files and delete_files table. Just group both by partition, do count(*).
> 
> The problem is now, RewriteDataFiles applies but doesn't remove delete files. I'm planning to work on that now, via implementing RewritePositionDeleteFiles (minor compaction of delete files), which will during the rewrite, drop obsolete position deletes. It's in progress.

Sorry but could you tell me how to query the data_files and delete_files table? "select * from hive_catalog.iceberg_db.iceberg_table.delete_files" doesn't seem to work. I am using 0.13.2 version.

**Comment by szehon-ho** [comment]
Yea I think it's released only in a more updated version, you check which has this pr:  https://github.com/apache/iceberg/pull/4243

**Comment by Fokko** [comment]
This works on Iceberg 1.1.0:
![image](https://user-images.githubusercontent.com/1134248/224109581-22939bac-36e3-4199-97fd-517b4cc63f56.png)
