### ISSUE TITLE
PyIceberg, Implement Limit filter to preview Table Data 

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg#7013]
### Feature Request / Improvement

it will be nice to have something like limit, so at least we can preview a table, currently the only way is to pass a filter and hope it will return smaller result set

### Query engine

Other

**Comment by Fokko** [comment]
I think this is a great idea. @djouallah are you interested in contributing to this? Or free for someone else to pick up?

**Comment by djouallah** [comment]
@Fokko  I am not a programmer, feel free to anyone to pick it up :)

**Comment by Fokko** [comment]
We probably want to include the changes in https://github.com/apache/iceberg/pull/7033/files. The `pq.read_table()` does not support limiting the number of rows being read. If we include those changes, we can do `ds.Scanner.from_fragment(...).head(num_rows=limit)` instead of `ds.Scanner.from_fragment(...).to_table()` when a limit is set. When we limit the number of rows being read we'll also reduce the time spent and the memory pressure.
