### ISSUE TITLE
 🐞Default table location may cause table to be lost

### ISSUE THREAD

**Issue by Zhangg7723** [apache/iceberg#7052]
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Flink Spark

### Please describe the bug 🐞

After these steps:
1. create table A.
2. rename table A to table B.
3. create table A.
4. drop table B or delete orphan files.

files of table A will be removed, because table A and B are stored in the same location. 
In my opinion, table location should be unique with uuid suffix when table is created.

**Comment by luoyuxia** [comment]
Seems reasonable. Hive will also change the location of A when rename to B.

**Comment by RussellSpitzer** [comment]
This is unfortunately very very difficult. Renaming a table would require moving all the associated files which is potentitally a very very large move, there are also currently no rules about an iceberg table having to have its files at the table location. We actually have many properties for doing just the opposite. 

That said I think we have several options of dealing with this,

See chat here
https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1679336480004559

And Issue here
https://github.com/apache/iceberg/issues/6890
and here
https://github.com/apache/iceberg/issues/4159


I think what we need to think about here is adding some additional safeguards on Remove Orphan files. For example we should check whether any known table locations in the catalogs could potentially conflict with our current table location (either matching or being a subdirectory)

Drop Table is basically safe since it only deletes known files, although some engines (Like Trino) also drop the root directory which is a separate issue.
