### ISSUE TITLE
Move InMemoryCatalog to core

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg#7115]
### Feature Request / Improvement

Currently the related classes are in test, I think it might also be useful to move it to core, so people can import the class and use it in external tests.

Any thoughts? @nastra 

### Query engine

None

**Comment by nastra** [comment]
I had a similar thought initially, but eventually decided that people can still access the `InMemoryCatalog` by using the `tests` classifier (in maven terms) / `testArtifacts` configuration (in gradle terms) when importing `iceberg-core`.

However, I'm ok moving to `iceberg-core` directly if we think this makes it easier to use. This would require also moving `InMemoryFileIo` + `InMemoryInputFile` + `InMemoryOutputFile`.

Thoughts on this @rdblue?

**Comment by nastra** [comment]
On the other hand I realized having `InMemoryCatalog` in test makes it more difficult to use it for testing in Spark because it would require an implementation dependency directly on the test artifacts via: `implementation project(path: ':iceberg-core', configuration: 'testArtifacts')`.

I've opened #7185 to move the `InMemoryCatalog` to core
