### ISSUE TITLE
SHOW CREATE TABLE returns invalid sql after upgrading to 1.2

### ISSUE THREAD

**Issue by looi** [apache/iceberg#7239]
### Apache Iceberg version

1.2.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

After upgrading to iceberg from 1.0 to 1.2, `show create table` returns invalid sql. The returned sql contains an extraneous `Iceberg` keyword after the `CREATE TABLE`.

For example, you can run the [quickstart docker image](https://iceberg.apache.org/spark-quickstart/) and the [Iceberg - Getting Started.ipynb](https://github.com/tabular-io/docker-spark-iceberg/blob/main/spark/notebooks/Iceberg%20-%20Getting%20Started.ipynb) and `SHOW CREATE TABLE nyc.taxis` returns `CREATE TABLE Iceberg demo.nyc.taxis ( ...`

**Comment by jack-o-hara** [comment]
This was caused by this commit 

https://github.com/apache/iceberg/commit/fc501f33761ae35a48f257d6d973d835fccd6da7#diff-d278772fd3dc1431367d81a075a79404d9e1acff28fab611ad4e3d1343133596R148

**Comment by amogh-jahagirdar** [comment]
I just verified this as well, I think we may want to revert the change because `name()` is a public API whose behavior is relied upon as we can see in this `SHOW CREATE TABLE` use case. To achieve the nice Spark UI improvements for observability for Iceberg tables, I think we should either leverage another API if one exists or add a new one, and integrate that in Spark. 

Thoughts @aokolnychyi @sumeetgajjar @szehon-ho @RussellSpitzer @singhpk234 @jackye1995 ?

**Comment by amogh-jahagirdar** [comment]
I published a PR to revert: https://github.com/apache/iceberg/pull/7273
