### ISSUE TITLE
[DISCUSS] Update metadata serially

### ISSUE THREAD

**Issue by waterlx** [apache/iceberg#732]
When trying to append data to a table in parallel, I see all the commits eventually wait in a queue and update the metadata one after another. I know that is to guarantee an atomic swap and get a linear history of changes. But it acts as we put a table-level lock on all the updates and if we would like to read the latest data of a table, we have to wait until all the swaps of the metadata are done. **It feels like to me that the updates are allowed to be taken in "parallel", but actually they are done in a "serial" manner (swap the metadata one after another)**.

Put feel free to correct me if I am wrong. So far, I do not have mature solutions to solve that, but some initial ones (like reduce the granularity of lock to partition level?), so I would like to raise this issue as a "discuss" one. Any comments are warmly appreciated.

**Comment by waterlx** [comment]
@rdblue @aokolnychyi Really appreciate it if you could share your ideas about that at your most convenience

**Comment by rdblue** [comment]
Commits don't wait in a queue. Committers write out metadata optimistically and will retry if another process commits first. The location swap must be done to get a linear history, but we try to make the remainder of the commit a light-weight operation by caching changes are reusing them.

For example, an append will create a new manifest file. When an append retries, it doesn't rewrite the manifest file from the first commit attempt. Instead, it updates the now-current metadata by adding the same manifest from the first try. That saves time and effectively does the majority of the metadata write work in parallel.

**Comment by waterlx** [comment]
@rdblue Got your idea, thank! I am reading the code to get a full understanding of your idea.
Ready to close this issue.

**Comment by aokolnychyi** [comment]
To add to the @rdblue's comment, Iceberg also looks at file level stats in some operations to decide if two commits are in conflict. Combined with caching of the work and cheap metadata retries, it allows us to commit concurrent changes to the same partition quickly (if operations are not in conflict).

**Comment by waterlx** [comment]
Thanks for sharing your insight! It is of great help for us.
I made some tests regarding the "metadata retries" based on Hive Catalog. It seems that it is not "cheap" 8-）

The report is as below:
**1. Environment**
(1) Linux, 8 core + 16G mem, *1
(2) Mac,  6 core + 16G mem, *1

**2. Iceberg table**
Partitioned by identity(field_a), 10,000 partitions. Each partition only contains 1 row. 

**3. Workload**
N delete concurrently. Each is to delete one row. So no conflict.
Our delete is Copy-on-Write, so the delete is mainly a overwrite or a delete call against Iceberg

**4. Setup**
(1) Local spark, master as local[*]
(2) Hive metastore, co-located on the same machine as Spark.

**5. Result** 
(Linux and Mac show similar results)
(1) 5 concurrent deletes: done in 13s
(2) 10 concurrent deletes:
a. Need to set commit.retry.num-retries to 10, done in 1m12s.
b. If commit.retry.num-retries takes the default (as 4), 5 deletes failed after 5 retries
(3) 50 concurrent deletes: 
a. Set commit.retry.num-retries to 50 (A smaller value might be also ok), done in about 20-25 min. But it is achieved only when I have a fresh metastore (restart the process).
b. When tested with a long run metastore, most of the delete (80%) stop retrying because the default timeout of commit.retry.total-timeout-ms (30min) is reached. The failed ones retried 7 times in average.

I am not sure if some bad settings (in Iceberg or Hive metastore...) lead to the result above. Please kindly share your insights or your setup/settings if it is ok.

It seems that here is no conflict but only competing for "metadata swap" and retries, because a lot of the following error message could be seen:
```
org.apache.iceberg.exceptions.CommitFailedException: Base metadata location 'aaa' is not same as the current table metadata location 'bbb' for table
```
So I am guess if the metadata swap is that "cheap"...  ^_^ Correct me if I am wrong.

**Comment by rdblue** [comment]
I don't think that this test workload is representative of real use cases. Iceberg is an analytic store, not a transactional store. 50 concurrent processes deleting a single row isn't something that we would expect to run. I'm not sure that 10 concurrent deletes is something we would expect, either, because we expect these to be grouped into larger operations. An operation in Iceberg is a change to the entire table state, not often to a single row.

That aside, this is very likely slow because this test case can't reuse work. I'm assuming that you wrote the 10,000 partitions in a single write, which will result in a single manifest file. That means that a delete has to scan that entire manifest and rewrite the entire manifest to delete a data file. If two processes try to delete at the same time, they will both rewrite the one manifest file in the table. One commit will succeed and the other will attempt to reuse the work it has done -- it would not rewrite the original manifest file, but that manifest has been replaced so it has to scan and rewrite the new manifest. You can see how the manifests tracking files in a table matter quite a bit for retry operations.

Retries are much quicker depending on the operation (e.g., append doesn't validate existing manifests) and the manifest layout in the table. Try running `RewriteManifests` to place each data file in a separate manifest. I think you'd get much faster retries in that case.

**Comment by atronchi** [comment]
For a more realistic use case, consider swapping the partition name `identity` in @waterlx case above for `date`, and a backfill which needs to overwrite the partitions running many days in parallel. I found this thread from exactly this use case, which triggered a deluge of Spark job failures failing on the `CommitFailedException`. Probably Spark should retry the commit in such cases instead of hard failing the job, which requires us to re-run the execution.

**Comment by rdblue** [comment]
@atronchi, Spark will actually retry. You can bump up the number of retries by setting the `commit.retry.num-retries` in [table properties](https://iceberg.apache.org/configuration/#table-behavior-properties). There are other settings for retries, like the wait time and max timeout as well.

With several commits happening at the same time, you probably just need to bump up the number of retries. The situation that @waterlx hit here was that there was a lot of work needed for each retry so the likelihood of conflict was really large. If you run into something similar, then I recommend using the `[RewriteManifests](https://iceberg.apache.org/maintenance/#rewrite-manifests)` approach I mentioned. That is now available as a [stored procedure](https://iceberg.apache.org/spark-procedures/#rewrite_manifests) so it is very simple to rewrite your manifests and avoid conflicts so retries can reuse more work and commit faster.

**Comment by pavarotti17** [comment]
is the "commit.retry.num-retries" accumulated throughout all the jobs in a spark application, or its just for each job and count number will reset to 0 after job success?

**Comment by alexyin1** [comment]
> is the "commit.retry.num-retries" accumulated throughout all the jobs in a spark application, or its just for each job and count number will reset to 0 after job success?

From my understanding, the number of retries is a unique number affiliated with each individual commit thread. https://github.com/apache/iceberg/blob/8520b5bc761910132c72c200f6ca5766cac6b958/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L416

ex: if there are four threads in the middle of commit when a fifth thread finishes commit, all four threads get to retry, up to commit.retry.num-retries times, so if commit.retry.num-retries=4, there are "16" max retries across four threads.
