### ISSUE TITLE
Flaky test: TestParallelIterable

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7367]
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

The test seems to be flaky so we should investigate it

```
TestParallelIterable > closeParallelIteratorWithoutCompleteIteration FAILED
    java.lang.AssertionError: 
    Expecting actual not to be empty
        at org.apache.iceberg.util.TestParallelIterable.closeParallelIteratorWithoutCompleteIteration(TestParallelIterable.java:63)
```

**Comment by amogh-jahagirdar** [comment]
Took a look in the code, and have a good idea what the issue is.  There's a race condition, the test relies on the underlying queue in `ParallelIterable` being populated by the time the non empty assertion is run, that's not guaranteed. I verified this theory by adding a sleep before offering to the queue here https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/ParallelIterable.java#L70

I'll work on a PR for fixing this test, we should be able to use Awaitility. Ideally we don't even have tests which rely on such timing but looking at the context https://github.com/apache/iceberg/pull/5887 I think it's important to have this specific case since we want to validate the memory is cleared up for engines.
