### ISSUE TITLE
Python: Replace MockCatalog with InMemoryCatalog

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg#7437]
### Feature Request / Improvement

We have two Catalogs in test, I think it would be good to merge them to avoid having duplicate/similar code.

### Query engine

Other

**Comment by DarthData410** [comment]
Hey @Fokko I reviewed the code within the test *.py files. The InMemoryCatalog can be found @: https://github.com/apache/iceberg/blob/251c9fa796157b06fc89e18fbb9a43045f459b07/python/tests/catalog/test_base.py#L52 

While the only reference I found to MockCatalog (as-typed) is @: https://github.com/apache/iceberg/blob/251c9fa796157b06fc89e18fbb9a43045f459b07/python/tests/cli/test_console.py#L103

With this in mind, would you like to see the /python/test/cli/test_console.py updated so that the MockCatalog is inherited from InMemoryCatalog found in test_base.py? Since they both inherit from Catalog class? Further, would InMemoryCatalog remain housed in test_base.py and have this imported from test_console.py? Or a new python file called test_catalogs.py (for example) created in /python/test/catalog/ to be imported from and used? 

Another option is the removal of reference to MockCatalog in test, and just reference InMemoryCatalog, but again would need to either have it imported from test_base.py or moved to its own python file to imported from. 

Either way I can complete this scope of work.
