### ISSUE TITLE
Pick split size automatically

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#7465]
### Feature Request / Improvement

I wonder whether we can pick the split size automatically instead of relying on users to supply a correct value. For instance, if the scheduler is FIFO, can we use the default cluster parallelism and the size of the data to be processed to come up with an optimal split size? We first find matching files and then plan splits so the split size can be dynamic, we just need a good way to estimate it correctly. It would be great if someone could investigate this a bit more.

### Query engine

Spark

**Comment by singhpk234** [comment]
linking previous discussions: 
- https://github.com/apache/iceberg/issues/7071

**Comment by aokolnychyi** [comment]
Oh, I did not know there was a previous discussion! Thanks for linking it here. Would you be interested to look into this, @singhpk234? I believe we can come up with something for Spark given that can access the default parallelism.

**Comment by singhpk234** [comment]
> Would you be interested to look into this, @singhpk234? 

+1, @aokolnychyi, Happy to work on it !

**Comment by aokolnychyi** [comment]
@rdblue @szehon-ho @RussellSpitzer @flyrain @jackye1995 @amogh-jahagirdar @nastra, any thoughts on when this may not work or should not be done?

**Comment by jackye1995** [comment]
Yeah this would also be very helpful for Trino because it can consume a large number of splits, most of the time the scan node does not fully utilize the cluster.

If the cluster size can be accessed, what would be a good default behavior? For example for a 30 node cluster, are we saying we should generate at least 30 splits? Or would it be even more optimal to generate a multiple of that like 60 or 90 splits? What would be a good criteria?

**Comment by aokolnychyi** [comment]
Historically, Spark advised users to have multiple either 1 or 2 or 4 tasks per slot. I am not sure about other engines, though. I think 2x slots is a good target but we should take the split size into account as well. If it gets too large, pick a bigger number of tasks.
