### ISSUE TITLE
Rename table property for enabling Parquet dictionary encoding

### ISSUE THREAD

**Issue by aokolnychyi** [apache/iceberg#7663]
### Feature Request / Improvement

See [here](https://github.com/apache/iceberg/pull/7301/files#r1199411330).

### Query engine

None

**Comment by amogh-jahagirdar** [comment]
Commented on https://github.com/apache/iceberg/pull/7301#issuecomment-1555346282 , we may want to see if we even want a table property in the first place, curious to know others thoughts @singhpk234 @Fokko @rdblue

**Comment by aokolnychyi** [comment]
I agree with @amogh-jahagirdar.

**Comment by Fokko** [comment]
> Dictionary encoding is useful for low cardinality columns, so the space difference between the two is negligible, with the tradeoff being deterministic lookups vs False positives from the bloom filter.

If it is low cardinality, the likelihood of having false positives is also low (assuming a fixed size bit for the bloom filter). I'm not sure if the dictionary is used for skipping data for example, but I don't think that should influence or impact this decision. Because if that's not the case, then we should fix that :)

I'm not super strong on this, but in the end, I think less configuration is better.

**Comment by rdblue** [comment]
I'm +1 for removing this property entirely. It is only used for testing and we've never had a request for it in production.
