### ISSUE TITLE
Is there any way to generate an empty partition without any data or delete files?

### ISSUE THREAD

**Issue by ZhendongBai** [apache/iceberg#7677]
### Query engine

spark

### Question

Is there any way to generate an empty partition without any data or delete files?

**Comment by Fokko** [comment]
@ZhendongBai I don't think this is possible today. Technically it is possible, but it doesn't make much sense (you would have a partition in the manifest-list, that would point to a manifest without any entries). What would be the use case of this?

**Comment by ZhendongBai** [comment]
> @ZhendongBai I don't think this is possible today. Technically it is possible, but it doesn't make much sense (you would have a partition in the manifest-list, that would point to a manifest without any entries). What would be the use case of this?

@Fokko In some of our user use cases, the execution of downstream tasks depends on the existence of upstream task result table partitions, without caring about whether the upstream tasks are completed. This is feasible in hive, but migrating to iceberg doesn't work, but we do not want to change user usage habits.

**Comment by RussellSpitzer** [comment]
In iceberg that doesn't happen @ZhendongBai, because it's an atomic system either the partition exists or it doesn't. More so, partitions only exist within metadata in the context of a committed datafiles. An Iceberg table by definition cannot have a partition without files. A particular partition value only exists as a field in the listing of a data file's metadata.

**Comment by ZhendongBai** [comment]
@RussellSpitzer I saw the Iceberg implementation as you said, thank you.
