### ISSUE TITLE
Parquet  : spark config "spark.sql.parquet.writeLegacyFormat = true " is useless

### ISSUE THREAD

**Issue by AlexLiue** [apache/iceberg#7706]
### Query engine

Hive: 3.1.3
Spark: 3.2.3
Iceberg: 1.2.1
Tez: 0.10.1

### Question

Hive query filed , becauses Hive Issue [https://issues.apache.org/jira/browse/HIVE-21987]
Is there anyway to set  parquet small decimal(p,s) type allways stored with base type FIXED_LEN_BYTE_ARRRAY(n)

**Comment by RussellSpitzer** [comment]
Iceberg has it's own parquet writers and parquet code, so Spark options will not necessarily work. 

As for Iceberg, our spec defines decimal as



Type | Parquet physical type | Logical type | Notes
-- | -- | -- | --
decimal(P,S) | P <= 9: int32,P <= 18: int64,fixed otherwise | DECIMAL(P,S) | Fixed must use the minimum number of bytes that can store P.
