### ISSUE TITLE
The Orc file (via iceberg)because large than Orc file(only via spark) ?

### ISSUE THREAD

**Issue by ZhendongBai** [apache/iceberg#7775]
### Query engine

spark sql 3.3.2

### Question

when I use spark 3.3.2，write the same table into hive partitioned table(table A) and iceberg(metadata store in hive) partitioned table(table B), both table are orc format and have same compression strategy, I do following test:
1. first create an iceberg table(table C) like hive table and add table A into table C (via spark add_files procedure)
2. compare table C and table B via select ".data_files" metadata table(column_sizes field, I extract the field size via field-id), the result show as below:
<img width="790" alt="image" src="https://github.com/apache/iceberg/assets/18043146/03311e28-e311-47fb-85d3-930b0f5bf435">
why the iceberg table string fields bytes size bigger than spark sql fields bytes size ? especially, map<string, string> and string type.

**Comment by shardulm94** [comment]
@ZhendongBai Since the issue is specific to string columns, I am guessing Iceberg and Spark might different setting for ORC's dictionary encoding for string columns. See https://orc.apache.org/specification/ORCv1/#string-char-and-varchar-columns

One way to verify this would be to run `orc-tools` command on the generated ORC files. See https://orc.apache.org/docs/java-tools.html. Take a look at the [encoding for the columns](https://orc.apache.org/docs/java-tools.html#:~:text=Encoding%20column%2014%3A-,DICTIONARY_V2,-%5B2%5D%0A%20%20%20%20Encoding%20column), if dictionary encoding is used it would be DICTIONARY or DICTIONARY_V2, if not it would be DIRECT or DIRECT_V2.

**Comment by ZhendongBai** [comment]
> @ZhendongBai Since the issue is specific to string columns, I am guessing Iceberg and Spark might different setting for ORC's dictionary encoding for string columns. See https://orc.apache.org/specification/ORCv1/#string-char-and-varchar-columns
> 
> One way to verify this would be to run `orc-tools` command on the generated ORC files. See https://orc.apache.org/docs/java-tools.html. Take a look at the [encoding for the columns](https://orc.apache.org/docs/java-tools.html#:~:text=Encoding%20column%2014%3A-,DICTIONARY_V2,-%5B2%5D%0A%20%20%20%20Encoding%20column), if dictionary encoding is used it would be DICTIONARY or DICTIONARY_V2, if not it would be DIRECT or DIRECT_V2.

@shardulm94  Thank you for your answer. I have checked the file encoding of both and they are DICTIONARY_V2 or DIRECT_V2(less 10,000 rows).
