### ISSUE TITLE
How to change the IP address of the original data when migrating data

### ISSUE THREAD

**Issue by zixiao144** [apache/iceberg#7827]
### Apache Iceberg version

1.2.1 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

At present, I have a problem. I have an old hadoop cluster and a new cluster. The old cluster IP address is 10.0.0.1, and the new cluster IP address is 10.0.0.2. How to migrate the old cluster's Data migration to the new cluster.
![image](https://github.com/apache/iceberg/assets/21092977/c2edb271-ac51-4428-a0a2-5563af9c2a63)

updateLocation().setLocation not work

**Comment by RussellSpitzer** [comment]
You actually have two problems. The "Location based table" means there is no catalog for your table. It's location is wherever it is. Basically when looking for a metadata.json file, it just looks in that spot. So you can't ever "change" this location because by definition the location of the table is where you are looking for the file.

The second issue is that even if you could update the location, or set a new data directory or metadata directory (those are options with a location based table), this would only effect new files. The metadata for old files would remain and the references to files would be unchanged. This means if you saved the full cluster path in the only metadata files, the only way to update the location would be to write new metadata files. Unfortunately, at the moment there is no automatic way to do this. Internally we have written small actions to do this but that code is not in OSS.

**Comment by zixiao144** [comment]
Thanks  you for your answer
