### ISSUE TITLE
Add View Support to Spark

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#7938]
### Feature Request / Improvement

Once #7880 is in, work could be started on supporting Views in Spark

### Query engine

Spark

**Comment by singhpk234** [comment]
@nastra @amogh-jahagirdar any plans for this, i think spark view interfaces are in it's just that complete wiring in spark is still pending via [1] , do you plan to pickup implementing spark view interfaces in iceberg so that once the complete wiring of view support in spark is merged then would start supporting it or is it like we should wait for spark view support to be complete and then we will start implementing the spark view interfaces in iceberg-spark ?

cc @jzhuge 


[1] https://github.com/apache/spark/pull/39796/files

**Comment by nastra** [comment]
@singhpk234 I was planning to pick up https://github.com/apache/spark/pull/39796, but I don't know yet whether we'd want to integrate those temporarily into Iceberg until they make it into Spark

**Comment by jzhuge** [comment]
Rebased https://github.com/apache/spark/pull/39796 to latest master branch

**Comment by jzhuge** [comment]
https://github.com/apache/spark/pull/39796#issuecomment-1839214419

**Comment by jzhuge** [comment]
Spark umbrella JIRA: [SPARK-31357](https://issues.apache.org/jira/browse/SPARK-31357)

**Comment by jzhuge** [comment]
Rebased https://github.com/apache/spark/pull/44197 with fixes for review comments and some unit tests

**Comment by rdblue** [comment]
I think we can call this one done with all of the PRs from @nastra that we've merged lately. Thanks @jzhuge and @nastra for getting this ready!
