### ISSUE TITLE
Pyiceberg StaticTable use the last metadata json URL when the full path is not provided

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg#7979]
### Feature Request / Improvement

when I write something like this, I expect pyicberg to pick the last metadata json file.

```
from pyiceberg.table import StaticTable
table = StaticTable.from_metadata(
"s3://yyyyyyyy/iceberg/metadata"    
)
```

### Query engine

Other

**Comment by Fokko** [comment]
Thanks for raising this, I can see how this is confusing. How the table is written? Ideally, this information comes from a catalog. When using the HDFS, there is a `version-hint.txt` that could be used, but this is [optional](https://github.com/apache/iceberg/issues/1496).

Some context. By design, Iceberg forbids list operations on the filesystem. This is because Iceberg is object-store-oriented, and list operations are expensive. S3 and GCS don't have a notion of a directory, and if you do a list, it might return a lot of files (which will be fetched paged, so this will result in many requests).

**Comment by djouallah** [comment]
I guess this is bad :), I know you need a catalog, it is just for convenience that's all, but no strong opinion either way :)

```
import boto3
import pandas as pd
s3_client = boto3.client('s3')
bucket = 'xxxxxxxxxxxxxxxxxxxxxxxx'
prefix = 'iceberg/metadata'
paginator = s3_client.get_paginator('list_objects_v2')
response_iterator = paginator.paginate(Bucket=bucket, Prefix=prefix)
file_names = pd.DataFrame(columns=['file','date'])
for response in response_iterator:
    for object_data in response['Contents']:
        key = object_data['Key']
        last = object_data['LastModified']
        if key.endswith('.json'):
            row = {'file': key,'date':last}
            file_names = pd.concat([file_names,pd.DataFrame(row,index=[key])] , axis=0, ignore_index=True)
file_names.sort_values(by=['date'], ascending = False, inplace=True)
file_names['file'].iat[0]
Latest_metadata ='s3://' + bucket +'/'+ file_names['file'].iat[0]
```

**Comment by rdblue** [comment]
I think the current behavior of `StaticTable` is what we want to encourage. If you want to find the "latest" using some file-level operation then that's up to you. But a static table should always be given a fully qualified location for the metadata file. We don't want to confuse people or introduce incorrect behavior by guessing which metadata file is correct.

That said, we could possibly have a method to "recover" table metadata by guessing. That way you could get the same result, but it is clear that you're doing something that is dangerous.

```python
io = ArrowFileIO(**config)
metadata_location = recover_metadata("s3://bucket/path/to/table", io)
table = StaticTable.from_metadata(metadata_location, config)
```
