### ISSUE TITLE
Api:Fix add the same listener to the same listeners queue multiple times

### ISSUE THREAD

**Issue by hejiay** [apache/iceberg#8107]
### Apache Iceberg version

1.3.0 (latest release)

### Query engine

Flink

### Please describe the bug 🐞

When I register create snaoshot event listener to listeners, I found that same listener would be added to the same listeners queue multiple times.
<img width="994" alt="image" src="https://github.com/apache/iceberg/assets/48463767/d4159c1d-dfe2-4cd4-96e4-ac8de5916425">
As you can see above, the kafkaCreateSnapshotEventToJsonListener@18286 was added to the same queue three times.
I will fix the bug.

**Comment by hejiay** [comment]
Thank you, the `KafkaCreateSnapshotEventToJsonListener` is my implementation of `Listener`, it sends create snapshot event to kafka topic when a snapshot was created.I register it into listeners when catalog initialize.
 And I found that when I execute the unit test `[TestFlinkHiveCatalog.testCreateCatalogWithWarehouseLocation()]`, the `HiveCatalog` would be initialized four times and the same KafkaCreateSnapshotEventToJsonListener object would be registered into the same eventType queue four times. So a snapshot event would be sent to kafka four times.

**Comment by hejiay** [comment]
This is my calling about  `register`:
<img width="603" alt="image" src="https://github.com/apache/iceberg/assets/48463767/66af3503-09be-4b5d-ab7c-f76b3f6c7d58">
They are executed when `HiveCatalog` is initialized.

**Comment by nastra** [comment]
Could you also please share the implementation of `KafkaCreateSnapshotEventToJsonListener` if possible? I'm mainly interested whether it implements `equals()` / `hashCode()`, because most listeners won't have that implemented and so adding a `if (!listeners.contains(...))` check wouldn't really help. Here's also a short example of how listeners are registered in the tests: https://github.com/apache/iceberg/blob/96f0f22bd829a5dbe0ac8194c70a878493300b7d/api/src/test/java/org/apache/iceberg/events/TestListeners.java#L27-L28

**Comment by hejiay** [comment]
This is my implementation of `KafkaCreateSnapshotEventToJsonListener`:<img width="1130" alt="image" src="https://github.com/apache/iceberg/assets/48463767/dbf51486-a8bc-46a9-86ef-24700a09ce57">
And I don't overwrite `equals()` and `hashCode()`
