### ISSUE TITLE
File leaking in RemoveSnapshots API

### ISSUE THREAD

**Issue by mehtaashish23** [apache/iceberg#822]
While using feature of Expire/RemoveSnapshots, I saw that the clean up operation of files happens, after successful commit (see below) of snapshot list and update to `version-hint.text`, which means that in case of intermittent/IOException from underlying store, we might end up leaving the files on disk, without any reference in table's latest version/snapshot list.You can see [this] to see the scenario, which I am trying to reproduce.

Usually these deleted files might have GDPR compliant data, so we should ideally have a way to do it in transaction, or make sure the files are deleted.

Code where we are failing to clean: https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L144

UT to reproduce: https://github.com/mehtaashish23/incubator-iceberg/pull/2/files

**Comment by mehtaashish23** [comment]
Since this is compliance related, one of the way is to put the onus of file deletion on client by providing callback API hooks on file deletion, and API hooks on transaction, so that client clean up the files for transactions, that are committed.

**Comment by rdblue** [comment]
I'm re-posting my reply from the dev list here:

The section of code that you point out is _mostly_ correct, but there is a case that we should fix. The reason I say "mostly correct" is that it has correct behavior and has error handling to ensure that as much of the work is done as possible.

Even if not all of the data is cleaned up, the behavior must be to throw an exception if and only if the metadata commit was successful. If the commit is successful, then throwing an error puts a client in an unrecoverable state because it thinks that the table hasn't changed when it actually did. If a client retries an operation that was already committed successfully, it could make incorrect changes to the table.

To address reliability, cleanup uses `Tasks` so that [a single failure doesn't prevent attempting to delete other files](https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L281) and files that can't be deleted are logged. There is similar failure handling while finding files to delete, so that [read failures don't prevent deleting](https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L291) as much data as possible. If you want even more guarantees, then you can add a custom delete method and persist the files to delete for another service to handle.

Now that I'm looking at this, one area that can be improved is the handling of manifest list files. There is [no failure handling while reading manifest lists](https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L333-L344), so we should add that.

I should also point out that this is not the only way for data to leak. For example, an executor failure in Spark can lead to a data file getting written by not committed to a table. I recommend having a way to periodically list table locations and check against the metadata tables, like `all_data_files` and `all_manifests`, to ensure that no files are left behind.

**Comment by prodeezy** [comment]
I believe Anton's latest work to cleanup orphan files [1] helps this case coz any dangling files would not show up in `all_data_files`. Although there is still handling to be done here. Will take this up to address pending issues.

[1] - https://github.com/apache/incubator-iceberg/pull/894

**Comment by rdblue** [comment]
Thanks @prodeezy! It would be great to fix the problem where a failure while reading manifests causes this problem.

**Comment by prodeezy** [comment]
Put up a PR with manifest-list failure handling : https://github.com/apache/incubator-iceberg/pull/928
