### ISSUE TITLE
SPJ joins in the outer join component of MERGE queries

### ISSUE THREAD

**Issue by dev-goyal** [apache/iceberg#8387]
### Query engine

Spark on EMR

### Question

In a `MERGE` query, is there a reason the inner join (`WHEN MATCHED`) is SPJ, but the left outer join (`WHEN NOT MATCHED`) is ShuffledHashJoin? Can post an example, but wondering if this is expected behaviour for some reason?

**Comment by RussellSpitzer** [comment]
So if I remember correctly the root of the issue is this. To do a SPJ we first align things based on partitions
```
[ Source Partition ] === [Destination Partition]
```
But Sometimes this balancing is not good so we want to be able to break up one of the two sides here into multiple pieces. To do that we split one of the sides up into multiple parts
```
[Source partition] === [Destination Partition Part 1]
[Source partition] === [Destination Partition Part 2]
[Source partition] === [Destination Partition Part 3]
```

For a "WHEN MATCHED" this is good, because if any task succeeds we can perform the action on the result. Each task can still be treated completely independently.

For "WHEN NOT MATCHED" we have a problem because then we can only apply the change if all of the tasks do not match for a given expression. We don't have a mechanism for doing a reduction over key (? or something like that) after doing our checks. This means we can't do our SPJ optimization and have to do a full shuffle.

I think I have that all right, but I'm mostly remembering our discussion when this was originally being implemented.

**Comment by dev-goyal** [comment]
Very helpful to know, thanks!
