### ISSUE TITLE
ICEBERG_CANNOT_OPEN_SPLIT: Error opening Iceberg split s3

### ISSUE THREAD

**Issue by FabricioZGalvani** [apache/iceberg#8427]
### Apache Iceberg version

1.3.0

### Query engine

Athena

## ICEBERG_CANNOT_OPEN_SPLIT: Error opening Iceberg split s3
Recurring Issue with AWS Athena When Running Queries on Iceberg Table.

## Description

I am trying to run queries on an Iceberg table using AWS Athena. The data is stored in S3, and I am using EMR 6.12.0, Iceberg 1.3.0-amzn-0, and Spark 3.4.0. The data ingestion process is running on EMR, which consumes data from a Kafka topic and ingests it into my Iceberg table in S3. Interestingly, sometimes the query runs successfully, but other times I encounter the following error in Athena:

> ICEBERG_CANNOT_OPEN_SPLIT: Error opening Iceberg split my_s3_path/data/id_pk_bucket=2/created_at_month=2023-08/my_parquet.parquet (offset=4, length=16038): Incorrect file size (16042) for file (end of stream not reached): my_s3_path/data/id_pk_bucket=2/created_at_month=2023-08/my_parquet.parquet

The error occurs only in Athena; running a query on the table using Spark works fine.

## Steps to Reproduce

1. Configured EMR with version 6.12.0 and Spark 3.4.0.
2. Set up an ingestion process on EMR to consume data from a Kafka topic and insert it into an Iceberg table on S3.
3. Created an Iceberg table on S3 using Iceberg version 1.3.0-amzn-0 and the following properties:

    ```sql
    OPTIONS (
        'format-version'='2',
        'write.target-file-size-bytes'='124217728',
        'history.expire.max-snapshot-age-ms'='172800000'
    PARTITIONED BY (bucket(10, my_pk), months(created_at))
    )
    ```
  
4. Data write process executed in Spark:
```python
query = (
                df.writeStream.format("iceberg")
                .outputMode("append")
                .trigger(once=True)
                .option("path", iceberg_table)
                .option("fanout-enabled", "true")
                .option(
                    "checkpointLocation",
                    checkpoint_location,
                )
            )
            
query.toTable(iceberg_table).awaitTermination()
```

5. Tried running a query in AWS Athena.
`SELECT * FROM "db"."table" limit 10;`

## Expected Result
I expected the query in AWS Athena to run without any issues.

## Actual Result

I am receiving a recurring error, ICEBERG_CANNOT_OPEN_SPLIT, which appears to indicate there is an issue with the file size or with the data streaming from S3.

## Additional Information

- EMR Version: 6.12.0
- Iceberg Version: 1.3.0-amzn-0
- Spark Version: 3.4.0
- We are using Glue as the catalog

I am open to providing more information as needed. Thank you!

**Comment by nastra** [comment]
It seems that this issue is related to Athena itself, meaning that you should probably try to report the issue to the Athena team, as the Iceberg community can't really help much here, because Athena deploys their own version of Iceberg

**Comment by pawankukreja01** [comment]
This error occurs only in Athena, while running a query on the table using Spark works fine. According to the [Amazon EMR documentation](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-iceberg.html), Apache Iceberg is an open table format for large data sets in Amazon Simple Storage Service (Amazon S3). It provides fast query performance over large tables, atomic commits, concurrent writes, and SQL-compatible table evolution. Starting with Amazon EMR 6.5.0, you can use Apache Spark 3 on Amazon EMR clusters with the Iceberg table format.

**Comment by mannerni** [comment]
Hi, We have faced similar error while using trino (479) with iceberg REST catalog (1.10.1). May be with trino as mentioned above. I suspect the issue is with optimization commands. We run optimize table by sizes (2/4/40/128MB) -> optmize manifest -> remove-snapshots -> remove-orphan-files. These 4 commands are run without any wait in between them. 
The leading command causing seems to be remove-orphan-files. The severe problem is we are not able to read that parquet file at all. Need some reliable handling and recommendation to avoid file corruption etc.
Error detail:
(Error opening Iceberg split s3://xxxxx-us-east-1-ts-zbc/t001/tablename/data/time_month=2022-03/id_bucket=3/20260209_035531_00064_t2j6q-856320fd-41db-4f68-acd1-317788e9238e.parquet (offset=14926945, length=3745233): s3://xxxxx-us-east-1-ts-zbc/t001/tablename/data/time_month=2022-03/id_bucket=3/20260209_035531_00064_t2j6q-856320fd-41db-4f68-acd1-317788e9238e.parquet)".
