### ISSUE TITLE
Pig should not rely on it own implementation of InputFormat

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#847]
Once #170 is completed, we should drop Pig's own implementation of InputFormat.

**Comment by rdblue** [comment]
This will require a little work because the InputFormat added in #843 assumes that there is only one read in a MR job, but Pig may run multiple. To avoid configuration collisions, Pig has a system for isolating the config for a scan, so we'll need to override some parts of the input format to store config differently.

**Comment by rdsr** [comment]
Yea, Pig is really bad at isolating per InputFormat configurations. This does seem like a Pig problem though and not an InputFormat problem. I hope this can be solved at Pig layer.
