### ISSUE TITLE
While decrypting iceberg table data using aws encyption sdk getting unsupported version error

### ISSUE THREAD

**Issue by Harsha-2264175** [apache/iceberg#8497]
I am performing Client-side encryption using aws encryption sdk on a csv file and after encryption storing the encrypted data into iceberg table.
then storing the encrypted data from iceberg table in s3 in csv format.
Performing decryption on the file stored in s3 and it is giving error that:
"NotSupportedError: ('Unsupported version 120', ValueError'120 is not a valid Serialization Version'"

I wanted to know if iceberg tables support this format or not? is, it possible or not.
Any support is helpful.

**Comment by amogh-jahagirdar** [comment]
Hey Harsha, I'm a bit confused on your workflow since Iceberg does not support CSV file format. Are you converting the CSV to Parquet and then doing addFiles?

Iceberg S3 integration supports the following server side encryption schemes: https://iceberg.apache.org/docs/latest/aws/#s3-server-side-encryption

Also just as an fyi: we're working on native encryption as part of the V3 spec https://github.com/apache/iceberg/projects/5
