### ISSUE TITLE
Document Azure and GCP integration

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8662]
We have a nice documentation for AWS (https://iceberg.apache.org/docs/latest/aws/) which explains if the warehouse path is S3, what configurations are needed for catalog and what dependencies are needed. 

Expecting a similar documentation (which also covers dependent libraries and all the authentication methods. For example Azure's accesskey, SAS token, principal)

**Comment by ajantha-bhat** [comment]
I am clearly not the expert here on this to add documentation. 
I saw that we have `ADLSFileIO` and `GCSFileIO` classes in code. 
But didn't find any catalog level examples or test cases for the same.

**Comment by ldacey** [comment]
I was confused with where to start on GCP. I haven't dug too deep because I know there is no write support yet for pyiceberg (and I do not have Spark installed at all), but I did want to test a few things.

I know I need a catalog and it looks like the easiest one might be my PostgreSQL cloud SQL database:

```
catalog:
  default:
    type: sql
    uri: postgresql+psycopg2://username:password@localhost/mydatabase
    
 ```

But I did not see a description of how to create the actual table, if the database needs to be named specifically, what is the schema of the database table? Does it get created automatically if I just create a "iceberg" database with a iceberg user and password?

Since I am on GCP, I know of Dataproc as well and I have explored Dataplex before, but I am not sure if I can use that as a catalog for pyiceberg. If I can use this, I am not sure if there is a benefit compared to the PostgreSQL approach above either way.

I might be missing something - I am basing this information off of this documentation: https://py.iceberg.apache.org/configuration/
