### ISSUE TITLE
Optimize metadata tables?

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#8714]
Just wondering why do we need both the entries table and data_files table? when one of the column from entries table is data_files. So, we can just use entries table with projection and filter? 

Similarly for delete files, position delete files can be extracted from entries table? etc

**Comment by ajantha-bhat** [comment]
cc: @szehon-ho

**Comment by ajantha-bhat** [comment]
@RussellSpitzer and @aokolnychyi: WDYT?

**Comment by RussellSpitzer** [comment]
I don't see any particular reason but I also don't see any reason to change an existing public api here.

**Comment by RussellSpitzer** [comment]
The case you have to balance against breaking public apis. User code that already uses these labels will fail if you remove the tables. So we need to be cautious about removing them, we could possibly lose them in an Iceberg 2.X but I'm not really sure we gain a ton of benefit by doing so. The maintenance cost of keeping them around is relatively small since they share code now and we can just remove documentation if we don't want users to use them.

**Comment by dramaticlly** [comment]
> My case for removing is to keep things simple and less metadata tables for users to understand and remember.

Deleting public facing code is probably one of the most difficult tasks, as I see metadata tables tend to grow over time. Personally i dont think user don't need to know all metadata tables all at once, it's like cook book or tool box where you can pick and choose yourselves.
