### ISSUE TITLE
Clean orphan data files 

### ISSUE THREAD

**Issue by waterlx** [apache/iceberg#873]
When the Flink program fails and restarts from the last successful checkpoint, the uncommitted DataFiles are abandoned as garbage. Need a cleaner here

**Comment by stevenzwu** [comment]
@waterlx current code does try to clean up uncommitted files after closing and uploading the files. We just swallow all exceptions if the deletion failed and rely on S3 bucket retention to purge garbage.
https://github.com/Netflix-Skunkworks/nfflink-connector-iceberg/blob/master/nfflink-connector-iceberg/src/main/java/com/netflix/spaas/nfflink/connector/iceberg/sink/IcebergWriter.java#L301-L313

@rdblue it will be great if `FileAppender` can provide an `abort()` API. Right now, Iceberg writer calls `close()` API, which also uploads the files even though we don't need it to be uploaded. It just creates cleanup work for us.

however, here is one case I am not sure how to do active cleanup. Writers uploaded the files, then failed/crashed. Where do we keep track of those files? In S3, these corner cases can be taken care of by bucket/prefix level retention policy.

**Comment by rdblue** [comment]
@stevenzwu, this isn't the responsibility of the appender. When writing a file, the write should invoke close to clean up resources whether or not the write was successful. If the write was successful, then the writer can move on. Otherwise, it is the writer's responsibility to delete the file.

The case you're talking about is specific to our internal S3 file system. When you don't know the internal details of the output stream, there isn't anything you can do to "abort" expensive operations. There is only close and clean up afterwards. That's why we haven't implemented this suggestion.

The right behavior here is to make a FileIO delete call to clean up a file if a write failed. In addition, tasks are responsible for deleting other completed data files that will not be committed because of task failure.

**Comment by rdblue** [comment]
I think we should clean up data files like this, but I don't think this needs to be part of the sink milestone, which is otherwise finished. I'm removing the milestone from this and will close it.

**Comment by rdblue** [comment]
@openinx, is this still a problem for the Flink sink?

**Comment by ahmedriza** [comment]
> The right behavior here is to make a FileIO delete call to clean up a file if a write failed. In addition, tasks are responsible for deleting other completed data files that will not be committed because of task failure.

Out of interest, how does Spark deal with this, i.e. if a writer fails before data has been committed to Iceberg, how do they handle the clean up of the orphan writes?
