### ISSUE TITLE
Investigate why dependabot didn't detect upgrades

### ISSUE THREAD

**Issue by jbonofre** [apache/iceberg#8764]
### Feature Request / Improvement

Apache Arrow 13.0.0 has been released, including a lot of bug fixes and improvements.

https://arrow.apache.org/release/13.0.0.html

I'm updating to test in Iceberg.

### Query engine

None

**Comment by Fokko** [comment]
Curious why this hasn't been picked up by dependabot.

**Comment by jbonofre** [comment]
@Fokko I found a few dependencies not detected by dependabot. I'm doing the updates and checking why dependabot didn't find it :)

**Comment by ajantha-bhat** [comment]
@snazy: Hi, Do you already have analyzed or have an info on this dependabot + version catalog problems?  
Do you recommend [renovateBot](https://github.com/renovatebot) to address this.

**Comment by Fokko** [comment]
I think this is because we limit to 5 PRs: https://github.com/apache/iceberg/blob/master/.github/dependabot.yml#L32

It looks like all five are open: https://github.com/apache/iceberg/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies I would be in favor of just removing this limit.

I would just set this to

**Comment by jbonofre** [comment]
@Fokko yes, I think we use the 5 PRs pool. +1 to upgrade. I'm doing it in a PR attached to this issue.

**Comment by ajantha-bhat** [comment]
Awesome. I can see the PR for Arrow now 👍

**Comment by jbonofre** [comment]
Happy to help 😃
