### ISSUE TITLE
iceberg-flink: Switch tests to JUnit5 + AssertJ-style assertions

### ISSUE THREAD

**Issue by nastra** [apache/iceberg#9087]
### Feature Request / Improvement

The goal is to switch all imports to JUni5 imports and to use AssertJ-style assertions

depends on #9077 #9078 #9079 

### Query engine

Flink

**Comment by ilyasahsan123** [comment]
hi @nastra , could you please assign this task to me?

**Comment by ilyasahsan123** [comment]
Hi @nastra,

I've submitted a pull request [PR #9565](https://github.com/apache/iceberg/pull/9565) to migrate unittests to JUnit5 in Flink v1.16.

I'm considering sending multiple pull requests for this migration since there are a lot of classes involved. This way, the review process can be more manageable, and you can provide feedback more efficiently.

Let me know if this approach works for you.

Thanks!

**Comment by tomtongue** [comment]
@nastra If no one is assigned with this, could you assign this with me? I believe there are three remaining tasks like flink, spark other versions, data for the migration completion.

**Comment by tomtongue** [comment]
@nastra I believe there is no JUnit 4 based classes in the Flink package, so we can close this issue.

**Comment by nastra** [comment]
thanks @tomtongue for taking care of this 💯

**Comment by tomtongue** [comment]
Thanks so much for your kind reviews! 😊@nastra
