### ISSUE TITLE
Implement Schema visitors for ORC value readers

### ISSUE THREAD

**Issue by rdsr** [apache/iceberg#920]
I wanted to see if I could implement #897 for ORC.  Given how ORC value readers are implemented for Iceberg-generics and Iceberg-spark, we have to do extra work. We will have to traverse Iceberg schema in `SparkOrcReader` just like we currently do in `GenericOrcReader` This traversal with Iceberg schema is duplicate work which can probably be abstracted in a visitor just as we do for `AvroSchemaWithTypeVisitor` .

This is a big refactoring change, but overall will improve readability and remove duplicate traversal code.  But we don't need to absolutely do it, we can traverse the Iceberg schema in SparkOrcReader and have an abstract StructReader which both Spark and data ORCreaders share.   

I'm +1 for doing it, but before doing wanted to see if folks are ok with it.  @rdblue, @shardulm94, what do u guys think?

**Comment by rdblue** [comment]
I think it's a good idea to add ORC schema visitors. I've found them helpful for Avro and Parquet because the recursive traversal is abstracted from the logic of each visitor. It's been easy to build new visitors. So I'm +1.

I also want to point out that this doesn't have to be one big refactor. We can keep the current code as it is and just use the visitors for new things, and slowly convert over to the visitors in places where it makes sense. A minimal start is to define the visitor interface and visit method, then use it for what you need to, like the read builder in this case.

**Comment by rdsr** [comment]
Thanks @rdblue . I'm taking this up as part of #897

**Comment by rdsr** [comment]
I plan to work on this this week together with #897 .

**Comment by edgarRd** [comment]
@rdsr we can probably close this issue since the visitors are implemented in https://github.com/apache/iceberg/pull/989 - right?

**Comment by rdsr** [comment]
Yea. I think we can close this. There are a few more visitors we could implement, but we'd take that up when required
