### ISSUE TITLE
Flink API  rewriteDataFile    How to set up scanning based on file size

### ISSUE THREAD

**Issue by GuoZhaoY** [apache/iceberg#9386]
### Query engine

      flink  code :  Actions.forTable(executionEnvironment,table)
                      .rewriteDataFiles()
                      .maxParallelism(maxParallelism)
                      .filter(Expressions.equal(xxxx,xxxxx))
                      .targetSizeInBytes(TARGET_FILE_SIZE)
                      .execute();

### Question

Using Flink for small file merging, assuming that I set the target size to 128M, I found that files larger than 128M were also scanned and merged. This is very unreasonable. I should scan and merge files smaller than the target size. How should I set this. The Filter() found here can only set partition related filtering conditions.

**Comment by pvary** [comment]
If a file is bigger than the TARGET_FILE_SIZE, it will create multiple splits when we read it. The last split of the file is a good candidate to add to merge with a new split, so it could be reasonable to rewrite these files.

For example, you have multiple files:
- File1: 158M
- File2: 158M

If the files are not rewriten, the resulting scan will have 4 splits (File1(0-128M), File1(129-158M), File2(0-128M), File2(129-159M)). If the files are rewritten the resulting scan will have 3 splits (File1' (File1(0-128)), File2' (File2(0,138)) and File3' (File1(129-158M) + File2(129-158M)))

Having 3 splits instead of 4 could have a serious performance impact.

**Comment by GuoZhaoY** [comment]
Thank you for your answer. I have understood your answer.
