### ISSUE TITLE
Partitioned table folder creation behaviour

### ISSUE THREAD

**Issue by Il-Pela** [apache/iceberg#9388]
### Query engine

Spark

### Question

Hi all,
I'm here to ask a question about partition folder creation behaviour while executing the following Python code 
`df.writeTo('db.table').partitionedBy(days('time')).using('iceberg').createOrReplace()`

Environment specs:
- **Spark** 3.3.2
- **Iceberg** 1.4.2 (iceberg-spark-runtime-3.3_2.12-1.4.2.jar)
- **Dataproc cluster image** 2.1.x-debian11

Why do I get the following structure in my bucket (GCS)?

```
db/
└── table/
    └── time=null/
        ├── time_day=2023-12-27/
        │   └── 00000-0-1f....parquet
        └── time_day=2023-12-28/
            └── 00000-0-2f....parquet
```

Does somebody know why I get the '_time=null/_' folder on top of the other "daily" folders? My '_time_' column doesn't contain null values.
What am I doing wrong/am I missing?

Available to give further details.

**Bonus question**: if I run an **expire snapshot** procedure on a partitioned table, will it cancel also the folders or will it leave an empty folder with respect to deleted data_files? (e.g. in my case if the parquet file of 27-12-2023 (_00000-0-1f....parquet_) will be deleted because of my expiring policy: will the folder '_time_day=2023-12-27/_' remain?)

Thanks 😄

**Comment by amogh-jahagirdar** [comment]
>Does somebody know why I get the 'time=null/' folder on top of the other "daily" folders? My 'time' column doesn't contain null values.
What am I doing wrong/am I missing?

So I don't think you're doing anything wrong, nor is there an issue in Iceberg as far as I can tell. The output file path contents are written with some details of the partition values (as you see time_day=XYZ). These path names include these details mostly for humans to inspect and be able to tell which files have which partition values. 
I don't know exactly why the top level part in the path is `time=null`, I'd need to inspect the code but it makes sense because really the partition values are produced from the day transform on the `time` column in your table. In the end though in terms of reads, the actual file path is inconsequential for query planning and should not cause any issues.

File paths are *not* used as the source of truth for partitioning in Iceberg , and rather it is the partition spec which is used to prune which files to read.

>Bonus question: if I run an expire snapshot procedure on a partitioned table, will it cancel also the folders or will it leave an empty folder with respect to deleted data_files? (e.g. in my case if the parquet file of 27-12-2023 (00000-0-1f....parquet) will be deleted because of my expiring policy: will the folder 'time_day=2023-12-27/' remain?)

When dealing with object stores (such as S3, GCS etc) it's important to remember, that there really are no "folders" as such since these are not file systems in the traditional sense. "/" is used as a delimiter in paths since it mostly helps humans with a sense of hierarchy. You can think of these as objects associated with a key (like a kv store) where the keys have delimiters like "/".

All that said, expire snapshots will remove all files which are considered unreachable by the current table state after snapshots have been removed.  In the example provided, if the parquet file for 2023-12-27 ends up being removed, you will no longer have a path with prefix time_day=2023-12-27 because in your example there are no other data files which have that partition value.

Let me know if this was useful, I'm going to close this but if you think there's a legitimate issue in Iceberg feel free to re-open.

**Comment by Il-Pela** [comment]
Hi @amogh-jahagirdar ,
thanks for your clarifications, really helpful!

> I'd need to inspect the code

The code is as simple as it can be (I'm just testing Iceberg's functionalities), I have a mock DataFrame to which I added the _time_ column, used for partitioning, in this way:
`df_with_timestamp = df_basic.withColumn('time', unix_timestamp(lit(timestamp), 'yyyy-MM-dd HH:mm:ss').cast("timestamp"))`

> When dealing with object stores (such as S3, GCS etc) it's important to remember, that there really are no "folders" as such since these are not file systems in the traditional sense. "/" is used as a delimiter in paths since it mostly helps humans with a sense of hierarchy. You can think of these as objects associated with a key (like a kv store) where the keys have delimiters like "/".

Yeah, you're right I haven't taken into consideration this behavior of object storages, my bad.
In the last few days, I give _expire_shapshots_ a try:
`spark.sql(f"CALL local.system.expire_snapshots( table => ''table_name", retain_last => 4, older_than => TIMESTAMP '{timestamp_4_days_ago}')")`

with this Spark configuration:
```spark = SparkSession.builder
.appName("MyApp")
.config("spark.sql.catalog.local", "org.apache.iceberg.spark.SparkCatalog")
.config("spark.sql.catalog.local.type", "hadoop")
.config("spark.sql.catalog.local.warehouse", MY_WAREHOUSE_ON_GCS)
.config("spark.sql.defaultCatalog", "local")
.config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
.getOrCreate()
```

And it worked as expected, deleting the snapshot older than 4 days. However, the reference to the "emptied" folder remained.
For instance the folder for  _time_day=2023-12-27_ remained so I checked for its contents:
- from the GCP UI there are no rows to display
- from the CloudShell interface I have 2 hidden empty objects each of them with size 0 bytes, with creation timestamp equals to the execution of the expire_snapshot procedure that deleted the files in the folder for the day.

Could they be some sort of "leftovers" left behind form the expire_snapshot procedure? Or maybe some kind of "soft_deletion" that my organization as in place in GCS? 
If you have any suggestion it would be really appreciated, in the meanwhile I'll dig deeper into it.

**Comment by amogh-jahagirdar** [comment]
> For instance the folder for time_day=2023-12-27 remained so I checked for its contents:

    from the GCP UI there are no rows to display
    from the CloudShell interface I have 2 hidden empty objects each of them with size 0 bytes and unnamed, with creation timestamp equals to the execution of the expire_snapshot procedure that deleted the files in the folder for the day. (gcloud storage ls -L command)

Could they be some sort of "leftovers" left behind form the expire_snapshot procedure? Or maybe some kind of "soft_deletion" that my organization as in place in GCS?
If you have any suggestion it would be really appreciated, in the meanwhile I'll dig deeper into it.


Hmm I don't think there should "leftovers" in the sense that the "folder" remains even if all the objects in it are deleted. I'm less familiar with GCS to be honest, so it's just probably lack of knowledge on my part there. I haven't seen anything like that in S3. 

> Or maybe some kind of "soft_deletion" that my organization as in place in GCS?

I'm guessing by soft deletion you mean you have versioning enabled and so deletes on the objects can be undone by reverting to previous versions. Maybe? Again, it's probably just my lack of knowledge on GCS, maybe it's something specific there but I don't recall seeing anything like that for S3.

Either way, I don't think there's an Iceberg issue since the relevant files are in fact being removed as part of the expire snapshots procedure. It's just surfacing in an unexpected way in GCS. 

I'll close this issue, but again based on your investigation if you still think that Iceberg is doing something wrong please feel free to reopen.
