### ISSUE TITLE
Purge support for Iceberg view

### ISSUE THREAD

**Issue by nk1506** [apache/iceberg#9433]
### Feature Request / Improvement

Currently Iceberg view doesn't have [Purge](https://github.com/apache/iceberg/blob/2101ac2e5528049688d4ce3ea2b4db861ea3c78b/api/src/main/java/org/apache/iceberg/catalog/ViewCatalog.java#L86) option.
Should we add purge for view also like [table](https://github.com/apache/iceberg/blob/2101ac2e5528049688d4ce3ea2b4db861ea3c78b/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L307) ? 

### Query engine

None

**Comment by nk1506** [comment]
cc: @pvary @nastra @rdblue

**Comment by ajantha-bhat** [comment]
@nk1506: Thanks for reporting. I think we should have this. Else, view metadata files will never be deleted from storage. 

I will assign this issue to you.

**Comment by rdblue** [comment]
What is the proposed behavior for a purge operation? How does this apply to views?

**Comment by nk1506** [comment]
With purge enablement similar like [dropTable](https://github.com/apache/iceberg/blob/66b1aa662761606d4d68d99371c62505e7ac2f1e/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L307) there should be a way to delete View Metadata files. 
In case of multiple version of views it can have multiple metadata files. Adding purge support will help to delete all the related metadata files. 

WDYT ?

**Comment by rdblue** [comment]
I think cleaning up metadata files is a catalog concern, not something that should be exposed to users through a PURGE flag. A user is not prepared to make a good choice about whether they should use PURGE. The user would assume that the metadata is cleaned up automatically. And if the user doesn't know to use PURGE, someone needs to clean it up anyway. This is distinct from the table case, where a PURGE signals that the user needs to get rid of the data _now_ rather than potentially keeping it around (most likely because of PII or other compliance concerns).

I don't think PURGE makes sense for views.

**Comment by ajantha-bhat** [comment]
Sorry. I am not very clear on this. 

I do see that `CatalogUtil.dropTableData` is cleaning up the table metadata files (`metadata.metadataFileLocation()`, `metadata.previousFiles()`). 

Why can't we have a same thing for views? If it is ok to do it for the table, Views can have it too? 

When the user drops the view, we do need to provide a way to get rid of the files related to that view?

**Comment by rdblue** [comment]
@ajantha-bhat, dropping old metadata files (if we track them) isn't the same thing as a `PURGE` option when dropping a view. For a view, there isn't anything to purge and I would not want to expose the option to the end user. To me, this is a catalog concern (how and when to clean up old metadata files) and could at most be configured in table properties, not SQL.
