### ISSUE TITLE
[bug]OversizedAllocationException when query data with Spark

### ISSUE THREAD

**Issue by zhangpenggh** [apache/iceberg#9820]
### Apache Iceberg version

1.4.3 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

I created an Iceberg table, wrote data into it using Flink, and when querying with Spark, I encountered the following error： 

org.apache.iceberg.shaded.org.apache.arrow.vector.util.OversizedAllocationException: Memory required for vector is (2147483648), which is overflow or more than max allowed (2147483647). You could consider using LargeVarCharVector/LargeVarBinaryVector for large strings/large bytes typesat org.apache.iceberg.shaded.org.apache.arrow.vector.BaseVariableWidthVector.checkDataBufferSize(BaseVariableWidthVector.java:435)at org.apache.iceberg.shaded.org.apache.arrow.vector.BaseVariableWidthVector.reallocDataBuffer(BaseVariableWidthVector.java:542)at org.apache.iceberg.shaded.org.apache.arrow.vector.BaseVariableWidthVector.handleSafe(BaseVariableWidthVector.java:1278)at org.apache.iceberg.shaded.org.apache.arrow.vector.BaseVariableWidthVector.setValueLengthSafe(BaseVariableWidthVector.java:989)at org.apache.iceberg.arrow.vectorized.parquet.VectorizedParquetDefinitionLevelReader$VarWidthReader.nextVal(VectorizedParquetDefinitionLevelReader.java:615)at org.apache.iceberg.arrow.vectorized.parquet.VectorizedParquetDefinitionLevelReader$BaseRead

**Comment by nazmiasri95** [comment]
Facing the same error as well. I'm storing a huge JSON in a string instead of struct due to schema evolving but not supported by type promotion. 
Can expect the JSON will be very huge. How do we allow large string to be store in Iceberg table?

**Comment by Xiangakun** [comment]
Set table property：`read.parquet.vectorization.batch-size` to a lower value, or just disable VECTORIZATION reader by setting `read.parquet.vectorization.enabled`=false should solve your problem.

**Comment by zhangpenggh** [comment]
> Set table property：`read.parquet.vectorization.batch-size` to a lower value, or just disable VECTORIZATION reader by setting `read.parquet.vectorization.enabled`=false should solve your problem.

It works, thank you

**Comment by tammyxiong** [comment]
also a quick note: the property setting is for the source table, not the target table

**Comment by firasomrane** [comment]
To not impact the read performance of all the consumers of the table you can set `spark.sql.execution.arrow.useLargeVarTypes` [spark config ](https://spark.apache.org/docs/latest/configuration.html#:~:text=spark.sql.execution.arrow.useLargeVarTypes) to `true`
only when running the spark jobs that will potentially fail with `OversizedAllocationException`, if you are using `spark >=3.5.0` .
If read performance is important for you on that table, setting `read.parquet.vectorization.enabled=false` will have a negative impact since that will disallow batch reads of rows from parquet files for all the queries.

Also setting that iceberg table property only for the spark sessions that you want and not as permanent for all the readers, would be also a desirable solution. I think you can set the reading options when reading with spark with `.option("read.parquet.vectorization.enabled", false).
But I think using the above spark conf will allow for a better performance if memory is not a problem.
