### ISSUE TITLE
Spark 3.5.0 `MERGE INTO` breaks

### ISSUE THREAD

**Issue by bk-mz** [apache/iceberg#9827]
### Apache Iceberg version

1.4.3 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Hey folks, when migrating from spark 3.4.1 to spark 3.5.0 we observe broken behavior of MERGE INTO:

```
merge into database.table base_table
using batch
on
    (base_table.data_load_ts >= TIMESTAMP '2024-02-19 15:00:00.0') and
    (base_table.id = batch.id)
when MATCHED then UPDATE SET *
when not MATCHED then INSERT *

24/02/28 10:37:33 ERROR MicroBatchExecution: Query [id = a43bffba-51a2-47b2-bf32-b978334ea6c9, runId = 7da1911b-8105-4b80-baa9-bf8ec4da9422] terminated with error
org.apache.spark.sql.catalyst.ExtendedAnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `base_table`.`data_load_ts` cannot be resolved. Did you mean one of the following? [`base_table`.`data_load_ts`, `batch`.`data_load_ts`, `base_table`.`date_sent`, `base_table`.`date_created`, `base_table`.`date_updated`].; line 4 pos 5;
'MergeIntoTable (('base_table.data_load_ts >= 2024-02-19 15:00:00) AND ('base_table.id = 'batch.id)), [updatestaraction(None)], [insertstaraction(None)]
```

The same works without problems on 3.4.1.

Please guide me if this is Apache Iceberg issue that you can help with.

Environment:

EMR 7.0.0
Spark 3.5.0
Iceberg 1.4.3

**Comment by manuzhang** [comment]
Same issue as reported in https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1704469705606459, can you try removing accept-any-schema table property if it's set?

**Comment by bk-mz** [comment]
Thank you! Will try that out and see if it helps.

**Comment by bk-mz** [comment]
Confirmed. 

```spark-sql ()> ALTER TABLE table UNSET TBLPROPERTIES ('write.spark.accept-any-schema');```

Though it's clear that:

![image](https://github.com/apache/iceberg/assets/892781/99fe139e-59fc-40bb-8575-cbeebe137ccb)

**Comment by bk-mz** [comment]
https://github.com/apache/iceberg/issues/5556

**Comment by ei-grad** [comment]
2026 update:

`MERGE WITH SCHEMA EVOLUTION` should work with Spark 4.1 support added in Iceberg 1.11+ (current master).

Another kind of summary of mentioned slack thread, for those who needs it, for history (still valid):

The `write.spark.accept-any-schema` property disables Spark's column resolution rules during MERGE statements:
1. SPARK-30609 made Spark skip resolution when this property is set (to let data sources handle it)
2. In Spark 3.4, Iceberg handled MERGE internally, so resolution worked
3. In Spark 3.5+, MERGE moved to Spark core (SPARK-46207), but Spark skips resolution due to the property
4. Result: No resolution happens at all, causing `UNRESOLVED_COLUMN` errors
