### ISSUE TITLE
Getting java.lang.NoSuchMethodError org.apache.iceberg.util.JsonUtil.mapper() With Hive catalog

### ISSUE THREAD

**Issue by ismailsimsek** [apache/iceberg#9848]
### Query engine

Java API and Hive Catalog

### Question

When using iceberg with Hive catalog getting following error on some environments. The error randomly appears in different environments

Full stack trace and configuration is here https://github.com/memiiso/debezium-server-iceberg/issues/271#issuecomment-1972347993

```
Producer failure: java.lang.NoSuchMethodError: 'org.apache.iceberg.shaded.com.fasterxml.jackson.databind.ObjectMapper org.apache.iceberg.util.JsonUtil.mapper()'
```

Original report https://github.com/memiiso/debezium-server-iceberg/issues/271

**Comment by nastra** [comment]
@ismailsimsek this is typically a sign of mixed dependency versions on the classpath. I think the problem is that Debezium is using [Spark 3.3](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/pom.xml#L53), which requires [Jackson 2.13.4](https://github.com/apache/spark/blob/branch-3.3/pom.xml#L175-L176) but Debezium uses [Jackson 2.14.2](https://github.com/memiiso/debezium-server-iceberg/blob/master/pom.xml#L33).

If you want to use Jackson 2.14.2, then you'd need to upgrade Spark to 3.4.

**Comment by nastra** [comment]
Additionally, make sure to sync up the AWS SDK version to what the respective [Iceberg version](https://github.com/apache/iceberg/blob/f1459e214493149f30d13e757b91aa18479778d9/gradle/libs.versions.toml#L31) is using. The same applies for GCP/Azure dependencies. Otherwise you'll be having the same issue with those dependencies

**Comment by ismailsimsek** [comment]
Thank you @nastra i will check it

**Comment by ismailsimsek** [comment]
Fixed https://github.com/memiiso/debezium-server-iceberg/issues/271
