### ISSUE TITLE
Automatically publish open-api.yml to swaggerhub with every release.

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#9867]
### Feature Request / Improvement

Officially having a versioned swagger-hub page published for Iceberg REST open-api spec seems like a good idea for me for people to refer it. 

Example from projectNessie: 
https://app.swaggerhub.com/apis/projectnessie/nessie/0.77.1

We can use github workflow for automating it on every release.  (something like below)
https://github.com/projectnessie/nessie/blob/683a45fc80e6d0e7e8f46554718710cf7b532124/.github/workflows/release-publish.yml#L261-L271

Note: There are few unofficial publication of the Iceberg open API spec (without proper versioning)
https://app.swaggerhub.com/apis/vivek-zemoso/Demo-Apache-Iceberg-OpenAPI/1.0

### Query engine

None

**Comment by ajantha-bhat** [comment]
@jbonofre, @nastra, @snazy: Thoughts? 

I think one unknown for me is do we need apache infra support for this to officially have an account for Iceberg in swagger-hub?

**Comment by jbonofre** [comment]
@ajantha-bhat I think it's a good idea to have an official OpenAPI published. That's part of the idea to deal OpenAPI yml like a RFC:
- changes submitted should be discussed and voted
- documentation is super important (part of the RFC)
- published publicly
- ref impl in the project in order to test it cleanly

So, I think your proposal is going in the right direction. Happy to work on this as part of the general effort ;)
