### ISSUE TITLE
About /v1/config REST API endpoint

### ISSUE THREAD

**Issue by ajantha-bhat** [apache/iceberg#9880]
### Query engine

NA

### Question

I started going through the REST API spec. 
I couldn't understand about optional `warehouse` parameter in `/v1/config` endpoint. 

The user can specify the overrides by passing a value in `warehouse` as part of `GET /v1/config`? 
I thought `GET /v1/config` will give all configurations (defaults and overrides). 

If we are using this param for overrides, why are we not supporting other properties from https://iceberg.apache.org/docs/latest/configuration/#catalog-properties?

**Comment by ajantha-bhat** [comment]
maybe cc: @nastra, @danielcweeks, @rdblue

**Comment by ajantha-bhat** [comment]
ping

**Comment by nastra** [comment]
The `warehouse` query parameter for that endpoint refers to https://github.com/apache/iceberg/blob/5b84f34a5386fc61b17bfe7dc7c1cbe565550958/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L896-L906, indicating that the client can send the used warehouse location to the server to keep the location in-sync.

The response in the config endpoint then has defaults and overrides, which can control how the catalog is configured. I don't think any other catalog properties make sense to pass as a query param, because `warehouse` might be the only one that can be configured on the client-side and might be used on the server-side.

**Comment by ajantha-bhat** [comment]
Thanks. But may be we should use a separate PATCH/PUT instead of sending in a GET request as we want to update the resource here.

**Comment by danielcweeks** [comment]
> Thanks. But may be we should use a separate PATCH/PUT instead of sending in a GET request as we want to update the resource here.

The `warehouse` config is really not something the client should have control over.  In some catalog implementations, the client is also acting as the catalog.  For example, the JDBCCatalog is connecting directly to the database.

This isn't a resource that the client should be able to update, just receive information about, which is why the config route is just a `GET` method

**Comment by ajantha-bhat** [comment]
Thanks for the clarification.
