### ISSUE TITLE
[core] Table commit successful but metadata json was never created leaving table in a bad state

### ISSUE THREAD

**Issue by abmo-x** [apache/iceberg#9997]
### Apache Iceberg version

1.3.1

### Query engine

Flink

### Catalog
Hive Metastore

### File IO
Hadoop S3A

### Please describe the bug 🐞

Iceberg table points to a metadata.json that failed to upload to s3. Due to this the table was not loadable as latest metadata json was not found 
`The main method caused an error: Failed to open input stream for file: s3a://bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json`

### Expected:
when s3 upload to metadata json failed, iceberg's hive commit should have failed as write metadata failed.

### Actual:

Iceberg logs show that commit was successful

`2024-03-06T23:06:36.160+00:00 INFO org.apache.iceberg.hive.HiveTableOperations 
     Committed to table iceberg.default.some_table with the new metadata location s3a://bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json `

#### However the upload to s3 failed!
`
06/Mar/2024:23:06:01 +0000 REST.PUT.OBJECT	prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json	"PUT /bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json HTTP/1.1"	**400	IncompleteBody**`

#### Flink pipeline fails around same time as upload 

`2024-03-06T23:06:36.110+00:00  WARN org.apache.flink.runtime.taskmanager.Task 
    message:  Source: table[11] -> PythonCalc[12] -> (Calc[13] -> IcebergStreamWriter, Calc[15] -> IcebergStreamWriter) (2/4)#0 switched from INITIALIZING to FAILED with failure cause:`

**Comment by steveloughran** [comment]
You know, if there's a bug in a related ASF project, _you are free to file a bug report there_

This problem was addressed in https://issues.apache.org/jira/browse/HADOOP-19221, _S3A: Unable to recover from failure of multipart block upload attempt "Status Code: 400; Error Code: RequestTimeout"_, which is a broader issue that S3FileIO may not have hit yet: V2 SDK can't recover from a transient 500 error if it happens during a part upload of a large multipart object.

It's in Hadoop 3.4.1, which raises InterruptedIOException here and on CancellationExceptions raised from interruptions of background threads of multipart uploads.
